### ISSUE TITLE
Is it possible to get lets-chat as small widget window over any website page.

### ISSUE THREAD

**Issue by Koka5** [sdelements/lets-chat#110]
for example, the way gmail chat is provided.
means every room should get a little widget window (which can be minimized or maximized)
on bottom right or bottom left.

so that user can do other other simultaneously, on the same page, while having chats.

**Comment by tvvocold** [comment]
Hope u guys can make it Cooler  than irc / hangouts!

**Comment by hhaidar** [comment]
No plans do this at the moment :(

Maybe it's something a custom client can take care of.
