### ISSUE TITLE
Support Docker

### ISSUE THREAD

**Issue by geoffwhittington** [sdelements/lets-chat#124]
Create Docker file and test it for 0.3

**Comment by geoffwhittington** [comment]
@doganaydin Can you help us with this?

I'm sure most of what is in master will work for 0.3. There is some new stuff we did to support XMPP that may impact things

**Comment by sibartlett** [comment]
I've added a Dockerfile to the release/0.3.0 branch.

**Comment by hhaidar** [comment]
Beast.

**Comment by funkaoshi** [comment]
Nice. I'm going to check this out.

**Comment by sibartlett** [comment]
I added basic instructions to the readme.

XMPP is not enabled by default - as it requires further configuration by the user/administrator.
