### ISSUE TITLE
Atwho: Show a flag indicating if user is online and in current room

### ISSUE THREAD

**Issue by sibartlett** [sdelements/lets-chat#139]

**Comment by geoffwhittington** [comment]
What is the value of this flag?

**Comment by sibartlett** [comment]
The current atwho was designed to show all registered users. The intention of the flag was to indicate which users in the atwho list are currently in the same room.

However, I think the idea of having two atwho options, @ and !, might be a nicer solution. The first only listing users currently in the room, and the second for all users.

**Comment by sibartlett** [comment]
We now use @ for users currently in room, and @@ for all registered users.

**Comment by hhaidar** [comment]
Someone needs to document this and all the other functions, preferably before we go into master.
