### ISSUE TITLE
Add XMPP user documentation in web interface

### ISSUE THREAD

**Issue by sibartlett** [sdelements/lets-chat#141]

**Comment by sibartlett** [comment]
Have adde basic connection details (username/port).

**Comment by geoffwhittington** [comment]
It would be good to add the multi user chat server name, too. conference.`server.name.com`. On Android Xabber I had to specify that.

I noticed the icon incorrectly matches the notifications modal, instead of the XMPP/Jabber one in the dropdown.

**Comment by sibartlett** [comment]
I've fixed the icons, and expanding on the connection info. I also added a list of supported clients - which we can expand on.
