### ISSUE TITLE
Atwho: shows users who are not in a room

### ISSUE THREAD

**Issue by geoffwhittington** [sdelements/lets-chat#170]
The user list that pops up when you type `@` includes users who are not in the room. This is misleading since we don't have the ability yet to send messages to users who aren't in a room,

**Comment by geoffwhittington** [comment]
@hhaidar - Simon tells me this is expected behavior?

**Comment by hhaidar** [comment]
Yea, it's nice to at people even if they're offline. We have another ticket open about showing online/offline status in the atwho plugin.

**Comment by sibartlett** [comment]
We now use @ for users currently in room, and @@ for all registered users.
