### ISSUE TITLE
Registering same user triggers server error

### ISSUE THREAD

**Issue by geoffwhittington** [sdelements/lets-chat#179]
The frontend doesn't tell a user if they have attempted to register a user which already exists

**Comment by sibartlett** [comment]
We also have the same issue with users who try to login via ldap/kerberos when another user already has the same username or email.

**Comment by geoffwhittington** [comment]
This looks good @hhaidar It works for local, will it also work for ldap/kerberos?

**Comment by hhaidar** [comment]
Nope, the login method's 400 error sends back an ambiguous message right now

**Comment by hhaidar** [comment]
It should tell you this now, albeit in an awkward way with sweetalert.
