### ISSUE TITLE
unable to create an user with the latest release 0.3.0

### ISSUE THREAD

**Issue by oinirio** [sdelements/lets-chat#183]
After cloning:

`cp settings.yml.example settings.yml`

`grunt bower`

`grunt build`

`npm start`

and after going to [localhost:5000](http://localhost:5000) when click in "I need an account" nothing happens.

**Comment by hhaidar** [comment]
Yea the  bower file broken. Try doing ```git reset --hard``` and then ```npm start```

**Comment by oinirio** [comment]
thanks it's working now

**Comment by hhaidar** [comment]
Awesome, glad I could be of help!
