### ISSUE TITLE
anybody it's running LCB on linux mint

### ISSUE THREAD

**Issue by oinirio** [sdelements/lets-chat#188]
I was running on a linux box (ubuntu 14.04) and vagrant (ubuntu 14.04) but when trying to run the release/0.3.0 on a new linux mint pc was impossible due to a build error in **node-krb5**

I try with the node on the repo `v0.10.26` and with `v0.10.35..36` from nvm

    npm ERR! node-krb5@0.0.5 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the node-krb5@0.0.5 install script.
    npm ERR! This is most likely a problem with the node-krb5 package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls node-krb5
    npm ERR! There is likely additional logging output above.
    npm ERR! System Linux 3.13.0-37-generic
    npm ERR! command "/home/carl1/.nvm/v0.10.36/bin/node" "/home/carl1/.nvm/v0.10.36/bin/npm" "i" "node-krb5"
    npm ERR! cwd /home/carl1/server/lets-chat/node_modules
    npm ERR! node -v v0.10.36
    npm ERR! npm -v 1.4.28
    npm ERR! code ELIFECYCLE
    npm ERR! not ok code 0

**Comment by sibartlett** [comment]
You need the krb5-dev package installed.

Unfortunately I do not know Mint OS - so can not give much direction in how to go about it. Maybe it's available from the Mint's package manager?

**Comment by sibartlett** [comment]
The package you require might be [krb5-multidev](http://community.linuxmint.com/software/view/krb5-multidev).

**Comment by oinirio** [comment]
installing `libkrb5-dev` fix this

**Comment by sibartlett** [comment]
Thanks for letting us know which package you used!

We'll update the documentation to include this dependency.
