### ISSUE TITLE
transcript "to date" is slightly truncated

### ISSUE THREAD

**Issue by geoffwhittington** [sdelements/lets-chat#194]
Screenshot below shows the trailing digit slightly truncated:

![lcb-transcript-truncated](https://cloud.githubusercontent.com/assets/1770544/6069166/30e275ca-ad50-11e4-837b-9e696511c01e.png)

**Comment by sibartlett** [comment]
Can you take another look, and let me know if my recent change has improved it for you?

**Comment by geoffwhittington** [comment]
On ChromeOS is looks good! Thanks
