### ISSUE TITLE
Show imgur links in-line

### ISSUE THREAD

**Issue by kevindelaney** [sdelements/lets-chat#195]
It would be great if we could show imgur links in this format in-line: https://imgur.com/pocjDSL

Note that a specific jpg or png was not linked, but the default imgur link.

Relevant imgur API docs here: https://api.imgur.com/endpoints/image

**Comment by tejasmanohar** [comment]
Instead of being specific to imgur, I suggest using https://github.com/discourse/onebox or similar library for website previews-- imgur will work with this, too :+1:

**Comment by PerfectCarl** [comment]
Link expansion would be a nice addition!

**Comment by hhaidar** [comment]
Closing this for the more general #244
