### ISSUE TITLE
Passworded room

### ISSUE THREAD

**Issue by pathetiq** [sdelements/lets-chat#198]
Hi, Anyway to secured a room to limit a number of people?

**Comment by sibartlett** [comment]
We don't currently have passworded rooms, but it is a feature we are considering for a future release.

**Comment by kevinrood** [comment]
+1 for this

**Comment by tejasmanohar** [comment]
+1 - but I don't like passwords, maybe invite-only groups like Slack

**Comment by hhaidar** [comment]
+1 to invites, but @pathetiq's use case might be different

**Comment by sibartlett** [comment]
XMPP supports passwords rooms too!

**Comment by pathetiq** [comment]
Yes that's why I asked for password instead of invite, XMPP has this support already. And from my view, it is easier to manage user with password than invite, has you can change to password to block them out.

**Comment by kevinrood** [comment]
My use case would be to setup rooms that only certain users could access. I would prefer not to have a password per room. Instead, some type of admin would assign users to a room and only assigned users could access it.

That's probably a different use case than initially suggested - but I think that's a common use case across business organizations.

**Comment by sibartlett** [comment]
We'll consider supporting supporting both use cases. Passwords rooms will probably come first, as it's simpler to implement.

**Comment by funkaoshi** [comment]
@kevinrood's idea would probably overlap with how you might also do private messaging.

**Comment by drakmail** [comment]
+1 for this

**Comment by xyc** [comment]
+1 for invite-only room

**Comment by bado57** [comment]
+1 definitely private chat and password rooms.Thanks

**Comment by mikeohara** [comment]
+1 for sure

**Comment by chiel1980** [comment]
+1

**Comment by powange** [comment]
+1

**Comment by jangrewe** [comment]
+1 for passworded
+0.5 for invite-only

**Comment by mikeohara** [comment]
Invite only would be interesting. How would that workflow work? 
IRC style? url token? or still utilizing a password?

Unlisted rooms could also be useful as a derivative of this. (do not show up on the master list, require an invite or knowledge of the link).

I also wonder about "Off the Record" rooms that do not store transcripts.

**Comment by xhs** [comment]
+1 for invite-only room

**Comment by joschi127** [comment]
+1 for direct messages to users (maybe show people in addition to rooms on the left side, like HipChat does?)

**Comment by joschi127** [comment]
ahhh... i guess direct messages are #282

**Comment by sibartlett** [comment]
Passworded rooms are now on master.

**Comment by chiel1980** [comment]
Hi,

It seems the docker build does not work anymore, or at least I only see the following:

letschat_1 | 
letschat_1 | > lets-chat@0.4.0 prestart /usr/src/app
letschat_1 | > migroose
letschat_1 | 

I removed all images, containers and even the git clone and cloned a new one but I get the same behaviour.
Also, I see the options in the default.yml where we can enable passworded rooms but is there some documentation of how this has to be set and should it be set in the settings.yml ?

Cheers,

Michiel
