### ISSUE TITLE
How do u  get it run in OpenShift(a free PAAS)?

### ISSUE THREAD

**Issue by tvvocold** [sdelements/lets-chat#199]
Anyidea?

**Comment by funkaoshi** [comment]
If you are just connecting to a RedHat VM, you shoud be fine so long as the box has the pre-requisites needed for the application. Is there some issue in particular you are stuck on?

**Comment by sibartlett** [comment]
@funkaoshi I think we need to make changes to changes to LCB, to support OpenShift.

OpenShift seems to be a bit a like Heroku - where we have to look for specific env variables.

I've signed up for a free OpenShift account, and am looking into it. If it's not much work, I'll get it working.

**Comment by geoffwhittington** [comment]
Do we want to consider allowing users to specify environment variable names in the settings file as a more general solution?

**Comment by tvvocold** [comment]
@sibartlett Cool! Thx!

**Comment by sibartlett** [comment]
@tvvocold I tried OpenShift out yesterday. It was a little disappointing because their admin console website kept crashing, and I somehow ran into a storage limitation with the free plan. I'll take a look at it again sometime, but it won't be for a couple of weeks.

You should be able to get Let's Chat working with a Node.js cartridge, and a MongoDB cartridge/add-on. To configure the application, you can use the [environment variables](https://github.com/sdelements/lets-chat/wiki/Environment-variables) that we have documented.

**Comment by tvvocold** [comment]
emm, have u run it by edit the action-hooks?

**Comment by sibartlett** [comment]
No, I didn't have the time to look into [acton hooks](https://developers.openshift.com/en/managing-action-hooks.html).

I will come back and take another look at this. However, we're very constrained for time right now.

**Comment by tvvocold** [comment]
OK,Cool!

**Comment by tvvocold** [comment]
BTW: Is that free i deploy letschat to heroku?(They only got 5Mb datebase)

**Comment by sibartlett** [comment]
Let's Chat will work for free on Heroku, but yes the database will be limited to 5MB - unless you pay for a MongoDB add-on.

**Comment by hhaidar** [comment]
We should close this if we're not going to support OpenShift @sibartlett

**Comment by sibartlett** [comment]
Yeah, I'd hate to say it... but for the time-being, we won't be adding official support for OpenShift. There's a lot of work involved in supporting each platform (not just adding it, but on-going support), and we don't currently have the resources to support a extra one.

We'll reconsider when we enough resources, or more demand.

**Comment by tvvocold** [comment]
@sibartlett i think there is one,but how to update it ? https://github.com/worldline/openshift-lets-chat
