### ISSUE TITLE
Build to Heroku is Failing

### ISSUE THREAD

**Issue by spenserhale** [sdelements/lets-chat#202]
Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.

**Comment by funkaoshi** [comment]
Was there anything of note in the logs?

**Comment by sibartlett** [comment]
Also, was this a deployment using the Heroku Deploy button or a custom deployment? Did you change any of the configuration?

I just tested the Heroku Deploy button, with default configuration and it worked fine.

**Comment by spenserhale** [comment]
Must has been a fluke or just inbetween commits or something, I deteled app and tried again and sure enough it worked, Thank you guys for quick response, on this app were would the default logs go?
