### ISSUE TITLE
Is there a live demo?

### ISSUE THREAD

**Issue by tvvocold** [sdelements/lets-chat#204]
I think it's time to build a live demo in a free cloud like Openshift for githubers  talk/enjoy this app...
In another words: 
Let's Chat!

**Comment by tejasmanohar** [comment]
Just use [this deploy to heroku link](https://heroku.com/deploy?template=https://github.com/sdelements/lets-chat)

**Comment by funkaoshi** [comment]
Agreed. We could host one ourselves, but I think we'd rather people just do the one-click Heroku deploy.
