### ISSUE TITLE
Bare domain advertised as MUC host.

### ISSUE THREAD

**Issue by Zash** [sdelements/lets-chat#214]
A `disco#info` query to the bare domain returns a feature that indicates that it is a MUC host.

     <iq id="2558cb68-1cd5-4323-988b-e93f4346f3ef" to="lets-chat.example" type="get">
       <query xmlns="http://jabber.org/protocol/disco#info"/>
     </iq>

    <iq type="result" id="2558cb68-1cd5-4323-988b-e93f4346f3ef" to="zash@lets-chat.example/cf71ffcceeda537d7a6654c77492e8a7" from="lets-chat.example">
      <query xmlns="http://jabber.org/protocol/disco#info">
        <identity category="conference" type="text" name="Let's chat"/>
         <feature var="vcard-temp"/>
        <feature var="http://jabber.org/protocol/muc"/>
       </query>
    </iq>

This can lead clients to believe that the items in a disco#items response are MUC rooms.

At least [Swift](https://swift.im/) seems to be confused by this and lists only the conference where you would normally see a room.

**Comment by sibartlett** [comment]
I've just pushed a fix for this. Thank you for pointing that out to us!

**Comment by sibartlett** [comment]
Oops, pushed a second commit that does fix this properly. I also downloaded and tested in Swift.
