### ISSUE TITLE
Increasing Project Scope

### ISSUE THREAD

**Issue by Squ34k3rZ** [sdelements/lets-chat#220]
Spitballing an idea here: Chat + Trello + Notes all in one app. 

To get a design discussion going, reply with "Yeah! And..." and add a suggestion. Then when we've gathered about 5 or 10 ideas, we can start talking about "why not" and deciding which ideas are the best to select.

"Yeah! And we could add an activity feed for people to post project/status updates!"

https://cloud.githubusercontent.com/assets/4743518/5886219/c7f7da36-a355-11e4-9519-99a7b524e0ca.png

**Comment by funkaoshi** [comment]
Do we want to do this? Seems like it'd be a completely different application. Might work better its own fork.

@hhaidar / @sibartlett ?
