### ISSUE TITLE
Long room names push right justified content off screen

### ISSUE THREAD

**Issue by tunnelsup** [sdelements/lets-chat#221]
Two different issues seem to be happening when a chat room is created with a long name. There is not a way to archive in screenshot 1 and there isn't a way to see the right side bar or archive in screenshot two. Screenshot two is using firefox 35.0.1.

![screen shot 2015-02-12 at 7 05 21 pm](https://cloud.githubusercontent.com/assets/3720012/6179759/ac4033c2-b2d9-11e4-9af6-2e6a845dadff.png)
![letschat](https://cloud.githubusercontent.com/assets/3720012/6179760/ac442108-b2d9-11e4-970a-a4f4359f5672.PNG)

Also when I try to make a chat room with japanese text it fails and I don't see a reason why it fails.

**Comment by sagivo** [comment]
similar issue with an empty string room.

**Comment by hhaidar** [comment]
Fixed in master.
