### ISSUE TITLE
S3 file uploads not working

### ISSUE THREAD

**Issue by TrevorHinesley** [sdelements/lets-chat#228]
When I try to upload a file, I get "Bad Request" and the pop-up says there was an error uploading. I've set the environment variables to enable files, to use "s3" as the provider, and set my amazon keys, bucket and region.

Any ideas?

**Comment by sibartlett** [comment]
We'll take a look into this - it's been a while since we tried the S3 code.

**Comment by TrevorHinesley** [comment]
Awesome thank you!

**Comment by joshwand** [comment]
+1 having the same problem. verified the s3 credentials work... the s3 code doesn't log anything besides "There was a problem with the server's S3 credentials." if the response code != 200. (/app/core/files/s3.js:38)

**Comment by sibartlett** [comment]
I've been debugging this, S3 is returning 403. Will take another look over the weekend!

**Comment by hhaidar** [comment]
Here's what knox is getting:

```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><AWSAccessKeyId>BLAH</AWSAccessKeyId><StringToSign>PUT
```

**Comment by hhaidar** [comment]
Okay, should be fixed now. @TrevorHinesley @joshwand can you guys try pulling latest?

Also, just a quick heads up: @sibartlett might create a separate plugin for this, so you might have to install an npm module in the near future.

**Comment by sibartlett** [comment]
I have extracted the S3 functionality into a separate plugin: https://github.com/sdelements/lets-chat-s3

**Comment by funkaoshi** [comment]
👍

**Comment by hhaidar** [comment]
:boat:

**Comment by geoffwhittington** [comment]
Is this still a problem?

**Comment by hhaidar** [comment]
@TrevorHinesley @joshwand this should be fixed in the plugin!
