### ISSUE TITLE
Room creation with invalid slug doesn't error out.

### ISSUE THREAD

**Issue by tmeusburger** [sdelements/lets-chat#229]
If you attempt to create a room with a dash in the slug it'll continue as if successful but fail to create the room.

As a result it's not really clear how to tell, why the room you attempted to create, doesn't exist.

To reproduce add a `-` into the slug name.

**Comment by geoffwhittington** [comment]
What do we think of auto-generating slugs in the UI? This doesn't fix the underlying issue, but may avoid a number of these cases

**Comment by sibartlett** [comment]
@geoffwhittington good idea!

**Comment by rjschu** [comment]
hey :) is this still an issue youd like fixing or are you going with auto-generating the slugs?

**Comment by hhaidar** [comment]
@rjschu we're doing both, are you planning on contributing a PR?

**Comment by rjschu** [comment]
i was going to take a look at it if no one else is yeah :)

**Comment by hhaidar** [comment]
@rjschu awesome :D

**Comment by rjschu** [comment]
is there any way in particular youd like the user to alerted that the creation was unsuccessful?

**Comment by hhaidar** [comment]
@rjschu we're using sweetAlert in a couple of places: http://tristanedwards.me/sweetalert

**Comment by rjschu** [comment]
@hhaidar brilliant i shall take a look at it and let ya know when its done :)

**Comment by hhaidar** [comment]
Thanks @rjschu, you rock!

**Comment by hhaidar** [comment]
There's an error now, but we need to make it more specific. This applies to all modals.
