### ISSUE TITLE
Validation of user fails on second login and beyond when using LDAP

### ISSUE THREAD

**Issue by parente** [sdelements/lets-chat#231]
Steps to reproduce:

1. Configure LDAP
2. Login with a valid LDAP username and password
3. Logout
4. Try to login with the same LDAP username and password again
5. Second login and beyond always fails with error:

```
{ [ValidationError: Validation failed]
  message: 'Validation failed',
  name: 'ValidationError',
  errors:
   { username:
      { [ValidatorError: Expected username to be unique]
        message: 'Expected username to be unique',
        name: 'ValidatorError',
        path: 'username',
        type: 'user defined',
        value: 'username' },
     email:
      { [ValidatorError: Expected email to be unique]
        message: 'Expected email to be unique',
        name: 'ValidatorError',
        path: 'email',
        type: 'user defined',
        value: 'username@somewhere.com' } } }
```

**Comment by sibartlett** [comment]
Hi @parente, thank you for sharing this problem with us.

Could you try updating the LDAP plugin to the lastest version: ```npm update lets-chat-ldap```

Before trying again, you'll need to remove the LDAP user already in the database - it might be easier to just drop the database.

**Comment by hhaidar** [comment]
If you just want to drop the user:

mongo
use MYDATABASE
db.users.remove({})

**Comment by parente** [comment]
@sibartlett `lets-chat-ldap@0.2.2` fixed the problem for me. Thanks!
