### ISSUE TITLE
Token menu option is hidden unless XMPP is enabled

### ISSUE THREAD

**Issue by GotenXiao** [sdelements/lets-chat#235]
The dropdown menu item for token management is wrapped inside the check for XMPP being enabled in templates/chat.html#52. Is this correct? I've not seen that requirement documented on the wiki, and the Docker setup defaults to XMPP disabled (thus meaning no tokens interface).

**Comment by sibartlett** [comment]
This was fixed here: b42d6de019bfc17f396b658a1c0dffa7ae14c2dc
