### ISSUE TITLE
Display Name default is password

### ISSUE THREAD

**Issue by elct9620** [sdelements/lets-chat#239]
Hello,

I setup Let's chat on Heroku, after I finished deploy and signup account.
I login and see my password show as display name, is three have any problem about this?

**Comment by hhaidar** [comment]
You might have entered your password in the display name field by default.

Do you mind trying to register again?

**Comment by elct9620** [comment]
Oops, I guess my password manager extension fill the password to display name field.

**Comment by hhaidar** [comment]
@elct9620 Yea it happens sometimes :D If you don't mind me asking, which password manager extension are you using? I'd like to see if there's something we can do to avoid stuff like this.

**Comment by elct9620** [comment]
I using LastPass to manage my password.
