### ISSUE TITLE
PostgreSQL Support

### ISSUE THREAD

**Issue by sammcj** [sdelements/lets-chat#241]
It would be great if Lets-Chat would work with more common databases such as PostgreSQL.

Many organisations / teams already have PostgreSQL for many of their applications and it's costly to support, backup and maintain multiple database products.

I'm no developer so I don't think I can contribute to help add PostgreSQL support but more I'm than happy to test anything anyone comes up with?

Great project by the way, I'm especially impressed with the XMPP support!

Need more reasons to add PostgreSQL as an option:

* http://blogs.enterprisedb.com/2014/09/24/postgres-outperforms-mongodb-and-ushers-in-new-developer-reality/
* http://www.sarahmei.com/blog/2013/11/11/why-you-should-never-use-mongodb/
* http://www.mongodb-is-web-scale.com/

**Comment by hhaidar** [comment]
Thanks, glad you like the project!

Currently there are no plans to switch away from Mongo simply because we're so dependent on Mongoose and Migroose. I don't really see an immediate benefit yet, that might change though :)

**Comment by sammcj** [comment]
Totally understand.

This makes lets-chat a no-go for organisations that want to use their existing database of choice which is one of the big advantages to using a standard ORM / abstraction layer (such as activerecord for Ruby etc...).

As the 'Mongo hype' has finally worn off and people are now cautious of MongoDB (and rightfully so) I think you'll find that quite a few people are hesitant to run an app that has a hard dependency on it.

Regardless of how easy it is to spin up Mongo in a Docker container and not really care about it, things are bound to go wrong at some point or require clustering to ensure a certain level of reliability.

Anyway, I love the project and the app so keep up the good work regardless :)

/endrant
