### ISSUE TITLE
History of room doesn't load after sign out from room and sign in to that room

### ISSUE THREAD

**Issue by drakmail** [sdelements/lets-chat#242]
Subj. See video for more detailed description: http://www.youtube.com/watch?v=2ChR1PzgnyM

**Comment by hhaidar** [comment]
@drakmail thanks for bringing this up, should be fixed if you pull the latest.

**Comment by drakmail** [comment]
Doesn't help :(

**Comment by hhaidar** [comment]
@drakmail did you restart the app after pulling? Assets are built on startup.

**Comment by drakmail** [comment]
Yes, I'm shut it down, did `git pull` and run again with `npm start`. But, maybe, this is cache issue... try to clear it now and check again.

**Comment by drakmail** [comment]
Yes, clearing cache solved issue

**Comment by hhaidar** [comment]
Ah nice! Thanks again for reporting this, I really appreciate it.
