### ISSUE TITLE
[REQ] Ability to bind to localhost

### ISSUE THREAD

**Issue by porkrinds** [sdelements/lets-chat#247]
I'd like to use nginx reverse proxy to this app so I can use proper modern SSL (PFS ciphers for example), as well as my sites already existing certificate, to proxy to let's-chat that listens only on localhost. I didn't see this option in the config or defaults

Or is this tool meant to only be used on a local network and not internet facing?

Thank You. The program is beautiful.

**Comment by hhaidar** [comment]
+1 Yea, this seems reasonable.

**Comment by hhaidar** [comment]
@porkrinds Can you try out #248, just add `host: 'localhost'` under `http:` in `settings.yml`

**Comment by porkrinds** [comment]
Hi, this appears to work for me. I can no longer access via public interface, however reverse proxying works. Now to get the nginx config setup properly :)

**Comment by hhaidar** [comment]
Good to hear, this will make it into master shortly. Just need to test heroku/docker/etc :)

**Comment by hhaidar** [comment]
Fixed via #248
