### ISSUE TITLE
Plugins should support environment variables

### ISSUE THREAD

**Issue by sibartlett** [sdelements/lets-chat#254]
Plugins should be configurable via environment variables.

**Comment by hhaidar** [comment]
:+1:

**Comment by maximilian-krauss** [comment]
:+1: 

Hey,
is it possible that we could bump this one up? I've built a plugin for [Microsoft Azure](https://github.com/maximilian-krauss/lets-chat-azure) and thats not working when using Heroku. (I guess the S3 upload is affected too?!)

If you guys are busy we could work out an idea/solution and I do the coding and submit a PR or something :smiley:

**Comment by sibartlett** [comment]
@maximilian-krauss if I have some time this weekend, I'll take a look at this - I've already done some work on this, and I just need to review it before I open a pull request.

**Comment by sibartlett** [comment]
This has been addressed on master. Plugins need to provide a "defaults" object, please see our plugins (ldap/kerberos/s3) for examples.

**Comment by maximilian-krauss** [comment]
@sibartlett that's great. Thank you very much :+1:
