### ISSUE TITLE
Installation on debian 7 failed

### ISSUE THREAD

**Issue by dbr1337** [sdelements/lets-chat#259]
Hello, i try to install the Let's Chat software for my company on debain 7 - 64 bit.
I installed the requirements, cloned the git repository and run npm install.
It fails at the installation, here is the installation history:

jabber@jabber:~/lets-chat$ npm install
...
> iconv@2.1.5 install /home/jabber/lets-chat/node_modules/node-xmpp-core/node_modules/ltx/node_modules/node-expat/node_modules/iconv
> node-gyp rebuild

make: Entering directory `/home/jabber/lets-chat/node_modules/node-xmpp-core/node_modules/ltx/node_modules/node-expat/node_modules/iconv/build'
  CC(target) Release/obj.target/libiconv/deps/libiconv/lib/iconv.o
  AR(target) Release/obj.target/iconv.a
  COPY Release/iconv.a
  CXX(target) Release/obj.target/iconv/src/binding.o
  SOLINK_MODULE(target) Release/obj.target/iconv.node
  SOLINK_MODULE(target) Release/obj.target/iconv.node: Finished
  COPY Release/iconv.node
make: Leaving directory `/home/jabber/lets-chat/node_modules/node-xmpp-core/node_modules/ltx/node_modules/node-expat/node_modules/iconv/build'

> node-expat@2.3.6 install /home/jabber/lets-chat/node_modules/node-xmpp-core/node_modules/ltx/node_modules/node-expat
> node-gyp rebuild

make: Entering directory `/home/jabber/lets-chat/node_modules/node-xmpp-core/node_modules/ltx/node_modules/node-expat/build'
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
../deps/libexpat/lib/xmltok.c:471:1: warning: missing initializer [-Wmissing-field-initializers]
../deps/libexpat/lib/xmltok.c:471:1: warning: (near initialization for ‘latin1_encoding_ns.isName2’) [-Wmissing-field-initializers]
../deps/libexpat/lib/xmltok.c:484:1: warning: missing initializer [-Wmissing-field-initializers]
../deps/libexpat/lib/xmltok.c:484:1: warning: (near initialization for ‘latin1_encoding.isName2’) [-Wmissing-field-initializers]
../deps/libexpat/lib/xmltok.c:504:1: warning: missing initializer [-Wmissing-field-initializers]
../deps/libexpat/lib/xmltok.c:504:1: warning: (near initialization for ‘ascii_encoding_ns.isName2’) [-Wmissing-field-initializers]
../deps/libexpat/lib/xmltok.c:517:1: warning: missing initializer [-Wmissing-field-initializers]
../deps/libexpat/lib/xmltok.c:517:1: warning: (near initialization for ‘ascii_encoding.isName2’) [-Wmissing-field-initializers]
../deps/libexpat/lib/xmltok.c:730:1: warning: missing initializer [-Wmissing-field-initializers]
../deps/libexpat/lib/xmltok.c:730:1: warning: (near initialization for ‘little2_encoding_ns.isName2’) [-Wmissing-field-initializers]
../deps/libexpat/lib/xmltok.c:749:1: warning: missing initializer [-Wmissing-field-initializers]
../deps/libexpat/lib/xmltok.c:749:1: warning: (near initialization for ‘little2_encoding.isName2’) [-Wmissing-field-initializers]
../deps/libexpat/lib/xmltok.c:762:1: warning: missing initializer [-Wmissing-field-initializers]
../deps/libexpat/lib/xmltok.c:762:1: warning: (near initialization for ‘internal_little2_encoding_ns.isName2’) [-Wmissing-field-initializers]
../deps/libexpat/lib/xmltok.c:775:1: warning: missing initializer [-Wmissing-field-initializers]
../deps/libexpat/lib/xmltok.c:775:1: warning: (near initialization for ‘internal_little2_encoding.isName2’) [-Wmissing-field-initializers]
../deps/libexpat/lib/xmltok.c:871:1: warning: missing initializer [-Wmissing-field-initializers]
../deps/libexpat/lib/xmltok.c:871:1: warning: (near initialization for ‘big2_encoding_ns.isName2’) [-Wmissing-field-initializers]
../deps/libexpat/lib/xmltok.c:890:1: warning: missing initializer [-Wmissing-field-initializers]
../deps/libexpat/lib/xmltok.c:890:1: warning: (near initialization for ‘big2_encoding.isName2’) [-Wmissing-field-initializers]
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
  AR(target) Release/obj.target/deps/libexpat/libexpat.a
  COPY Release/libexpat.a
  CXX(target) Release/obj.target/node_expat/node-expat.o
../node-expat.cc: In static member function ‘static v8::Handle<v8::Value> Parser::New(const v8::Arguments&)’:
../node-expat.cc:42:9: warning: ‘void* NanRawString(v8::Handle<v8::Value>, Nan::Encoding, size_t*, void*, size_t, int)’ is deprecated (declared at ../node_modules/nan/nan.h:2072) [-Wdeprecated-declarations]
../node-expat.cc:42:64: warning: ‘void* NanRawString(v8::Handle<v8::Value>, Nan::Encoding, size_t*, void*, size_t, int)’ is deprecated (declared at ../node_modules/nan/nan.h:2072) [-Wdeprecated-declarations]
../node-expat.cc: In static member function ‘static v8::Handle<v8::Value> Parser::SetEncoding(const v8::Arguments&)’:
../node-expat.cc:150:9: warning: ‘void* NanRawString(v8::Handle<v8::Value>, Nan::Encoding, size_t*, void*, size_t, int)’ is deprecated (declared at ../node_modules/nan/nan.h:2072) [-Wdeprecated-declarations]
../node-expat.cc:150:64: warning: ‘void* NanRawString(v8::Handle<v8::Value>, Nan::Encoding, size_t*, void*, size_t, int)’ is deprecated (declared at ../node_modules/nan/nan.h:2072) [-Wdeprecated-declarations]
../node-expat.cc: In static member function ‘static v8::Handle<v8::Value> Parser::Reset(const v8::Arguments&)’:
../node-expat.cc:223:9: warning: ‘void* NanRawString(v8::Handle<v8::Value>, Nan::Encoding, size_t*, void*, size_t, int)’ is deprecated (declared at ../node_modules/nan/nan.h:2072) [-Wdeprecated-declarations]
../node-expat.cc:223:64: warning: ‘void* NanRawString(v8::Handle<v8::Value>, Nan::Encoding, size_t*, void*, size_t, int)’ is deprecated (declared at ../node_modules/nan/nan.h:2072) [-Wdeprecated-declarations]
  SOLINK_MODULE(target) Release/obj.target/node_expat.node
  SOLINK_MODULE(target) Release/obj.target/node_expat.node: Finished
  COPY Release/node_expat.node
make: Leaving directory `/home/jabber/lets-chat/node_modules/node-xmpp-core/node_modules/ltx/node_modules/node-expat/build'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/jabber/lets-chat/npm-debug.log
npm ERR! not ok code 0

How can i fix that? Greetings

**Comment by hhaidar** [comment]
Try installing libexpat: https://packages.debian.org/sid/libexpat-dev

**Comment by dbr1337** [comment]
It works now, thank you!
But i have a new problem, i enabled the XMPP Application. It works to connect, but the web interface is not more reachable and this errors show up: http://img-host.de/bild.php/53964,bildschirmfoto20150216um154331XLFD4.png

**Comment by Twilek-de** [comment]
Interesting, I installed it on a debian 64 bit. For me the web interface works but the XMPP does not. The port is open but the Login always fails.

**Comment by hhaidar** [comment]
@dbr1337 can you paste your settings for http and xmpp?

@Twilek-de are you using the username to login? What happens when you telnet to that port and type something?

**Comment by dbr1337** [comment]
http:
  enable: true
  host: 'localhost'
  port: 5000

xmpp:
  enable: true
  roomCreation: false
  debug:
    handled: false
    unhandled: true
  port: 5222
  host: 192.168.211.161
  tls:
    enable: true
    key: ./mycert.key
    cert: ./mycert.crt

**Comment by hhaidar** [comment]
@dbr1337 what address are you using to access the web interface? The host setting under http is currently `localhost`, which will only be accessible there. Try changing it to `192.168.211.161`

**Comment by dbr1337** [comment]
I had change it before to 192.168.211.161, now it was localhost. But i changed it and i worked. My next question: i need to connect the xmpp server with active directory and implement the users from there. how can i do this?

**Comment by hhaidar** [comment]
We have modules for LDAP and Kerberos auth:

https://github.com/sdelements/lets-chat-ldap
https://github.com/sdelements/lets-chat-kerberos

Please be sure to disable local registration too! https://github.com/sdelements/lets-chat/wiki/Authentication#local-authentication

**Comment by hhaidar** [comment]
Closing this. @Twilek-de do you mind opening another issue if you're still having problems getting XMPP to run? CC @sibartlett
