### ISSUE TITLE
Unable to connect to XMPP on Debian 64 bit installation

### ISSUE THREAD

**Issue by Twilek-de** [sdelements/lets-chat#260]
The XMPP Port is open but I cannot connect

lsof -i -P gets 
node      29414        root   22u  IPv6 2966443      0t0  TCP *:5222 (LISTEN)

telnet localhost 5222
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused

Let´s chat shows no errors

My settings look like this

env: development # development / production

http:
  enable: false
  port: 5000

https:
  enable: true
  port: 5001
  key: xxx
  cert: xxx

files:
  enable: true
  provider: local
  local:
    dir: uploads

xmpp:
  enable: true
  debug:
    handled: true
    unhandled: true
  port: 5222
  host: xxx.de
  tls:
    enable: true
    key: xxx
    cert: xxx

database:
  uri: mongodb://localhost/letschat

secrets:
  cookie: xxx

  local:
    dir: uploads

  s3:
    accessKeyId:
    secretAccessKey:
    bucket:
    region:

auth:
  providers: [local]

  local:
    enableRegistration: true
    salt: xxx# Required when upgrading from version < 0.3

**Comment by Twilek-de** [comment]
I am just realizing that the port is opened only for IPv6. It is not opened for IPv4 by lets chat or any other program (just checked that)

**Comment by sibartlett** [comment]
This is what I get on Mac OS X, looks similar to what you get:

```
node      84996 sibartlett   29u  IPv6 0xa2a7dbb01734667d      0t0  TCP *:5222 (LISTEN)
```

Telnet worked for me though.

**Comment by Twilek-de** [comment]
The SSL Port looks like this
node      29414        root   10u  IPv4 2966442      0t0  TCP *:5001 (LISTEN)

**Comment by sibartlett** [comment]
My local instance reports HTTP/HTTPS as IPv4, and XMPP as IPv6.

**Comment by Twilek-de** [comment]
So does mine, but for me XMPP really only works with IPv6. Connecting to 5001 only works with IPv4.

**Comment by sibartlett** [comment]
I realize my comments haven't been very helpful so far.

@geoffwhittington @TuxOtaku do you guys happen to have a debian install you can test the XMPP functionality on?

**Comment by TuxOtaku** [comment]
@sibartlett I can set one up in the lab for you tomorrow if you like. :smile:

**Comment by geoffwhittington** [comment]
I've done all my testing on Ubuntu, I just assumed Debian was identical but I'm wrong often. I'll see what i can do!

**Comment by Twilek-de** [comment]
I have setup a barebone fresh Debian 64 VM and just installed the necessary stuff (you are missing a probably too obvious prerequisite in the installation instructions, namely "git" itself :-) ). With just http and XMPP enabled lets chat will open Port 5000 with v4 only and Port 5222 v6 only.

**Comment by Twilek-de** [comment]
I played a little more with my test installation. Althought port 5222 is only listed as IPv6 you can connect with IPv4. A telnet localhost 5222 gives a trying ::1 and then a Connected to localhost, so it defaults to IPv6. A telnet 127.0.0.1 5222 will still connect. This is different from the behaviour of lets chat on my server althought the listing of the ports with lsof is the same.

**Comment by geoffwhittington** [comment]
It looks like you can connect to XMPP on 5222, is that right?

**Comment by Twilek-de** [comment]
Yes on my own server with IPv6 on the test installation IPv4 and IPv6

**Comment by geoffwhittington** [comment]
Ok great - good to hear!

**Comment by jscmenezes** [comment]
I am having the same issue.. XMPP only work with ipv6.. Posted on lets-chat google group..

**Comment by shakaw** [comment]
Proposed patch: file xmpp/node/node_modules/lets-chat/app/xmpp/index.js" replace this segment:

function xmppStart(core) {
    var options = {
        port: settings.xmpp.port,
        domain: settings.xmpp.domain
    };
with this:

function xmppStart(core) {
    var options = {
        port: settings.xmpp.port,
        host: settings.xmpp.host,
        domain: settings.xmpp.domain
    };
And add xmpp.host entry to "xmpp/node/node_modules/lets-chat/settings.yml" with a default value of "0.0.0.0".
