### ISSUE TITLE
hubot scripts on LCB

### ISSUE THREAD

**Issue by oinirio** [sdelements/lets-chat#265]
I've been testing with the hubot adapter but can execute any of my script or any other third party inside even though they run inside hubot shell.

**Comment by hhaidar** [comment]
Do you see the hubot in the user list?

**Comment by hhaidar** [comment]
Also if you're using 0.3+, please make sure lets-chat-hubot is up to date and you're supplying it with a user auth token.

**Comment by oinirio** [comment]
the problem was an outdated hubot-lets-chat git pull solve this

**Comment by hhaidar** [comment]
![yes](http://media3.giphy.com/media/62PP2yEIAZF6g/giphy.gif)
