### ISSUE TITLE
Error starting

### ISSUE THREAD

**Issue by vdite** [sdelements/lets-chat#267]
I do get "sh: 1: migroose: not found" on "npm start" on Ubuntu 14.04.1 LTS

**Comment by hhaidar** [comment]
What version of node and npm do you have?

Also is this a fresh install?

**Comment by hhaidar** [comment]
You might need to run `npm install`

**Comment by vdite** [comment]
both i had installed via apt-get yesterday
node -v v0.6.12
npm -v 1.1.4

**Comment by vdite** [comment]
oh, I see now the fail. I do need Node.js (0.10.x)

**Comment by hhaidar** [comment]
ah cool, let me know what happens.
