### ISSUE TITLE
Lock registration down to certain domains

### ISSUE THREAD

**Issue by JohnTheodore** [sdelements/lets-chat#268]
Slack has a feature which is great, where I can only register for my slack instance if I have an email that uses @mycompany.com. and 'mycompany.com' is a configurable field. So only our employees can sign up. It would be great if Let's Chat did this as well.

**Comment by hhaidar** [comment]
+1 But we'll need email confirmation, which is probably where we're heading.

**Comment by JohnTheodore** [comment]
Just realized this is a duplicate of 218, I'll close.

https://github.com/sdelements/lets-chat/issues/218

**Comment by hhaidar** [comment]
Dupe of #218

**Comment by hhaidar** [comment]
@JohnTheodore you're the man!
