### ISSUE TITLE
Error while installing 

### ISSUE THREAD

**Issue by ubilli** [sdelements/lets-chat#272]
when i did the npm install it did not work when i goto localhost:5000,
This is the log of the command.

jobinpal@Jobinpal ~/lets-chat> sudo npm install
[sudo] password for jobinpal: 
npm http GET https://registry.npmjs.org/node-xmpp-core
npm http GET https://registry.npmjs.org/socket.io-client
npm http 304 https://registry.npmjs.org/socket.io-client
npm http 304 https://registry.npmjs.org/node-xmpp-core
npm http GET https://registry.npmjs.org/node-stringprep
npm http GET https://github.com/dodo/reconnect-core/tarball/merged
npm http GET https://registry.npmjs.org/tls-connect
npm http GET https://registry.npmjs.org/ltx
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/debug/0.7.4
npm http GET https://registry.npmjs.org/engine.io-client/1.5.1
npm http GET https://registry.npmjs.org/component-bind/1.0.0
npm http GET https://registry.npmjs.org/component-emitter/1.1.2
npm http GET https://registry.npmjs.org/object-component/0.0.3
npm http GET https://registry.npmjs.org/socket.io-parser/2.2.3
npm http GET https://registry.npmjs.org/has-binary/0.1.6
npm http GET https://registry.npmjs.org/indexof/0.0.1
npm http GET https://registry.npmjs.org/parseuri/0.0.2
npm http GET https://registry.npmjs.org/to-array/0.1.3
npm http GET https://registry.npmjs.org/backo2/1.0.2
npm http 304 https://registry.npmjs.org/node-stringprep
npm http 304 https://registry.npmjs.org/tls-connect
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/ltx
npm http 304 https://registry.npmjs.org/debug/0.7.4
npm http 304 https://registry.npmjs.org/object-component/0.0.3
npm http 304 https://registry.npmjs.org/engine.io-client/1.5.1
npm http 304 https://registry.npmjs.org/component-bind/1.0.0
npm http 304 https://registry.npmjs.org/socket.io-parser/2.2.3
npm http 304 https://registry.npmjs.org/component-emitter/1.1.2
npm http 304 https://registry.npmjs.org/indexof/0.0.1
npm http 304 https://registry.npmjs.org/parseuri/0.0.2
npm http 304 https://registry.npmjs.org/has-binary/0.1.6
npm http 304 https://registry.npmjs.org/backo2/1.0.2
npm http 304 https://registry.npmjs.org/to-array/0.1.3
npm http GET https://registry.npmjs.org/better-assert
npm http GET https://registry.npmjs.org/json3/3.2.6
npm http GET https://registry.npmjs.org/isarray/0.0.1
npm http GET https://registry.npmjs.org/benchmark/1.0.0
npm http GET https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
npm http GET https://registry.npmjs.org/has-cors/1.0.3
npm http GET https://registry.npmjs.org/ws/0.4.31
npm http GET https://registry.npmjs.org/engine.io-parser/1.2.1
npm http GET https://registry.npmjs.org/debug/1.0.4
npm http GET https://registry.npmjs.org/parseuri/0.0.4
npm http GET https://registry.npmjs.org/parsejson/0.0.1
npm http GET https://registry.npmjs.org/parseqs/0.0.2
npm http GET https://registry.npmjs.org/component-inherit/0.0.3
npm http 304 https://registry.npmjs.org/better-assert
npm http GET https://registry.npmjs.org/callsite/1.0.0
npm http 304 https://registry.npmjs.org/isarray/0.0.1
npm http 304 https://registry.npmjs.org/json3/3.2.6
npm http 304 https://registry.npmjs.org/ws/0.4.31
npm http 304 https://registry.npmjs.org/has-cors/1.0.3
npm http 304 https://registry.npmjs.org/engine.io-parser/1.2.1
npm http 304 https://registry.npmjs.org/debug/1.0.4
npm http 304 https://registry.npmjs.org/parsejson/0.0.1
npm http 304 https://registry.npmjs.org/parseuri/0.0.4
npm http 304 https://registry.npmjs.org/parseqs/0.0.2
npm http 304 https://registry.npmjs.org/callsite/1.0.0
npm http 304 https://registry.npmjs.org/benchmark/1.0.0
npm http 304 https://registry.npmjs.org/component-inherit/0.0.3
npm http 200 https://github.com/dodo/reconnect-core/tarball/merged
npm http GET https://registry.npmjs.org/backoff
npm http GET https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/sax
npm http GET https://registry.npmjs.org/node-expat
npm http 304 https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/sax
npm http 304 https://registry.npmjs.org/backoff
npm http 304 https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/ms/0.6.2
npm http 304 https://registry.npmjs.org/node-expat
npm http GET https://registry.npmjs.org/node-expat/-/node-expat-2.3.6.tgz
npm http 304 https://registry.npmjs.org/ms/0.6.2

> node-stringprep@0.5.4 install /home/jobinpal/lets-chat/node_modules/node-xmpp-core/node_modules/node-stringprep
> node-gyp rebuild

npm http 200 https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
npm http 200 https://registry.npmjs.org/node-expat/-/node-expat-2.3.6.tgz
/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-24-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/jobinpal/lets-chat/node_modules/node-xmpp-core/node_modules/node-stringprep
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! weird error 1
npm http GET https://registry.npmjs.org/better-assert
npm http GET https://github.com/component/global/archive/v2.0.1.tar.gz
npm http GET https://registry.npmjs.org/after/0.8.1
npm http GET https://registry.npmjs.org/arraybuffer.slice/0.0.6
npm http GET https://registry.npmjs.org/blob/0.0.2
npm http GET https://registry.npmjs.org/base64-arraybuffer/0.1.2
npm http GET https://registry.npmjs.org/has-binary/0.1.5
npm http GET https://registry.npmjs.org/utf8/2.0.0
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/options
npm http GET https://registry.npmjs.org/tinycolor
npm http 304 https://registry.npmjs.org/better-assert
npm http GET https://registry.npmjs.org/callsite/1.0.0
npm http 304 https://registry.npmjs.org/after/0.8.1
npm http 304 https://registry.npmjs.org/blob/0.0.2
npm http 304 https://registry.npmjs.org/arraybuffer.slice/0.0.6
npm http 304 https://registry.npmjs.org/base64-arraybuffer/0.1.2
npm http 304 https://registry.npmjs.org/has-binary/0.1.5
npm http 304 https://registry.npmjs.org/utf8/2.0.0
npm http 304 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/options
npm http 304 https://registry.npmjs.org/tinycolor
npm http GET https://registry.npmjs.org/commander/-/commander-0.6.1.tgz
npm http 304 https://registry.npmjs.org/callsite/1.0.0
npm http GET https://registry.npmjs.org/isarray/0.0.1
npm http 200 https://registry.npmjs.org/commander/-/commander-0.6.1.tgz
npm http 304 https://registry.npmjs.org/isarray/0.0.1

> ws@0.4.31 install /home/jobinpal/lets-chat/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

npm http 200 https://github.com/component/global/archive/v2.0.1.tar.gz
npm ERR! not ok code 0

**Comment by hhaidar** [comment]
What version of node / npm do you have?

```
npm -v && node -v
```

And please don't run `npm install` with sudo :(

**Comment by ubilli** [comment]
@hhaidar  1.3.10

**Comment by hhaidar** [comment]
@ubilli how about 'node -v'?

**Comment by ubilli** [comment]
The program 'node' can be found in the following packages:
 * node
 * nodejs-legacy
Try: sudo apt-get install <selected package>

**Comment by hhaidar** [comment]
Try doing `sudo apt-get install nodejs-legacy` and then `node -v`

**Comment by hhaidar** [comment]
[Here's more info on this](http://stackoverflow.com/questions/21168141/can-not-install-packages-using-node-package-manager-in-ubuntu)

**Comment by ubilli** [comment]
v0.10.25 that is it response.

**Comment by hhaidar** [comment]
If `node -v` worked, can you try:

```
rm -rf node_modules
npm install
```

You might have to run `rm -rf node_modules` with sudo.

**Comment by ubilli** [comment]
the npm install has finish now but when i goto localhost:5000 it does not work.

**Comment by sibartlett** [comment]
The app starts fine when you run ```npm start```?

**Comment by ubilli** [comment]
a new error. when i did npm start

jobinpal@Jobinpal ~/lets-chat> npm start

> lets-chat@0.3.3 prestart /home/jobinpal/lets-chat
> migroose


/home/jobinpal/lets-chat/migroose.js:10
            if (err) { throw err; }
                             ^
Error: failed to connect to [localhost:27017]
    at null.<anonymous> (/home/jobinpal/lets-chat/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:555:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (/home/jobinpal/lets-chat/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (/home/jobinpal/lets-chat/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0
jobinpal@Jobinpal ~/lets-chat> npm start

> lets-chat@0.3.3 prestart /home/jobinpal/lets-chat
> migroose


/home/jobinpal/lets-chat/migroose.js:10
            if (err) { throw err; }
                             ^
Error: failed to connect to [localhost:27017]
    at null.<anonymous> (/home/jobinpal/lets-chat/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:555:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (/home/jobinpal/lets-chat/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (/home/jobinpal/lets-chat/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0

**Comment by hhaidar** [comment]
You need MongoDB running :)

**Comment by ubilli** [comment]
how do i do that please...

**Comment by hhaidar** [comment]
[Here you go](http://www.mongodbspain.com/en/2014/08/30/install-mongodb-on-ubuntu-14-04/)

**Comment by ubilli** [comment]
Please I will continue tommorow.

**Comment by ubilli** [comment]
Thanks for your support @hhaidar but i went to the link you gave me the second step
2. Generate a file with the MongoDB repository url

$ echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen

OUTPUT
deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen
No command 'deb' found, did you mean:
 Command 'xdeb' from package 'xdeb' (universe)
 Command 'debc' from package 'devscripts' (main)
 Command 'deb3' from package 'quilt' (main)
 Command 'debi' from package 'devscripts' (main)
 Command 'derb' from package 'icu-devtools' (main)
 Command 'dwb' from package 'dwb' (universe)
 Command 'dab' from package 'bsdgames' (universe)
deb: command not found

**Comment by hhaidar** [comment]
What OS are you running and which version?

Please have a look at mongodb's install docs: http://docs.mongodb.org/manual/installation/

**Comment by funkaoshi** [comment]
[You might want to look at running lets chat using a Docker container.](https://github.com/sdelements/lets-chat/wiki/Docker)

**Comment by ubilli** [comment]
thanks  gues it is working but how do i do connect with other users and upload files.

**Comment by funkaoshi** [comment]
You can tell users to make accounts on your instance. You can access the file menu from the sidebar.

**Comment by ubilli** [comment]
Hi,

I&#39;d like to add you to my professional network on LinkedIn.

- Udeme

Accept: https://www.linkedin.com/blink?simpleRedirect=0SdjwVdzcVd3cPcPwQdj0QejARfkh9rCZFt65QqnpKqipns4lKs2R6hPRVpkJApn9xq7cCt7dBtmtvpnhFtCVFfmJB9C5QoORBt6BSrCAJt7dBtmsJr6RBfmtKqmJzon9Q9ClQqnpKimtBkClOs3Rx9CQRbnsOu6ZIqjxFbmtPr7xxcjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054840039272448_500&markAsRead=


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=rjkJtP9UrSNFe6AJpTdIu64NfmhFpipjcQhIpTwUe3h8rk9Os7hipB56szkOskZzr49hlltAqkhAs3kOlBF4hBhaiPB1jTlTj6pqrAVOsPhUhBlMold8rmJ3cj9Lcn1WoAZHpRcJnSdhpDhEgRESckVOs51LrTxDokQPm4dWijt5pSwVjARRtllktBlmik5UhR8Utk5UoQtfhTEMpBlaukpqhTEUl6xej2R1kDBvkkVQsmR7hCsQlCxyj6kPrklMhnp6s39ds3xVlk51gmsUcnhmjQ4VilZGhB51fmhFrSMCt7dBtmtvpnhFtCVFfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9CQRbnsOu6ZIqjxFbmtPr7xxcjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5994054840039272448_500&amp;markAsRead= Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ct7dBtmtvpnhFtCVFfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9CQRbnsOu6ZIqjxFbmtPr7xxcjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054840039272448_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by ubilli** [comment]
Udeme Samuel would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=dzkUejoPejgPcPcUd3kMd3AVdjR4imVLqnhxt6BSrCAClT15rD0JhAsZumlbp6lOomxP9DhUpnhvt71BoSdxfndQ9CZOpmwZrioPfmBI9z4MnT9Bp6VFrmlOnThPpnlDnThPsCBCfmJB9ClQqnpKimtBkClOs3Rx9z8RbmFytCRBsPxFbmtPr7xxcjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054840039272448_500&markAsRead=

View Udeme Samuel&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=0VdjgRc38Vcj4Zh4BOpm9JpmQCt7xBt5ZBr6BCrT9MfndQ9CZOpmwZrioQfmBI9z4MnT9Bp6VFrmlOnThPpnlDnThPsCBCfmJB9DpMrzRQ9z8RbmFytCRBsPxFbmtPr7xxcjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054840039272448_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=rmZzhj8BoDlEt6BDhj8BumNMpn8Md2kPem9ze3sPc6lzejoNoj8Vd69xpChCc34Nc30Mc30Mc6pzczBCp3wTdmoPoP0McPoQoClAe68Np3gMc34PpCkQcPgOcjkPdm5xpjcVe68Ppm8Nc312cylVr71BszRIqm5JpioMdz0MczRAqioSdjwVdzcVd3cPcPwQdj0QejARfmhFpOoNc5ZOpmhKqmRBsBZQsSlRpRZQsT9FpzRHpipQu6lQnS9RsSVRbjkJoDlPrDkJcj1vsClArCBJpn9vt7dBtmtvt7dOqmoJr6RBfmtKqmJzon9Q9CZLpPRQ9z8RbmFytCRBsPxFbmtPr7xxcjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054840039272448_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=38RbmFytCRBsPxFbmtPr7xxcjRAqmkCiTgTuCFnpBh2s5Z6d6NarStzc6lKgn1FekV2j4tTlRBVs4FTsDhldChgsz5ngkATi4hfcj18dksTp65ei65hojlvdkF6oT9Wkn1iqnFBsyR9iAhpk6lFkkpeiSwUcDdPnSkUhQJMj6NRpCxHnSFGdkNnpS8Nkldmpk9fikRJdkVRokQSsQ9UsCZEt4Fdp7Fvc6RzikFxu5BCr3hNoAd7hQwPh7B5jCBfdyRNnP0OqyRCuBl1gk5DsncRdl1hi4lvhklhgjRAqmZI9z4MnT9Bp6VFrmlOnThPpnlDnThPsCBCfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9z8RbmFytCRBsPxFbmtPr7xxcjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5994054840039272448_500&amp;markAsRead=This email was intended for sdelements/lets-chat. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=3wUdPgZp4BBr6dFt79x9z4MnT9Bp6VFrmlOnThPpnlDnThPsCBCfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9z8RbmFytCRBsPxFbmtPr7xxcjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054840039272448_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by ubilli** [comment]
Udeme Samuel would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=0SdjwVdzcVd3cPcPwQdj0QejARfkh9rCZFt65QqnpKqipns4lKs2R6hPRVpkJApn9xq7cCt7xBt5ZQs6lzoS4ZsTgCrT9Bq3RJ9zcZqmMCcj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9ClQqnpKimtBkClOs3Rx9zoQbjlHcnpBczBFbmtPr7xxcjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054840039272448_500&markAsRead=

View Udeme Samuel&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=3ARd3kMczANcjR4in9BoCRBripQu6lQnSlIqmpLsD0ZsTgCrT9Bq3RJ9zgZqmMCcj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9DpMrzRQ9zoQbjlHcnpBczBFbmtPr7xxcjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054840039272448_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=6RLoQkO9m9Rq7hFpQkO9nBIs6lOc3gBcPByoPwTcP1BoPAScm4OejhyompApz0Ncj0Mc30Mc31CoP8VpCgUdPlCcScMc3cSd69Bp3xycmgQc30NcSpBd3cQcz4RcPlxomkPejxycSlycj0Mgz8BumNMpn8Zr6BxrmkCc3oMc38Zp6ACdzkUejoPejgPcPcUd3kMd3AVdjRAqmsCcj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9DhUpnhvoDlPrDkJdyRytndKtiQNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncJr6RBfmtKqmJzon9Q9CZLpPRQ9zoQbjlHcnpBczBFbmtPr7xxcjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054840039272448_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=dzgJdmINtCkOemAJpTdIu64NfmhFpiplqnF4jAVntmFDgk4JhPlqk6BbkBlmj6JId39EolBylDxEh51Fcjhchmdpp5BWcAB4iRdkdCgOq4xzomlom4NNiCIRoTxhsPh6r5dSp4lvhP9Eq7dhkQ9Le4VUrT9MelZInTAMhQVfqkhDbk9CgQUNlQxCtTpDlAZ6qmNLoj5SsCcUs7hPr59Vhn0MhDFFmmJzp78RgQ4UqDoMtBZIcjcVhRhRbmFohClVqkNde51JgQkMlk51gl5boll9lRpblDF3hl51fmhFrSMCcj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9zoQbjlHcnpBczBFbmtPr7xxcjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5994054840039272448_500&amp;markAsRead=This email was intended for sdelements/lets-chat. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ccj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9zoQbjlHcnpBczBFbmtPr7xxcjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054840039272448_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA
