### ISSUE TITLE
Error encountered while installing

### ISSUE THREAD

**Issue by micsanmo** [sdelements/lets-chat#283]
@hhaidar @azend I encountered this error while installing using npm install, assistance needed ASAP:

$ npm install
npm ERR! install Couldn't read dependencies
npm ERR! package.json ENOENT, open 'C:\Users\Meliorembsl\package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Users\Meliorembsl
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path C:\Users\Meliorembsl\package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\Meliorembsl\npm-debug.log
npm ERR! not ok code 0

**Comment by funkaoshi** [comment]
Are you running npm install in the correct directory?

**Comment by hhaidar** [comment]
```
cd lets-chat
npm install
```

**Comment by funkaoshi** [comment]
[You might want to look into running this application using Docker / Fig](https://github.com/sdelements/lets-chat/wiki/Docker)

**Comment by micsanmo** [comment]
this is the error i encountered again after cs lets-chat @hhaidar

**Comment by hhaidar** [comment]
@micsanmo you need to run `npm install` the directory that you downloaded Let's Chat. If don't know where the files are I can't really help you :(

Also, I don't recommend installing this on Windows without Docker or something.
