### ISSUE TITLE
Vagrant doesn´t work at the moment

### ISSUE THREAD

**Issue by Twilek-de** [sdelements/lets-chat#294]
Just cloned just chat and did vagrant up. After lots of installing it went down in flames with this

==> lcb: > node-expat@2.3.6 install /home/vagrant/lets-chat/node_modules/node-xmpp-core/node_modules/ltx/node_modules/node-expat
==> lcb: > node-gyp rebuild
==> lcb: make: Entering directory `/home/vagrant/lets-chat/node_modules/node-xmpp-core/node_modules/ltx/node_modules/node-expat/build'
==> lcb:   CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
==> lcb:   CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
==> lcb: ../deps/libexpat/lib/xmltok.c:471:1: warning: missing initializer [-Wmissing-field-initializers]
==> lcb: ../deps/libexpat/lib/xmltok.c:471:1: warning: (near initialization for 'latin1_encoding_ns.isName2') [-Wmissing-field-initializers]
==> lcb: ../deps/libexpat/lib/xmltok.c:484:1: warning: missing initializer [-Wmissing-field-initializers]
==> lcb: ../deps/libexpat/lib/xmltok.c:484:1: warning: (near initialization for 'latin1_encoding.isName2') [-Wmissing-field-initializers]
==> lcb: ../deps/libexpat/lib/xmltok.c:504:1: warning: missing initializer [-Wmissing-field-initializers]
==> lcb: ../deps/libexpat/lib/xmltok.c:504:1: warning: (near initialization for 'ascii_encoding_ns.isName2') [-Wmissing-field-initializers]
==> lcb: ../deps/libexpat/lib/xmltok.c:517:1: warning: missing initializer [-Wmissing-field-initializers]
==> lcb:
==> lcb: ../deps/libexpat/lib/xmltok.c:517:1: warning: (near initialization for 'ascii_encoding.isName2') [-Wmissing-field-initializers]
==> lcb: ../deps/libexpat/lib/xmltok.c:730:1: warning: missing initializer [-Wmissing-field-initializers]
==> lcb: ../deps/libexpat/lib/xmltok.c:730:1: warning: (near initialization for 'little2_encoding_ns.isName2') [-Wmissing-field-initializers]
==> lcb: ../deps/libexpat/lib/xmltok.c:749:1: warning: missing initializer [-Wmissing-field-initializers]
==> lcb: ../deps/libexpat/lib/xmltok.c:749:1: warning: (near initialization for 'little2_encoding.isName2') [-Wmissing-field-initializers]
==> lcb: ../deps/libexpat/lib/xmltok.c:762:1: warning: missing initializer [-Wmissing-field-initializers]
==> lcb: ../deps/libexpat/lib/xmltok.c:762:1: warning: (near initialization for 'internal_little2_encoding_ns.isName2') [-Wmissing-field-initializers]
==> lcb: ../deps/libexpat/lib/xmltok.c:775:1: warning: missing initializer [-Wmissing-field-initializers]
==> lcb: ../deps/libexpat/lib/xmltok.c:775:1: warning: (near initialization for 'internal_little2_encoding.isName2') [-Wmissing-field-initializers]
==> lcb: ../deps/libexpat/lib/xmltok.c:871:1: warning: missing initializer [-Wmissing-field-initializers]
==> lcb:
==> lcb: ../deps/libexpat/lib/xmltok.c:871:1: warning: (near initialization for 'big2_encoding_ns.isName2') [-Wmissing-field-initializers]
==> lcb: ../deps/libexpat/lib/xmltok.c:890:1: warning: missing initializer [-Wmissing-field-initializers]
==> lcb: ../deps/libexpat/lib/xmltok.c:890:1: warning: (near initialization for 'big2_encoding.isName2') [-Wmissing-field-initializers]
==> lcb:   CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
==> lcb:   AR(target) Release/obj.target/deps/libexpat/libexpat.a
==> lcb:   COPY Release/libexpat.a
==> lcb:   CXX(target) Release/obj.target/node_expat/node-expat.o
==> lcb: ../node-expat.cc: In static member function 'static v8::Handle<v8::Value> Parser::New(const v8::Arguments&)':
==> lcb: ../node-expat.cc:42:9: warning: 'void* NanRawString(v8::Handle<v8::Value>, Nan::Encoding, size_t*, void*, size_t, int)' is deprecated (declared at ../node_modules/nan/nan.h:2072) [-Wdeprecated-declarations]
==> lcb: ../node-expat.cc:42:64: warning: 'void* NanRawString(v8::Handle<v8::Value>, Nan::Encoding, size_t*, void*, size_t, int)' is deprecated (declared at ../node_modules/nan/nan.h:2072) [-Wdeprecated-declarations]
==> lcb: ../node-expat.cc: In static member function 'static v8::Handle<v8::Value> Parser::SetEncoding(const v8::Arguments&)':
==> lcb: ../node-expat.cc:150:9: warning: 'void* NanRawString(v8::Handle<v8::Value>, Nan::Encoding, size_t*, void*, size_t, int)' is deprecated (declared at ../node_modules/nan/nan.h:2072) [-Wdeprecated-declarations]
==> lcb: ../node-expat.cc:150:64: warning: 'void* NanRawString(v8::Handle<v8::Value>, Nan::Encoding, size_t*, void*, size_t, int)' is deprecated (declared at ../node_modules/nan/nan.h:2072) [-Wdeprecated-declarations]
==> lcb: ../node-expat.cc: In static member function 'static v8::Handle<v8::Value> Parser::Reset(const v8::Arguments&)':
==> lcb: ../node-expat.cc:223:9: warning: 'void* NanRawString(v8::Handle<v8::Value>, Nan::Encoding, size_t*, void*, size_t, int)' is deprecated (declared at ../node_modules/nan/nan.h:2072) [-Wdeprecated-declarations]
==> lcb: ../node-expat.cc:223:64: warning: 'void* NanRawString(v8::Handle<v8::Value>, Nan::Encoding, size_t*, void*, size_t, int)' is deprecated (declared at ../node_modules/nan/nan.h:2072) [-Wdeprecated-declarations]
==> lcb:   SOLINK_MODULE(target) Release/obj.target/node_expat.node
==> lcb:   SOLINK_MODULE(target) Release/obj.target/node_expat.node: Finished
==> lcb:   COPY Release/node_expat.node
==> lcb: make: Leaving directory `/home/vagrant/lets-chat/node_modules/node-xmpp-core/node_modules/ltx/node_modules/node-expat/build'
==> lcb: npm
==> lcb:
==> lcb: ERR!
==> lcb:  Error: 400 Bad Request
==> lcb: npm
==> lcb:
==> lcb: ERR!
==> lcb:      at WriteStream.<anonymous> (/usr/lib/node_modules/npm/lib/utils/fetch.js:58:12)
==> lcb: npm
==> lcb:
==> lcb: ERR!
==> lcb:      at WriteStream.emit (events.js:117:20)
==> lcb: npm
==> lcb:
==> lcb: ERR!
==> lcb:      at evalmachine.<anonymous>:1609:14
==> lcb: npm
==> lcb:
==> lcb: ERR!
==> lcb:      at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
==> lcb: npm
==> lcb:
==> lcb: ERR!
==> lcb:      at Object.oncomplete (evalmachine.<anonymous>:107:15)
==> lcb: npm ERR! If you need help, you may report this *entire* log,
==> lcb: npm ERR! including the npm and node versions, at:
==> lcb: npm ERR!     <http://github.com/npm/npm/issues>
==> lcb:
==> lcb: npm ERR! System Linux 3.2.0-23-generic-pae
==> lcb: npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
==> lcb: npm ERR! cwd /home/vagrant/lets-chat
==> lcb: npm ERR! node -v v0.10.33
==> lcb: npm ERR! npm -v 1.4.28
==> lcb: npm
==> lcb:
==> lcb: ERR!
==> lcb:
==> lcb: not ok code 0
==> lcb:
==> lcb: > lets-chat@0.3.3 prestart /home/vagrant/lets-chat
==> lcb: > migroose
==> lcb: module.js:340
==> lcb:     throw err;
==> lcb:
==> lcb:
==> lcb:   ^
==> lcb: Error: Cannot find module 'mongoose-validate'
==> lcb:     at Function.Module._resolveFilename (module.js:338:15)
==> lcb:     at Function.Module._load (module.js:280:25)
==> lcb:     at Module.require (module.js:364:17)
==> lcb:     at require (module.js:380:17)
==> lcb:     at Object.<anonymous> (/home/vagrant/lets-chat/app/models/user.js:16:16)
==> lcb:     at Module._compile (module.js:456:26)
==> lcb:     at Object.Module._extensions..js (module.js:474:10)
==> lcb:     at Module.load (module.js:356:32)
==> lcb:     at Function.Module._load (module.js:312:12)
==> lcb:     at Module.require (module.js:364:17)
==> lcb:     at require (module.js:380:17)
==> lcb:     at Object.<anonymous> (/home/vagrant/lets-chat/migrootions/1421183479874-users.js:3:12)
==> lcb: npm
==> lcb:
==> lcb: ERR!
==> lcb:  lets-chat@0.3.3 prestart: `migroose`
==> lcb: npm
==> lcb:
==> lcb: ERR!
==> lcb:  Exit status 8
==> lcb: npm
==> lcb:  ERR!
==> lcb: npm ERR! Failed at the lets-chat@0.3.3 prestart script.
==> lcb: npm
==> lcb:
==> lcb: ERR!
==> lcb:  This is most likely a problem with the lets-chat package,
==> lcb: npm
==> lcb:  ERR! not with npm itself.
==> lcb: npm ERR! Tell the author that this fails on your system:
==> lcb: npm ERR!     migroose
==> lcb: npm ERR!
==> lcb:  You can get their info via:
==> lcb: npm
==> lcb:
==> lcb: ERR!
==> lcb:      npm owner ls lets-chat
==> lcb: npm
==> lcb:
==> lcb: ERR!
==> lcb:  There is likely additional logging output above.
==> lcb: npm ERR! System Linux 3.2.0-23-generic-pae
==> lcb: npm ERR!
==> lcb:
==> lcb: command "/usr/bin/node" "/usr/bin/npm" "start"
==> lcb: npm ERR! cwd /home/vagrant/lets-chat
==> lcb: npm
==> lcb:
==> lcb: ERR! node -v v0.10.33
==> lcb: npm ERR! npm -v 1.4.28
==> lcb: npm ERR!
==> lcb:
==> lcb: code
==> lcb:  ELIFECYCLE
==> lcb: npm
==> lcb:
==> lcb: ERR!
==> lcb:
==> lcb: npm
==> lcb:
==> lcb: ERR!
==> lcb:  Additional logging details can be found in:
==> lcb: npm
==> lcb:
==> lcb: ERR!
==> lcb:      /home/vagrant/lets-chat/npm-debug.log
==> lcb: npm
==> lcb:
==> lcb: ERR!
==> lcb:  not ok code 0
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by geoffwhittington** [comment]
Can you provide some specifics?

- Vagrant version and platform. I just tested this on Windows 7 with 1.7.2 and it installs without any issue.
- Was this a fresh install using the default Vagrant file without modification?

**Comment by Twilek-de** [comment]
Debian 64bit testing
Apt installation of virtualbox and vagrant. Unmodified vagrant file in a fresh clone from git.

**Comment by geoffwhittington** [comment]
Sorry, I don't have access to Debian 64bit. What version of Vagrant and Virtualbox?

**Comment by Twilek-de** [comment]
Vagrant 1.6.5
Virtualbox 4.3.18
Both from the regular Debian repository.

**Comment by geoffwhittington** [comment]
Thanks! Next question, is this from master branch or from a tagged version of lets chat?

I can't seem to replicate using master branch. Have you looked at the npm logs?

Docker may provide you a better option. The Vagrant install still relies on dynamic installation which we can't control: your network connection, node repository selection, etc.

It would be nice if someone could post a working VM online that people could download and run.

**Comment by Twilek-de** [comment]
I followed the instructions from the wiki, so that would be the master version then. I just tried again. It would still show a couple of errors with the expat thing but would run through. Maybe it really is sonething dynamic.

**Comment by geoffwhittington** [comment]
When you say it runs through so you mean its working now - or still failing?

**Comment by Twilek-de** [comment]
The installation runs through with errors and it is working after that.

**Comment by geoffwhittington** [comment]
Ah cool! Not sure about those errors.
FYI I posted #298 today about Vagrant.

Can we close this issue now?

**Comment by Twilek-de** [comment]
As I myself cannot really replicate it anymore you can.
