### ISSUE TITLE
Vagrant guest install doesn't expose ports to host

### ISSUE THREAD

**Issue by geoffwhittington** [sdelements/lets-chat#298]
There's a bug we introduced that means when you spin up Lets Chat using Vagrant you can't access it via the host.

The workaround is to get onto the guest VM and change `http.host ` in `settings.yml` to `0.0.0.0` and restart lets chat.

**Comment by hhaidar** [comment]
I know it's a security issue, but would it make sense to just make the setting promiscuous then?

**Comment by geoffwhittington** [comment]
There are two options we can consider:
- Modify the settings file just for Vagrant (sed command) and set the option explicitly before npm start
- Pass an environment variable in the npm start in the Vagrant file and use that. I think `http.host` works?
