### ISSUE TITLE
IE 11 downloading .json file

### ISSUE THREAD

**Issue by memphisraynz** [sdelements/lets-chat#300]
Trying to login under Internet Explorer 11 and the  broswer tries to save the JSON response as an attachment.
The contents are simply  {"status":"success","message":"Logging you in..."}

Cheers

**Comment by hhaidar** [comment]
Working fine for me on Windows 7 with IE11.

Does the console show any errors?

**Comment by memphisraynz** [comment]
Nothing, the only message I receive is the same message I've been getting from the start
express deprecated req.host: Use req.hostname instead node_modules/express.oi/lib/index.js:72:46

**Comment by hhaidar** [comment]
I mean the IE11 console: https://msdn.microsoft.com/en-us/library/ie/dn255006%28v=vs.85%29.aspx

This issue happens when javascript breaks in the login page.

**Comment by memphisraynz** [comment]
After opening console I found that IE was running Intranet sites in compatibility mode. Because this is running on the local network it considers it Intranet.

**Comment by hhaidar** [comment]
@memphisraynz try pulling the latest from master and restart your server. We should be sending an `X-UA-Compatible` header now.

**Comment by memphisraynz** [comment]
Thanks,
One I set IE to not use compatibility mode  it works perfectly.
Cheers
