### ISSUE TITLE
XMPP: Connect, but no Login

### ISSUE THREAD

**Issue by jangrewe** [sdelements/lets-chat#302]
My Let's Chat setup allows me use the HTTP-based chat just fine, but i can't login via XMPP. Pidgin (2.10.11) is able to connect, and i see some output on the console when enabling debugging, but then it just stays at "Connecting...", so the actual login doesn't work. Username and password should be fine, as they're working via HTTP. I have TLS enabled and use a self-signed certificate.

The output is:
```
<iq type="get" id="purple15e30041" to="chat.example.com" xmlns:stream="http://etherx.jabber.org/streams" from="jgrewe@chat.example.com/work"><query xmlns="http://jabber.org/protocol/disco#items"/></iq>
<iq type="get" id="purple15e30042" to="chat.example.com" xmlns:stream="http://etherx.jabber.org/streams" from="jgrewe@chat.example.com/work"><query xmlns="http://jabber.org/protocol/disco#info"/></iq>
```
I get these lines each time i try to login.

**Comment by sibartlett** [comment]
Have you configured the XMPP host setting? That is a must for XMPP to work.

**Comment by jangrewe** [comment]
Oh, i was under the impression that this setting controls on which address the service listens, like the HTTP setting... it's working now, thanks!

**Comment by sibartlett** [comment]
Yeah, sorry for the confusion. We may need to rename this setting.

**Comment by geoffwhittington** [comment]
For now we can update the documentation FAQ / wiki to clarify this
