### ISSUE TITLE
lets-chat wont start

### ISSUE THREAD

**Issue by wilspi** [sdelements/lets-chat#306]
I have installed lets-chat in arch linux. It showed the following warning while installing
![screenshot from 2015-02-23 22 08 40](https://cloud.githubusercontent.com/assets/7404121/6332046/05a55eec-bba9-11e4-94be-3e3592444244.png)

And when npm start
![screenshot from 2015-02-23 21 51 41](https://cloud.githubusercontent.com/assets/7404121/6332052/0e2d3dbe-bba9-11e4-881b-71d5ee537ac0.png)

**Comment by geoffwhittington** [comment]
I notice you're running node v0.12.0 - that may the source of your trouble? We develop and test against 0.10.x

https://github.com/sdelements/lets-chat#what-version-of-nodejs-is-required

**Comment by hhaidar** [comment]
is mongodb running?

**Comment by hhaidar** [comment]
Sorry, I was on the phone and didn't look at the entire image.

Try reinstalling your modules:

```
rm -rf node_modules
npm cache clear
npm install
```

**Comment by wilspi** [comment]
@hhaidar that worked 
with these errors (if nothing serious)
![screenshot from 2015-02-24 01 37 42](https://cloud.githubusercontent.com/assets/7404121/6336028/c2b7a05a-bbc5-11e4-8fa7-84ee96fe0a63.png)

![screenshot from 2015-02-24 01 33 23](https://cloud.githubusercontent.com/assets/7404121/6335939/26f218f8-bbc5-11e4-97dd-c0ef963dfc3d.png)

**Comment by hhaidar** [comment]
@wilspi ah cool, great to hear.

My coworker @hanifvirani  also uses arch linux and has this issue as well.
