### ISSUE TITLE
Update not work

### ISSUE THREAD

**Issue by dbr1337** [sdelements/lets-chat#310]
Hello,
the update from git with "git pull" will not work 100 percent.
How can i be up to date everytime? The new files are loading, but where not implemented.

Greetings

**Comment by sibartlett** [comment]
Pulling the latest from git, and restarting the node application should work.

Could you try that again, to make sure? I pushed an update very recently.

Also when you say the new files are loading, and not implemented - what do you mean? You mean the app won't start? Are there errors?

**Comment by dbr1337** [comment]
I pulled the newest update, and looked for the password room plugin in the file app/models/room.js but no entry for that exists. When i pull, i restart the lets chat server. Or what i must do?

**Comment by sibartlett** [comment]
Password rooms has not been merged in yet. That feature is still in development, and there's currently a pull request open for it.

**Comment by dbr1337** [comment]
Okay, good.

My next question:
I need Port 5223 for XMPP in combination with SSL.
I have tls and certificates enabled, but it doesnt work with port 5223.
How can i change that?

**Comment by geoffwhittington** [comment]
@dbr1337 Unfortunately we don't typically handle differing topics in the same issue: it doesn't help future users find answers to similar problems. I'm closing this issue as it looks like its solved.

Please use the mailing for deployment/implementation questions:

https://groups.google.com/forum/#!forum/lets-chat-app
