### ISSUE TITLE
We need a stable master branch

### ISSUE THREAD

**Issue by geoffwhittington** [sdelements/lets-chat#311]
Create a develop branch

- master tracks the latest stable version people can count on
- develop is bleeding edge functionality that should not be used in production scenarios
- New feature work should be merged from a pull request into develop.
- develop can be promoted to master after we get sign-off from @hhaidar and/or @sibartlett 
- Bugs in master are fixed via pull request
- Direct commits to master should be very limited. If in doubt, create a pull request

**Comment by funkaoshi** [comment]
Agreed.

**Comment by hhaidar** [comment]
There's already a master branch, can you put this in CONTRIBUTING.md?

**Comment by sibartlett** [comment]
Do we want external people opening pull requests against develop? Maybe having them open pull requests against master is a good thing?
