### ISSUE TITLE
SSL Error ?

### ISSUE THREAD

**Issue by yiqin** [sdelements/lets-chat#318]
I run npm install, but it turned out that it didn't success. I'm a beginner. Could anyone help me?

npm ERR! Additional logging details can be found in:
npm ERR!     /Users/yiqin/Desktop/lets-chat-master/npm-debug.log
npm ERR! not ok code 0

From npm-debug.log
747 info retry registry request attempt 3 at 11:51:47
748 http GET https://registry.npmjs.org/connect-assets
749 error Error: SSL Error: CERT_UNTRUSTED
749 error     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/main.js:440:26)
749 error     at ClientRequest.g (events.js:185:14)
749 error     at ClientRequest.EventEmitter.emit (events.js:88:17)
749 error     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1445:7)
749 error     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:111:23)
749 error     at CleartextStream.socketOnData [as ondata] (http.js:1356:20)
749 error     at CleartextStream.CryptoStream._push (tls.js:396:27)
749 error     at SecurePair.cycle (tls.js:750:20)
749 error     at EncryptedStream.CryptoStream.write (tls.js:131:13)
749 error     at Socket.ondata (stream.js:38:26)
749 error  [Error: SSL Error: CERT_UNTRUSTED]
750 error You may report this log at:
750 error     <http://github.com/isaacs/npm/issues>
750 error or email it to:
750 error     <npm-@googlegroups.com>
751 error System Darwin 14.1.0
752 error command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
753 error cwd /Users/yiqin/Desktop/lets-chat-master
754 error node -v v0.8.2
755 error npm -v 1.1.36
756 error message SSL Error: CERT_UNTRUSTED
757 verbose exit [ 1, true ]

**Comment by sibartlett** [comment]
Sorry, but could you report this issue in our mailing list: https://groups.google.com/forum/#!forum/lets-chat-app

This is to ensure that future users can find answers to similar problems.

Thank you.

**Comment by sibartlett** [comment]
You were using outdated versions of Node.js and NPM. Let's Chat requires Node 0.10

**Comment by yiqin** [comment]
Thanks. It works !
