### ISSUE TITLE
Update heroku deployed app

### ISSUE THREAD

**Issue by depinav** [sdelements/lets-chat#320]
Not sure if this was answered anywhere else, but I initially used the "deploy on heroku" button to get an instance of let's chap running. I was wondering what the steps were to update the currently running instance with any updates from this repo?

**Comment by sibartlett** [comment]
You'll need to clone/pull the latest changes from our GitHub repository, and then force push to Heroku:

```
git push git@heroku.com:APP_NAME.git master --force
```

I'll update the wiki.

**Comment by depinav** [comment]
Nice, I'll give it a shot when I get home. Thanks.

**Comment by sibartlett** [comment]
@depinav Did it work?

**Comment by funkaoshi** [comment]
@depinav if it didn't, can you please move the discussion over to our [mailing list](https://groups.google.com/forum/#!forum/lets-chat-app). We will use Github issues solely for tracking feature work and bugs going forward. Thanks.
