### ISSUE TITLE
Inline image crop

### ISSUE THREAD

**Issue by depinav** [sdelements/lets-chat#321]
Are there any plans to change the inline image crop and just resize the image so we can see the full thing?

**Comment by geoffwhittington** [comment]
I would prefer that too, myself. In LCB 0.2 I thought there was a resize, but I could be mistaken @hhaidar?

**Comment by funkaoshi** [comment]
It used to re-size to fit. Not it resizes to fit the width, and crops the height. I assume for aesthetics.

**Comment by hhaidar** [comment]
Fixed via d1080ad5b016e22e9f3d4f65f15b32d679e8d3df
