### ISSUE TITLE
Status change (XMPP) generates topic change?

### ISSUE THREAD

**Issue by SleeplessAnnoyedNerd** [sdelements/lets-chat#322]
If we connect via XMPP to our let's Chat instance (via Adium/Mac or Pidgin/Linux) and user changes his status he gets "topic changed" message (s. screenshot ("user X has changed topic to"), sorry for German text). This is a bit of an annoyance b/c history is filled w/ these useless messages.

![jdgbcbia](https://cloud.githubusercontent.com/assets/2134355/6426128/d0a8204a-bf49-11e4-8892-b2e9d965fdfc.png)

Workround is to comment

```
subject.c('subject').t(room.name + ' | ' + room.description);
```

in `xmpp/msg-processors/room-join.js` and `xmpp/events/room-updated.js`.

Unfortunately I'm unsure which is the cause for this. But maybe this helps someone out there.

OT: Thanks for providing let's Chat!

**Comment by sibartlett** [comment]
This has been annoying me too, I'll work on a fix for this.

**Comment by sibartlett** [comment]
This has been fixed on master.
