### ISSUE TITLE
errno 34 on npm install

### ISSUE THREAD

**Issue by jackiekaye89** [sdelements/lets-chat#329]
```
8215 error If you need help, you may report this log at:
8215 error     <http://github.com/isaacs/npm/issues>
8215 error or email it to:
8215 error     <npm-@googlegroups.com>
8216 error System Linux 3.13.0-37-generic
8217 error command "/usr/bin/nodejs" "/usr/bin/npm" "install"
8218 error cwd /home/jackiekaye89/Public/Projects/Misc/Other/lets-chat
8219 error node -v v0.10.25
8220 error npm -v 1.3.10
8221 error path /home/jackiekaye89/tmp/npm-12168-Vbyze5H7/1425261882022-0.024444887647405267/package/bench/speed.js
8222 error code ENOENT
8223 error errno 34
8224 verbose exit [ 34, true ]
```

I get that when I type npm install from the "/home/jackiekaye89/Public/Projects/Misc/Other/lets-chat" directory. That's not the full log, I'll upload the full .log file to a gist and link to it in a second.

**Comment by jackiekaye89** [comment]
here's the link to the [debug log](https://gist.github.com/jackiekaye89/a96f957e2e13621b4cd9) from NPM

**Comment by hhaidar** [comment]
Try this:

```
rm -rf ~/.npm
rm -rf node_modules
npm cache clean
npm install
```

Also what version of node/npm do you have?

**Comment by jackiekaye89** [comment]
uhh, just realized that I may know the reason it's not working XD I *don't* have node installed, I use ioJS XD

**Comment by hhaidar** [comment]
hah, let me know what happens :)

**Comment by jackiekaye89** [comment]
what do you mean?

**Comment by hhaidar** [comment]
Like if installing node doesn't work.

We don't officially support io.js yet.

**Comment by jackiekaye89** [comment]
is there no apt-get install for nodejs? the only things I can find is to build it from source XD

**Comment by jackiekaye89** [comment]
okay got nodejs installed

this error:

npm ERR! cb() never called!

is what I'm getting now.

**Comment by jackiekaye89** [comment]
okay, so nevermind on the previous error, I added permissions to certain node folders and that error went bye bye, but what are these ones for and how do I fix them?

```
npm WARN unmet dependency /home/jackiekaye89/Public/Projects2/lets-chat/node_modules/socket.io-client/node_modules/engine.io-client requires debug@'1.0.4' but will load
npm WARN unmet dependency /home/jackiekaye89/Public/Projects2/lets-chat/node_modules/socket.io-client/node_modules/debug,
npm WARN unmet dependency which is version 0.7.4
npm WARN unmet dependency /home/jackiekaye89/Public/Projects2/lets-chat/node_modules/socket.io-client/node_modules/engine.io-client requires parseuri@'0.0.4' but will load
npm WARN unmet dependency /home/jackiekaye89/Public/Projects2/lets-chat/node_modules/socket.io-client/node_modules/parseuri,
npm WARN unmet dependency which is version 0.0.2
```

**Comment by funkaoshi** [comment]
Please move the discussion over to the [Let's Chat mailing list][1]. Github issues should be used to track features and bugs in the code.

[1]:https://groups.google.com/forum/#!forum/lets-chat-app

**Comment by jackiekaye89** [comment]
how is this not an issue? I can't figure out how to get the thing up and running, obviously for either one of two reasons... either I'm just stupid, or your documentation needs to be clarified. However, this is still an issue, and not a 'discussion'

**Comment by sibartlett** [comment]
@jackiekaye89 will the app run, even with those NPM warnings?

**Comment by funkaoshi** [comment]
@jackiekaye89  Sure, but you should discuss this _issue_ on the mailing list. That's where we are trying to move the discussion of all deployment issues. If there is a specific problem with our documentation or a bug in our code, we can then make an issue or pull request to update as needed. As it stands support requests were clogging up the Github issue tracker, which isn't a good place for this stuff to live.

We assume you have a box running NodeJS and Mongo. We don't really have the time to help people set up NodeJS on their boxes, which seems fair. This is a side project for us.
