### ISSUE TITLE
express deprecated req.host: Use req.hostname instead node_modules/express.oi/lib/index.js

### ISSUE THREAD

**Issue by wahaha2001** [sdelements/lets-chat#332]
Got this error when try to login with LDAP option, tried upgrade the express.io to the latest version, but still got same error.  Not sure if this error caused I can't login with LDAP.

How can I fix this?  Thanks.

**Comment by geoffwhittington** [comment]
This is more of a warning, than an error. Word of warning: we use `express.oi` not `express.io`.

LDAP should work regardless of the warning. Someone on https://groups.google.com/forum/#!forum/lets-chat-app may be able to help troubleshoot LDAP
