### ISSUE TITLE
Wrong URL link target

### ISSUE THREAD

**Issue by nicklegr** [sdelements/lets-chat#333]
URL in message is auto-linked, but link target is wrong in some cases.

For example, When I post a URL below:
https://github.com/sdelements/lets-chat/wiki/API%3A-Messages#post-messages

It's displayed correctly, but actually linked to:
https://github.com/sdelements/lets-chat/wiki/API%253A-Messages#post-messages

I think '%' should not be escaped in this case.

Tested on heroku and docker with master branch.
Browser is Firefox 35.0.1 (Mac).

**Comment by hhaidar** [comment]
@nicklegr this should be fixed, do you mind trying out the latest code on master?

**Comment by nicklegr** [comment]
Confirmed. Thank you!
