### ISSUE TITLE
Install didn't work on Debian wheezy

### ISSUE THREAD

**Issue by K3r0sen** [sdelements/lets-chat#336]
Please advice 

npm-debug.log 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'owner', 'ls', 'lets-chat' ]
2 info using npm@1.4.28
3 info using node@v0.10.36
4 verbose node symlink /usr/bin/node
5 verbose request where is /lets-chat
6 verbose request registry https://registry.npmjs.org/
7 verbose request id 6b95e3cb0ccbb456
8 verbose url raw /lets-chat
9 verbose url resolving [ 'https://registry.npmjs.org/', './lets-chat' ]
10 verbose url resolved https://registry.npmjs.org/lets-chat
11 verbose request where is https://registry.npmjs.org/lets-chat
12 info trying registry request attempt 1 at 23:00:25
13 http GET https://registry.npmjs.org/lets-chat
14 http 404 https://registry.npmjs.org/lets-chat
15 verbose headers { date: 'Tue, 03 Mar 2015 23:00:26 GMT',
15 verbose headers   server: 'CouchDB/1.6.1 (Erlang OTP/R14B04)',
15 verbose headers   'content-type': 'application/json',
15 verbose headers   'cache-control': 'max-age=0',
15 verbose headers   'content-length': '52',
15 verbose headers   'accept-ranges': 'bytes',
15 verbose headers   via: '1.1 varnish',
15 verbose headers   age: '0',
15 verbose headers   'x-served-by': 'cache-fra1244-FRA',
15 verbose headers   'x-cache': 'MISS',
15 verbose headers   'x-cache-hits': '0',
15 verbose headers   'x-timer': 'S1425423626.070308,VS0,VE111',
15 verbose headers   'keep-alive': 'timeout=10, max=50',
15 verbose headers   connection: 'Keep-Alive' }
16 silly registry.get cb [ 404,
16 silly registry.get   { date: 'Tue, 03 Mar 2015 23:00:26 GMT',
16 silly registry.get     server: 'CouchDB/1.6.1 (Erlang OTP/R14B04)',
16 silly registry.get     'content-type': 'application/json',
16 silly registry.get     'cache-control': 'max-age=0',
16 silly registry.get     'content-length': '52',
16 silly registry.get     'accept-ranges': 'bytes',
16 silly registry.get     via: '1.1 varnish',
16 silly registry.get     age: '0',
16 silly registry.get     'x-served-by': 'cache-fra1244-FRA',
16 silly registry.get     'x-cache': 'MISS',
16 silly registry.get     'x-cache-hits': '0',
16 silly registry.get     'x-timer': 'S1425423626.070308,VS0,VE111',
16 silly registry.get     'keep-alive': 'timeout=10, max=50',
16 silly registry.get     connection: 'Keep-Alive' } ]
17 error owner ls Couldn't get owner data lets-chat
18 error 404 404 Not Found: lets-chat
18 error 404
18 error 404 'lets-chat' is not in the npm registry.
18 error 404 You should bug the author to publish it
18 error 404

**Comment by geoffwhittington** [comment]
Hi, can you post this issue and, importantly, the command you ran to get this output to:

https://groups.google.com/forum/#!forum/lets-chat-app
