### ISSUE TITLE
Uploading certain files (local) causes a "Bad Request" notice.

### ISSUE THREAD

**Issue by mikeohara** [sdelements/lets-chat#338]
Uploading a spreadsheet (xlsx) file into Lets-Chat seems to cause a "Bad Request" error during upload.

![screenshot 2015-03-04 10 07 28](https://cloud.githubusercontent.com/assets/10249051/6484923/4d99d6de-c256-11e4-8402-54befd4f89a5.png)

We are running some tools like ModSecurity and various monitoring tools on the same environment, would that interfere with this?

**Comment by sibartlett** [comment]
There are configuration settings for whitelisting file types, I think that may be the issue on your installation: https://github.com/sdelements/lets-chat/wiki/Files

Error messaging is definitely something we need to improve upon.

**Comment by mikeohara** [comment]
My Config file is as follows (relivent portion)

`files:`
 ` enable: true`
 ` provider: local`
 ` maxFileSize: 1000000000`
 ` local:`
 `   dir: uploads`

`xmpp:`
`  enable: false`
`  port: 5222`
`  host: localhost`

I am not currently restricting any file types. Or is it that I have to explicitly allow file types for them to work by default?

**Comment by sibartlett** [comment]
Files are restricted by default.

You can turn this restriction off, but doing the following:

```
files:
  restrictTypes: false
```

Or whitelist more file types, doing this:

```
files:
  allowedTypes:
    - 'image/jpeg'
    - 'image/png'
    - 'image/gif'
```

**Comment by mikeohara** [comment]
That did it!

Thanks!

*Mike O'Hara*
O'Hara Consulting
*O:* (506) 387-6100
*C:* (506) 962-6100

Twitter <http://twitter.com/#%21/mike_ohara> | Linkedin
<http://ca.linkedin.com/in/mikerohara>

**Comment by geoffwhittington** [comment]
Great to hear @mikeohara ! I've updated https://github.com/sdelements/lets-chat/wiki/Files to clarify things. Please read it over for the additional security note.
