### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by Uelee** [sdelements/lets-chat#343]
1.Permissions are not clear, anyone can establish a room, you can delete the others in room, use of unsafe
2.Room names does not support Chinese
3.Registry link control is not easy, you need to change the file: settings.yml implementation，Enrollment support via email registration
4.User-created rooms require approval，Support room management
5.Support for custom avatars，Input box paste the file support

**Comment by notsrg** [comment]
A few of these already have issues created for them and plan to be addressed in the future. 

Just by searching I have found:
https://github.com/sdelements/lets-chat/issues/4
https://github.com/sdelements/lets-chat/issues/33

Please read the contributing guidelines before creating an issue next time as not following these rules makes it harder to maintain the backlog of work to be done. 
https://github.com/sdelements/lets-chat/blob/master/CONTRIBUTING.md

**Comment by Uelee** [comment]
Thk
