### ISSUE TITLE
npm start can't start

### ISSUE THREAD

**Issue by 3588** [sdelements/lets-chat#346]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/node/bin/node', '/usr/sbin/npm', 'start' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart lets-chat@0.3.8
6 verbose unsafe-perm in lifecycle true
7 info start lets-chat@0.3.8
8 verbose unsafe-perm in lifecycle true
9 info lets-chat@0.3.8 Failed to exec start script
10 verbose stack Error: lets-chat@0.3.8 start: `node app.js`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/node/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/node/lib/node_modules/npm/lib/utils/spawn.js:14:12)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1008:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
11 verbose pkgid lets-chat@0.3.8
12 verbose cwd /root/chat/lets-chat
13 error Linux 2.6.32-431.1.2.0.1.el6.x86_64
14 error argv "/usr/local/node/bin/node" "/usr/sbin/npm" "start"
15 error node v0.12.0
16 error npm  v2.5.1
17 error code ELIFECYCLE
18 error lets-chat@0.3.8 start: `node app.js`
18 error Exit status 1
19 error Failed at the lets-chat@0.3.8 start script 'node app.js'.
19 error This is most likely a problem with the lets-chat package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     node app.js
19 error You can get their info via:
19 error     npm owner ls lets-chat
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

**Comment by 3588** [comment]
try move to nodejs v0.10.9

**Comment by 3588** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.7.0
3 info using node@v0.10.9
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart lets-chat@0.3.8
6 verbose unsafe-perm in lifecycle true
7 info start lets-chat@0.3.8
8 verbose unsafe-perm in lifecycle true
9 info lets-chat@0.3.8 Failed to exec start script
10 verbose stack Error: lets-chat@0.3.8 start: `node app.js`
10 verbose stack Exit status 8
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:98:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
10 verbose stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
10 verbose stack     at maybeClose (child_process.js:735:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:802:5)
11 verbose pkgid lets-chat@0.3.8
12 verbose cwd /root/chat/lets-chat
13 error Linux 2.6.32-431.1.2.0.1.el6.x86_64
14 error argv "node" "/usr/local/bin/npm" "start"
15 error node v0.10.9
16 error npm  v2.7.0
17 error code ELIFECYCLE
18 error lets-chat@0.3.8 start: `node app.js`
18 error Exit status 8
19 error Failed at the lets-chat@0.3.8 start script 'node app.js'.
19 error This is most likely a problem with the lets-chat package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     node app.js
19 error You can get their info via:
19 error     npm owner ls lets-chat
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

**Comment by 3588** [comment]
try move to x86

**Comment by geoffwhittington** [comment]
Hello, could you please use https://groups.google.com/forum/m/#!forum/lets-chat-app

For your deployment question? Also, please post your operating system, etc
