### ISSUE TITLE
enable xmpp error

### ISSUE THREAD

**Issue by tobor** [sdelements/lets-chat#347]
Cannot load StringPrep-0.7.0 bindings (using fallback). You may need to `npm install node-stringprep`

**Comment by tobor** [comment]
npm ERR! extraneous: node-stringprep@0.7.0 /opt/lets-chat/node_modules/node-stringprep
npm ERR! not ok code 0

**Comment by geoffwhittington** [comment]
We don't have a lot of context to work with here: like your OS, node, npm versions, what you ran, what exactly is not working, etc.

Please use the mailing list for your deployment issue: https://groups.google.com/forum/#!forum/lets-chat-app
