### ISSUE TITLE
Ubuntu 14.04 Server npm start issue

### ISSUE THREAD

**Issue by BornLuna** [sdelements/lets-chat#348]
I'm trying to setup lets chat on a ubuntu 14.04 server. I setup everything the readme file and website said and when I go to run "npm start" I get the following:

```
root@io:~/lets-chat# npm start

> lets-chat@0.3.8 prestart /root/lets-chat
> migroose

/usr/bin/env: node: No such file or directory
npm ERR! weird error 127
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0
root@io:~/lets-chat# 
```

**Comment by hhaidar** [comment]
`sudo apt-get install nodejs-legacy`

**Comment by hhaidar** [comment]
also, please don't run this as root... :(

**Comment by notsrg** [comment]
Please do not use the issue tracker for personal support requests, instead use our mailing list:
https://groups.google.com/forum/#!forum/lets-chat-app
