### ISSUE TITLE
Upload causes MIME type error

### ISSUE THREAD

**Issue by Fibrewire** [sdelements/lets-chat#349]
Running Ubuntu 14.04.1 LTS
![capture](https://cloud.githubusercontent.com/assets/2836205/6573896/4748255e-c717-11e4-88df-050c63e67b79.PNG)
![capture2](https://cloud.githubusercontent.com/assets/2836205/6573897/47482612-c717-11e4-8ff5-3ecc27555900.PNG)

**Comment by geoffwhittington** [comment]
Your file upload settings are not setup the way you want. Please check the wiki for more details about setting this up:

https://github.com/sdelements/lets-chat/wiki/Files

**Comment by Fibrewire** [comment]
That resolved the issue, thank you very much @geoffwhittington

**Comment by geoffwhittington** [comment]
Awesome! thanks for checking in
