### ISSUE TITLE
npm start failed with "sh: 1: migroose: Permission denied"

### ISSUE THREAD

**Issue by mekery** [sdelements/lets-chat#350]
Hi guys, 

I got errors when perform 'npm start'.
My environment is node -v v0.10.28, npm -v 1.4.9.

Thanks in advance!

$ npm start

> lets-chat@0.3.8 prestart /micle/tech/git/github/mekery/lets-chat
> migroose

sh: 1: migroose: Permission denied

>npm ERR! lets-chat@0.3.8 prestart: `migroose`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the lets-chat@0.3.8 prestart script.
npm ERR! This is most likely a problem with the lets-chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     migroose
npm ERR! You can get their info via:
npm ERR!     npm owner ls lets-chat
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-36-generic
npm ERR! command "/share/bin/node" "/share/bin/npm" "start"
npm ERR! cwd /micle/tech/git/github/mekery/lets-chat
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /micle/tech/git/github/mekery/lets-chat/npm-debug.log
npm ERR! not ok code 0

**Comment by geoffwhittington** [comment]
Hi @mekery  There's doesn't seem much there to go on, unfortunately. Permission issues are typically beyond the scope of the project. Please use the mailing to post your deployment issue:

https://groups.google.com/forum/#!forum/lets-chat-app

Be sure to post the contents of your redacted debug log: `/micle/tech/git/github/mekery/lets-chat/npm-debug.log`

**Comment by mekery** [comment]
Thanks @geoffwhittington

**Comment by 1337sup3rh4x0r** [comment]
Has anyone come up with a solution to this?

I am getting the same problem on npm start:


    root@servername:/home/lets-chat# npm start

    > lets-chat@0.4.2 prestart /home/lets-chat
    > migroose

    sh: 1: migroose: Permission denied

    npm ERR! Linux 3.2.0-4-amd64
    npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
    npm ERR! node v0.12.7
    npm ERR! npm  v2.11.3
    npm ERR! code ELIFECYCLE
    npm ERR! lets-chat@0.4.2 prestart: `migroose`
    npm ERR! Exit status 126
    npm ERR!
    npm ERR! Failed at the lets-chat@0.4.2 prestart script 'migroose'.
    npm ERR! This is most likely a problem with the lets-chat package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     migroose
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls lets-chat
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /home/lets-chat/npm-debug.log


The output of npm-debug.log is:

    0 info it worked if it ends with ok
    1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
    2 info using npm@2.11.3
    3 info using node@v0.12.7
    4 verbose node symlink /usr/bin/node
    5 verbose run-script [ 'prestart', 'start', 'poststart' ]
    6 info prestart lets-chat@0.4.2
    7 verbose unsafe-perm in lifecycle true
    8 info lets-chat@0.4.2 Failed to exec prestart script
    9 verbose stack Error: lets-chat@0.4.2 prestart: `migroose`
    9 verbose stack Exit status 126
    9 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
    9 verbose stack     at EventEmitter.emit (events.js:110:17)
    9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
    9 verbose stack     at ChildProcess.emit (events.js:110:17)
    9 verbose stack     at maybeClose (child_process.js:1015:16)
    9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
    10 verbose pkgid lets-chat@0.4.2
    11 verbose cwd /home/lets-chat
    12 error Linux 3.2.0-4-amd64
    13 error argv "/usr/bin/node" "/usr/bin/npm" "start"
    14 error node v0.12.7
    15 error npm  v2.11.3
    16 error code ELIFECYCLE
    17 error lets-chat@0.4.2 prestart: `migroose`
    17 error Exit status 126
    18 error Failed at the lets-chat@0.4.2 prestart script 'migroose'.
    18 error This is most likely a problem with the lets-chat package,
    18 error not with npm itself.
    18 error Tell the author that this fails on your system:
    18 error     migroose
    18 error You can get their info via:
    18 error     npm owner ls lets-chat
    18 error There is likely additional logging output above.
    19 verbose exit [ 1, true ]


Does anyone have a clue?
mongodb is up and running fine. 
the mongo log contains:

    [initandlisten] waiting for connections on port 27017

mongodb is version 3.0.6
