### ISSUE TITLE
Unknown migration error with migroose on Windows.

### ISSUE THREAD

**Issue by Roobyx** [sdelements/lets-chat#352]
I installed everything fine, the problem is that when I'm trying to do npm start it runs the migration command and it opens up the migroose.js which is unchanged, however it always responds with the message "Database migration required" and closes the application.

Im running mongodb fine on the default hosing port. I think the problem is that migroose connect function is not running. When I try to log something fromt the "connect" function is doesnt log anything, the function is simply not executed. I can log something from the "needsMigration" function so obviously it is not even connecting.

I don't know migroose very well and have no idea why this is happening. I am running on Windows 8.1 with node v0.10.36 and Mongo v2.6.8

[Terminal Window Screenshot](http://gyazo.com/7a81cb650806a7e6bf995f779137c46a)

**Comment by Intendit** [comment]
Encountered the same error, I simply commented out lines 255 to 264 in app.js to get it to run, but I'm suspecting that this issue is windows specific?

**Comment by sibartlett** [comment]
Yes, it seems to be a Windows-specific issue, we've also had another Windows user report the same error and work-around.

Commenting out lines 255 to 264 in app.js - is our suggested workaround for now.

**Comment by Roobyx** [comment]
Thanks for the solution. Worked as much as needed.

**Comment by Intendit** [comment]
Could we keep this issue open?
If windows compatibility is a goal it should be,

**Comment by funkaoshi** [comment]
Good point, i'll re-open.

**Comment by 1337sup3rh4x0r** [comment]
Commenting out these lines (in current version of app.js it's 273-282) doesn't help. I still get a crash of migroose. (in migroose.js, line 3, error: object expected, code: 800A138F, source: Runtime Error in Microsoft JScript)
Followed by an error in app.js:

> lets-chat@0.4.2 start C:\Program Files\lets-chat
    > node app.js

    C:\Program Files\lets-chat\node_modules\mongoose\node_modules\mongodb\lib\server.js:
    228
            process.nextTick(function() { throw err; })
                                                ^
    Error: Could not connect to database
        at NativeConnection.<anonymous> (C:\Program Files\lets-chat\app.js:190:11)
        at NativeConnection.emit (events.js:104:17)
        at NativeConnection.Object.defineProperty.set (C:\Program Files\lets-chat\node_modules\mongoose\lib\connection.js:105:14)
        at C:\Program Files\lets-chat\node_modules\mongoose\lib\connection.js:444:23
        at C:\Program Files\lets-chat\node_modules\mongoose\lib\drivers\node-mongodb-native\connection.js:57:21
        at C:\Program Files\lets-chat\node_modules\mongoose\node_modules\mongodb\lib\db.js:203:14
        at null.<anonymous> (C:\Program Files\lets-chat\node_modules\mongoose\node_modules\mongodb\lib\server.js:226:9)
        at g (events.js:199:16)
        at emit (events.js:110:17)
        at null.<anonymous> (C:\Program Files\lets-chat\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\lib\topologies\server.js:255:68)
        at g (events.js:199:16)
        at emit (events.js:110:17)
        at null.<anonymous> (C:\Program Files\lets-chat\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:77:12)
        at g (events.js:199:16)
        at emit (events.js:110:17)
        at Socket.<anonymous> (C:\Program Files\lets-chat\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\lib\connection\connection.js:118:49)

    npm ERR! Windows_NT 6.1.7601
    npm ERR! argv "T:\\Programme\\nodejs\\\\node.exe" "T:\\Programme\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
    npm ERR! node v0.12.7
    npm ERR! npm  v2.13.1
    npm ERR! code ELIFECYCLE
    npm ERR! lets-chat@0.4.2 start: `node app.js`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the lets-chat@0.4.2 start script 'node app.js'.
    npm ERR! This is most likely a problem with the lets-chat package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node app.js
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls lets-chat
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\Program Files\lets-chat\npm-debug.log

The output in npm-debug.log is:

    0 info it worked if it ends with ok
    1 verbose cli [ 'T:\\Programme\\nodejs\\\\node.exe',
    1 verbose cli   'T:\\Programme\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
    1 verbose cli   'start' ]
    2 info using npm@2.13.1
    3 info using node@v0.12.7
    4 verbose run-script [ 'prestart', 'start', 'poststart' ]
    5 info prestart lets-chat@0.4.2
    6 verbose unsafe-perm in lifecycle true
    7 info start lets-chat@0.4.2
    8 verbose unsafe-perm in lifecycle true
    9 info lets-chat@0.4.2 Failed to exec start script
    10 verbose stack Error: lets-chat@0.4.2 start: `node app.js`
    10 verbose stack Exit status 1
    10 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
    10 verbose stack     at EventEmitter.emit (events.js:110:17)
    10 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
    10 verbose stack     at ChildProcess.emit (events.js:110:17)
    10 verbose stack     at maybeClose (child_process.js:1015:16)
    10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
    11 verbose pkgid lets-chat@0.4.2
    12 verbose cwd C:\Program Files\lets-chat
    13 error Windows_NT 6.1.7601
    14 error argv "T:\\Programme\\nodejs\\\\node.exe" "T:\\Programme\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
    15 error node v0.12.7
    16 error npm  v2.13.1
    17 error code ELIFECYCLE
    18 error lets-chat@0.4.2 start: `node app.js`
    18 error Exit status 1
    19 error Failed at the lets-chat@0.4.2 start script 'node app.js'.
    19 error This is most likely a problem with the lets-chat package,
    19 error not with npm itself.
    19 error Tell the author that this fails on your system:
    19 error     node app.js
    19 error You can get their info via:
    19 error     npm owner ls lets-chat
    19 error There is likely additional logging output above.
    20 verbose exit [ 1, true ]

I have the current versions of nodejs, python27 and mongodb installed from the according websites. Path env variables are set correctly as well

**Comment by hhaidar** [comment]
@1337sup3rh4x0r if you opened up a cmd window, are you able to connect to your mongo instance via `mongo`?

The issue here is your install can't connect to mongo for some reason:

```
Error: Could not connect to database
```

**Comment by marsoln** [comment]
Hey guys,i got the same crash like @1337sup3rh4x0r (in migroose.js, line 3, error: object expected, code: 800A138F, source: Runtime Error in Microsoft JScript).

Here is my command line output if i run `node app.js`,

```
module.js:338
    throw err;
    ^

Error: Cannot find module 'utf8'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (H:\Github\letschat\lets-chat\node_modules\express.oi\
node_modules\socket.io\node_modules\engine.io\node_modules\engine.io-parser\lib\
index.js:5:12)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```


ENV: windows 7,python 2.7,node 4.1.2,npm 2.14.4

Any help will be grateful. Thx

**Comment by fourpixels** [comment]
Hi guys,
I don't get any specific error, I just get the message that I need to make a migrations. Running migrate simply says nothing. I had to comment out the check for migrations needed. There is no explanation what to do **at all**, which is a shame..

**Comment by ausminternet** [comment]
same problem here :(

**Comment by zhouseahe** [comment]
@hhaidar  cmd mongo connect the server , same error

**Comment by rockmasterflex69** [comment]
Its June 2016, this still hasn't been fixed?

**Comment by hhaidar** [comment]
@rockmasterflex69 it's a fundamental issue with the way windows works.

We *really* don't recommend that you run this thing on windows.. but if you insist, below are instructions on how to properly do it.

The error that @1337sup3rh4x0r @ marsoln have are because windows isn't associating .js files with node, you can fix that by opening an administrative shell and running:

```
assoc .js=node
```

Next you'll need to install `migroose-cli` globally;

```
npm install -g migroose-cli
```

Finally when prompted to run `npm run migrate` do this instead:

```
migroose.cmd
```

If someone wants to turn this into a script or has a better way of doing it, please let us know. @simon and I are also looking at removing migroose altogether.

**Comment by sibartlett** [comment]
We have removed migroose from Let's Chat.
