### ISSUE TITLE
events.js:72         throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by betashepherd** [sdelements/lets-chat#353]
npm --version
1.3.6

bash-4.1$ npm start

> lets-chat@0.3.8 prestart /home/work/wwwroot/lets-chat
> migroose

> lets-chat@0.3.8 start /home/work/wwwroot/lets-chat
> node app.js

██╗     ███████╗████████╗███████╗     ██████╗██╗  ██╗ █████╗ ████████╗
██║     ██╔════╝╚══██╔══╝██╔════╝    ██╔════╝██║  ██║██╔══██╗╚══██╔══╝
██║     █████╗     ██║   ███████╗    ██║     ███████║███████║   ██║   
██║     ██╔══╝     ██║   ╚════██║    ██║     ██╔══██║██╔══██║   ██║   
███████╗███████╗   ██║   ███████║    ╚██████╗██║  ██║██║  ██║   ██║   
╚══════╝╚══════╝   ╚═╝   ╚══════╝     ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝

Release 0.3.8

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1042:14)
    at listen (net.js:1064:10)
    at net.js:1146:9
    at asyncCallback (dns.js:68:16)
    at Object.onanswer [as oncomplete] (dns.js:121:9)
npm ERR! weird error 8
npm ERR! not ok code 0

**Comment by funkaoshi** [comment]
Hey, could you please move this question over to the [Let's Chat mailing list][1]. That's where we are trying to deal with any support issues.

Github issues should be used to track features and specific bugs in the code.

[1]:https://groups.google.com/forum/#!forum/lets-chat-app

**Comment by hhaidar** [comment]
@betashepherd change your port setting, you probably have something running on 5000 already

**Comment by betashepherd** [comment]
oh, yeah, got it. I have run psdash on port 5000, many thks.

**Comment by hhaidar** [comment]
@betashepherd nice, glad to hear!
