### ISSUE TITLE
Implement room/user/hashtag task handling

### ISSUE THREAD

**Issue by Chronos6** [sdelements/lets-chat#356]
Rooms, users and hashtags could have a task list. It would be nice to have tasks (like in Wunderlist or any task handling app) what you could assign to somebody or something and it could be prioritized, marked and described. The task list should be as simple as possible with as much flexibility as possible.

An alternative could be to link Let's-Chat to an existing task handling app. 

My user story:
My team has three responsibility groups what would be one chatroom each. The handled product versions would be hashtags with numbers. Both the rooms and the versions would have to-be-done tasks so anybody in the room could assign tasks either to the resp. group (room) or the version. If somebody proposes an inappropriate task, it could be ticked finished or could be reassigned to a version or another room. This way you can track both the small tasks and the progress within the chat.

**Comment by hhaidar** [comment]
How about [something like this](https://github.com/github/hubot-scripts/blob/master/src/scripts/tasks.coffee)

**Comment by Chronos6** [comment]
That's a good start! I think it would be needed to be visual, part of the GUI and its essential to bound it to any object you can think of. I listed three, but that could be extended.

**Comment by geoffwhittington** [comment]
This sounds pretty cool - integrated tasks with arbitrary objects. I might even use it.

But I don't think we should build it. There is a lot of opportunity for scope creep beyond what would be considered a chat application. Even if we did want to tackle this - it would be prioritized so low on the list of features that it wouldn't get worked on until 2018 given the resources we have.

We do already integrate Lets Chat with Jira here in our team. It works pretty well using Lets Chat replacements. We render #issues as links to Jira issues and people can click through to the Jira issue. Also, we are looking at further hooks so jira can create a message given certain events. There are hubots for more advanced things.

You have a cool idea but we can't focus on it. We take pull requests though!
