### ISSUE TITLE
IFrames, how do I allow them?

### ISSUE THREAD

**Issue by zwarmapapa** [sdelements/lets-chat#361]
I want Let's Chat to allow IFrames to intigrate Let's Chat into our system, but I couldn't find anything in the code that sets the x-frame-option to sameorigin. 

How do I allow Let's Chat to be IFramed?

**Comment by geoffwhittington** [comment]
Check out:

https://github.com/sdelements/lets-chat/blob/master/app.js#L78

The application sends "X-Frame-Options:SAMEORIGIN" as a security protection. Details of the `helmet.frameguard()` call is available here:

https://github.com/helmetjs/frameguard

**Comment by zwarmapapa** [comment]
Awesome, I first commented out "app.use(helmet.frameguard());", but that caused the connection to immediately break when using Let's Chat in an IFrame. After that I commented out everything from helmet and now IFrames work!

Thanks!

**Comment by geoffwhittington** [comment]
I hope you are running Lets Chat in a secured environment and you're aware of impacts of disabling the helmet options.

Enjoy!

**Comment by hhaidar** [comment]
![image](https://cloud.githubusercontent.com/assets/1066160/6669996/a7755c48-cbd2-11e4-81f8-a5a52a60b1ca.png)
