### ISSUE TITLE
DIfference active users between XMPP and HTTP interface

### ISSUE THREAD

**Issue by chiel1980** [sdelements/lets-chat#362]
It seems there is a difference between XMPP and the lets-chat HTTP interface:

I do see people in the rooms (and thus logged in) but I don't see them as active users in a XMPP client such as Adium (they are offline users).
Not sure if this is a feature or is a bug, I would expect that both interfaces share the same active roster list.

**Comment by notsrg** [comment]
Currently private messaging is only supported between other XMPP users. Supporting this in the web UI is on the roadmap.

**Comment by chiel1980** [comment]
I am not sure if that is the same: sharing a roster (seeing who us online) and private messaging between users.
But if this will be fixed by the other reported issue then I am happy with closing this ticket :)

**Comment by sibartlett** [comment]
@chiel1980 when you say roster, do you mean your Adium friend list (roster) or the user list once you have entered a room in Adium?

The friend list (roster) will not show any users, until we have implemented 1-to-1 chat.

**Comment by chiel1980** [comment]
The first, friend list or active users in Adium, but then I have to wait for the 1-to-1 chat feature :+1: 
Will this also be bundled with the password room in 1 release?
