### ISSUE TITLE
Enable file upload with docker-compose

### ISSUE THREAD

**Issue by bodiam** [sdelements/lets-chat#363]
Hi all,

I'm probably missing something here, but I'm trying to enable the file uploads, but I'm failing. 

I'm using docker-compose, and I'm running lets-chat via `docker-compose up`. All works fine, but now I want to enable file uploads, which I did by creating a settings.yml file in the checked out sources, and I've put in the following:

     files:
      enable: true
      provider: local
      maxFileSize: 100000000
      restrictTypes: true
      allowedTypes:
        - 'image/jpeg'
        - 'image/png'
        - 'image/gif'

I've restarted my docker container, but still I don't see the upload button. 

What am I missing here? Do I need to do something special when running in docker compared to npm?

Thanks, Erik

**Comment by funkaoshi** [comment]
Hey, could you please move this question over to the [Let's Chat mailing list][1]. That's where we are trying to deal with any support issues.

Github issues should be used to track features and specific bugs in the code.

[1]:https://groups.google.com/forum/#!forum/lets-chat-app

**Comment by bodiam** [comment]
For sure. Sorry for polluting the issues, I had not seen the mailing list!

**Comment by funkaoshi** [comment]
@bodiam No problem. You aren't the first person to post such a question here :P.

**Comment by paundl** [comment]
up!
upload is not working...
