### ISSUE TITLE
MongoDB configuration

### ISSUE THREAD

**Issue by gustavosiqueira94** [sdelements/lets-chat#364]
I'm trying to install Let's Chat and I'm having trouble to configure mongodb properly for its authentication. Made a search on web and checked files trying to find where this can be configured but failed. How can I configure a mongodb connection using the fields username and passwrod for authentication?

**Comment by hhaidar** [comment]
Something like this should work:

```
database:
  uri: mongodb://username:password@localhost/letschat
```

See: http://docs.mongodb.org/manual/reference/connection-string/

**Comment by hhaidar** [comment]
@gustavosiqueira94 did you end up getting it to work?

**Comment by hardez** [comment]
I'm also having trouble connecting to MongoDB. My Hoster sets up a special instance for every user with an own user pw and port.
So I changed 
```
database:
  uri: mongodb://localhost/letschat
```
 to

```
database:
  uri: mongodb://username:PW@localhost:port/letschat
```

but it allways throws auth problems.
If I start the Mongo instance without authentication and change the setup.yaml to 
```
database:
  uri: mongodb://localhost:port/letschat
```
the connection works. But I really don't want to run a Mongo instance without auth on a shared host.

I also tried to create a new user and password especially for Lets Chat but that also don't worked.
Any ideas?

**Comment by hhaidar** [comment]
@hardez are you able to connect to mongo via command line?

Something like `mongo -u <username> -p <password>`

**Comment by hardez** [comment]
yes, that works perfect. With both users.

**Comment by hardez** [comment]
Ok I tried again, it only works if I connect to the admin DB but even with the mongoadmin user I can't directly connect to the letschat DB. But I can switch to the letschat DB from the mongo cli after I connected to the admin DB.

**Comment by hardez** [comment]
OK, I got the solution.
You have to add ?authSource=admin to the Mongo URI
```
database:
  uri: mongodb://username:PW@localhost:port/letschat?authSource=admin
```

**Comment by hhaidar** [comment]
@hardez ah nice job!
