### ISSUE TITLE
let's chat in subdirectory

### ISSUE THREAD

**Issue by apotry** [sdelements/lets-chat#366]
I'm trying to run Let's chat as part of another website. So far I have only been successful in running Let's chat on http://my-domain.com, but I'd really need it to run in a subdirectory on the server, say http://my-domain.com/chat - how and where can I edit the "base_url" of the site?

**Comment by hhaidar** [comment]
You'll need to proxy behind nginx, apache or some other configuration.

We don't officially support this by the way :(

See: #208 and http://nginx.com/blog/websocket-nginx/ and

**Comment by geoffwhittington** [comment]
Someone has been working with nginx already apparently. Check the mailing list where we discuss deployment issues:

https://groups.google.com/forum/m/#!forum/lets-chat-app

Maybe you can find your answer there?

**Comment by apotry** [comment]
Thanks for the advice - I managed to get this working with nginx, manually redirecting subdirectories to the corresponding paths.

**Comment by geoffwhittington** [comment]
Awesome. Can you post a config that works? I'm sure other people will appreciate it.

Thanks!
