### ISSUE TITLE
Added reset option when adding a room

### ISSUE THREAD

**Issue by fallacy321** [sdelements/lets-chat#373]
Reset option can help the user in case the user accidentally fills the textbox incorrectly.

I have pushed the changes to my forked repo of lets-chat. Let me know if I should merge it yet[1]

Regards

[1]https://github.com/fallacy321/lets-chat/commit/54bafb0e5c6d0c5bbaff164391fa72a891395d33

**Comment by tonghuix** [comment]
I suppose it could replaced by a pic?

**Comment by fallacy321** [comment]
@tonghuix You mean a screenshot, right?

**Comment by fallacy321** [comment]
Attached is the screenshot of reset option
![reset_room](https://cloud.githubusercontent.com/assets/3140219/6806627/d4719222-d26f-11e4-85c9-024e8589a28d.png)

**Comment by tonghuix** [comment]
er...I fount it provide a close [x] button on the top right corner, so that you don't need reset user's config. If some one want to reset, just close that window

**Comment by fallacy321** [comment]
Yeah, that could be the alternative as well. But then one has to close it and again click on + to add the room, using reset one has to click on reset and thats all. But since both are fine, reset seems to be redundant now. Thanks for the suggestion :)

**Comment by funkaoshi** [comment]
Yeah, i'm going to close this. We have our UX person looking at the project in his spare time, so expect UX improvements in the future. The extra button that is likely to be rarely used seems like a distraction.
