### ISSUE TITLE
Long shot: create client for Andoid and iOS

### ISSUE THREAD

**Issue by chiel1980** [sdelements/lets-chat#374]
I know this is not a bug and perhaps a long shot but it would really help to further promote this tool if a client is available for Android and iOS.
All the other slack wannabe's have it and I must say that the browser on my phone is not ideal - it works but logging in does not work 100% => whenever I fill in my credentials and press Login, the screen is enlarged where I pressed and then I have to press login again.
An app which stores some specific settings and have Android/iOS notification would definitely be much more appealing to must people and again; if this should be the BYOS slack killer: all other cloud groupchat apps have an app ;)

**Comment by funkaoshi** [comment]
Someone is actually working on an Android application right now, though it's probably more likely that you would use an existing XMPP / Jabber client to connect to LCB.

**Comment by chiel1980** [comment]
An xmpp client is not the same but I hope a native lets-chat app will arise 
soon.
Can I follow its progress somewhere?

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by funkaoshi** [comment]
@chiel1980 we would love mobile clients as well, but it's basically work someone else can probably do external to us. The APIs to talk to the server are well documented.

**Comment by geoffwhittington** [comment]
Native mobile Lets Chat :+1: 
Someone else writing it :+1: 

@chiel1980 Thanks for the idea - I am going to close this issue (The implementation would have to live in another repo even if we were going to do it anyways)
