### ISSUE TITLE
XMPP not running

### ISSUE THREAD

**Issue by web-vision** [sdelements/lets-chat#376]
Hello,

I'm trying to get XMPP running with let's chat. I am using vagrant on a mac and my settings.yml looks like this:

env: production # development / production

http:
  enable: true
  host: 'localhost'
  port: 5000

https:
  enable: false
  port: 5001
  key: key.pem
  cert: certificate.pem

files:
  enable: true
  provider: local
  local:
    dir: uploads

xmpp:
  enable: true
  host: 'localhost'
  port: 5222

database:
  uri: mongodb://localhost/letschat

secrets:
  cookie: secretsauce

auth:
  providers: [local]
  local:
    enableRegistration: true
    salt: secretsauce # Required when upgrading from version < 0.3

When I'm trying to connect via telnet I get a "connection refused" error:
telnet localhost 5222
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying fe80::1...
telnet: connect to address fe80::1: Connection refused
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.

I've also entered the virtualbox and took at look at the open ports with netstat -tulpn, but it seems that port 5222 isn't even open.

Any hint is welcome.

Best regards,

Boris

**Comment by BorntraegerMarc** [comment]
@borishinzer Mind documenting what you did to make it work?

**Comment by borishinzer** [comment]
@BorntraegerMarc unfortunately I can't remember, since we moved over to Rocket.Chat meanwhile.
