### ISSUE TITLE
Giphy support

### ISSUE THREAD

**Issue by sibartlett** [sdelements/lets-chat#377]
We need the ability to search and send GIFs directly from the web interface.

Giphy has an [API](https://api.giphy.com/).

**Comment by emintham** [comment]
:up: :boat:

**Comment by sibartlett** [comment]
DONE! :tada:

**Comment by hhaidar** [comment]
We don't need this ability.

What have you done...

![image](https://cloud.githubusercontent.com/assets/1066160/6856975/e8c99218-d3d9-11e4-9fb9-26dd3dc6f6f1.png)

**Comment by geoffwhittington** [comment]
@hhaidar see what happens when you give away the keys to the car?

**Comment by funkaoshi** [comment]
This is the worst merge request ever.

**Comment by tatsuhirosatou** [comment]
@sibartlett Is this code implmemented? If it is not merged to the project I would merge it to my own version. It would be great to have this feature.

**Comment by funkaoshi** [comment]
It's in the development branch of Let's Chat.

**Comment by tatsuhirosatou** [comment]
@funkaoshi Is the develop branch usable?

**Comment by funkaoshi** [comment]
That's what we use internally at SD Elements. So it's stable, but we normally recommend people use master for their 'production' set ups.

**Comment by tatsuhirosatou** [comment]
Thank you! I will give it a try then.
