### ISSUE TITLE
Make the login fields - Username/Email and Password as required 

### ISSUE THREAD

**Issue by fallacy321** [sdelements/lets-chat#378]
It would be nice to have the login fields - Username/Email and Password as required for validation. 
Here is my commit for the same [1]. 
Let me know the feedbacks :+1: 

One more doubt I have, to contribute to lets-chat, should I do the pull request directly or raise a issue at first? 

[1]https://github.com/fallacy321/lets-chat/commit/443ba94d4b63ae151cfc1ddae00e919fd8ef0131

![validate](https://cloud.githubusercontent.com/assets/3140219/6854655/9fab2954-d418-11e4-80d8-e569c2176a75.png)

**Comment by hhaidar** [comment]
They're already required via js

**Comment by funkaoshi** [comment]
Seems like there isn't harm also doing it via HTML5?

**Comment by funkaoshi** [comment]
@fallacy321 It's probably fine to open pull requests directly, and we can comment on the code, and accept or reject.

**Comment by fallacy321** [comment]
Thanks @funkaoshi I have already submitted a pull requested :)
