### ISSUE TITLE
Unable to log in to XMPP client with LDAP auth

### ISSUE THREAD

**Issue by necramirez** [sdelements/lets-chat#380]
I'm on latest `master` of both `lets-chat` and `lets-chat-ldap`. This is my XMPP and LDAP config:
```
xmpp:
  enable: true
  debug:
    handled: true
    unhandled: true
  port: 5222
  host: chat.company.com

auth:
  providers: [ldap]
  ldap:
    connect_settings:
      url: ldap://ldap.company.com:389
    bind_options:
      bindDN: <a user's dn>
      bindCredentials: <the user's password>
    search:
      base: ou=something,o=company.com
      opts:
        scope: sub
        filter: (mail={{username}})
    field_mappings:
      uid: uid
      username: shortName
      firstName: givenName
      lastName: sn
      displayName: givenName
      email: mail
```

1. I can login successfully on the web app using my LDAP creds.
2. I try to login using Pidgin with:
    * Protocol:  XMPP
    * Username:  (my uid)
    * Domain:  (same domain as in XMPP config)
    * Port:  5222
    * Connect server:  (same domain as in XMPP config)
3. I get a prompt to Enter password for (uid)@(domain)
4. I enter my LDAP password, but login fails

Nothing appears in the logs, despite setting XMPP debug on. Am I missing anything?

**Comment by sibartlett** [comment]
@necramirez the problem is that the search filter is not compatible with how the XMPP works. Change it to the following:

```
(uid={{username}})
```

This will allow you to:
* login to the web interface using your UID (instead of mail)
* login to XMPP with uid@chat.company.com

**Comment by necramirez** [comment]
That's too bad.  I don't want to use UIDs to login, because our company directory uses serial numbers for UID, it would just feel so unnatural.

Just curious about why "the search filter is not compatible with how the XMPP works":  Does it not support the special characters in an email address ("@", ".")?

**Comment by necramirez** [comment]
Just confirmed it. "@" does not work.

Given the "uid@chat.company.com" format, if I pass use my email address as username, Pidgin itself breaks the "myemail@mycompany.com@chat.company.com" string into:
* username = "myemail"
* domain = "mycompany.com@chat.company.com"

So I tried to URL-encode my email address into "myemail%40mycompany.com", and `passport-ldapauth` simply passes it directly to the LDAP directory. It's `passport-ldapauth` that does not support email addresses as XMPP usernames.

I added this
```
  username = decodeURIComponent(username);
```
at https://github.com/vesse/passport-ldapauth/blob/master/lib/passport-ldapauth/strategy.js#L139 in my local install (`lets-chat/node_modules/lets-chat-ldap/node_modules/passport-ldapauth/lib/passport-ldapauth/strategy.js`) in order to test my hunch, and I can now login via Pidgin!

**Comment by sibartlett** [comment]
@necramirez I think we can come up with a better solution. If I create a branch for this, would you be willing to test it? I think we may be able to have it so you can use your email as your username, but you'll need to specify chat.company.com as the XMPP server.

**Comment by necramirez** [comment]
> but you'll need to specify chat.company.com as the XMPP server.

How is that different from how it is now? :p

But, yeah, I'm willing to test.

**Comment by sibartlett** [comment]
Could you try this branch: https://github.com/sdelements/lets-chat/tree/fix/380_xmpp_email_login

###### Example

If:

* your company's email domain is: @company.com
* your Let's Chat host is: chat@company.com

Configure XMPP like:

```
xmpp:
  username: email
  host: company.com
```

Then, login with:

Username: <user>@company.com
XMPP Server: chat.company.com

**Comment by necramirez** [comment]
I'm testing on my local machine, with this XMPP config:
```
xmpp:
  enable: true
  debug:
    handled: true
    unhandled: true
  port: 5222
  username: email
  host: localhost
```
My Pidgin account setup is, assuming my email is "my_email@my.company.com":
```
* Protocol: XMPP
* Username: my_email # (first part of the email, before "@")
* Domain: my.company.com # (second part of the email, after the "@")
* Connect port: 5222
* Connect server: localhost
```
I can now login!

However, Pidgin is stuck connecting. This also appears in the console log:
```
<iq type="get" id="purplece599842" to="my.company.com" xmlns:stream="http://etherx.jabber.org/streams" from="my_email@my.company.com/b823525be37ade25e472dea3d77c069d"><query xmlns="http://jabber.org/protocol/disco#items"/></iq>
```
I reverted to my hack (with `decodeURIComponent()` in `passport-ldapauth`) and I can login, and get this in the console log:
```
<iq type="get" id="purple50a6b7c1" to="localhost" xmlns:stream="http://etherx.jabber.org/streams" from="nikerwin%40sg.ibm.com@localhost/aa65ac584a2ec8ae92752307d9ab81cc"><query xmlns="http://jabber.org/protocol/disco#items"/></iq>
<iq type="result" id="purple50a6b7c1" to="nikerwin%40sg.ibm.com@localhost/aa65ac584a2ec8ae92752307d9ab81cc" from="localhost"><query xmlns="http://jabber.org/protocol/disco#items"><item jid="conference.localhost" name="Let's Chat Conference Service"/></query></iq>
```
So now I understand when you said, _"you'll need to specify chat.company.com as the XMPP server"_, as that's what's used in `<iq ... to="...">`. I really need my chat server's domain to be the same as the email address' domain. Which won't work for us. :-(

**Comment by sibartlett** [comment]
@necramirez the xmpp.host setting was supposed to be set to your email domain, not localhost. As follows:

```
xmpp:
  enable: true
  debug:
    handled: true
    unhandled: true
  port: 5222
  username: email
  host: my.company.com
```

**Comment by necramirez** [comment]
Just tested that, and it works!  I think this is a useful option.  It'll be safe to merge this, I think.

Though, honestly, it still won't work in our case, since we have geography-based subdomains: user1@us.company.com, then user2@uk.company.com, etc.  That means, I can only configure Let's Chat XMPP for only one country.

In any case, thanks for thinking about this.  :-)

**Comment by sibartlett** [comment]
@necramirez thanks for the update! I won't merge that fix right away, instead I'll take some time to think whether there's a better way to handle your use-case.

**Comment by necramirez** [comment]
IMO, I think that the fix should really be with passport-ldapauth,
especially now that the author is already considering decodeURIComponent as
an option. Once that's actually done there, then lets-chat only needs to
make use of that option.

**Comment by sibartlett** [comment]
@necramirez can you try the latest code again? I think it might work for your scenario - with the multiple email domains. This time I changed the value of xmpp.username should be "full" instead of "email", so your configuration would be like:

```
xmpp:
  enable: true
  debug:
    handled: true
    unhandled: true
  port: 5222
  username: full
  host: my.company.com
```

**Comment by necramirez** [comment]
It works! Yey! :-D

**Comment by necramirez** [comment]
Is there a list of supported XMPP features? I see that sending files is disabled.

**Comment by sibartlett** [comment]
@necramirez yeah, sending files hasn't been implemented yet. It's basically just the ability to join rooms, and send/receive messages.

You can try the develop branch - that has additional XMPP features, including: friends list and 1-to-1 messaging.

**Comment by geoffwhittington** [comment]
@sibartlett do we track the list of XMPP Extension Protocols (XEP) that we support ?

**Comment by sibartlett** [comment]
@geoffwhittington No we don't, that's something we could start doing though. We'd also have to note that we don't support the full specification for each XMPP extension - we support just enough for most/our needs.

**Comment by geoffwhittington** [comment]
Thanks!
