### ISSUE TITLE
porting to angular

### ISSUE THREAD

**Issue by geir54** [sdelements/lets-chat#381]
Any interest in porting the front end to angular? This would make it easier to contribute. I could probably get this work started if there is interest?

**Comment by necramirez** [comment]
I wouldn't want this.

**Comment by geoffwhittington** [comment]
@geir54 I don't understand - what you want to accomplish with a port to angular? The current code works and it would be an epic change - providing us no immediate benefit.

**Comment by geir54** [comment]
I just personally like working with angular and feel it would be easier to contribute new “modular” futures.

**Comment by funkaoshi** [comment]
I don't think we'll ever do this.
