### ISSUE TITLE
Unexpected room change on pressing backspace

### ISSUE THREAD

**Issue by geoffwhittington** [sdelements/lets-chat#385]
When the focus is on a chat message (not the message entry) and backspace is pressed - there is an unexpected room change. I trigger this a few times a day.

This is on develop branch

**Comment by sibartlett** [comment]
Backspace is the browser shortcut for going to the previous page in your history - in this case the previous room you were in. Not sure if we should try overriding the browser's default behaviour?

**Comment by geoffwhittington** [comment]
Ha! yes, you're right. That's annoying.

**Comment by sibartlett** [comment]
Yeah, that shortcut has always bothered me. Maybe no one did UX back when they came up with that!
