### ISSUE TITLE
Sticky Desktop notifications for unmentioned messages

### ISSUE THREAD

**Issue by geoffwhittington** [sdelements/lets-chat#387]
Sometimes I get desktop message notifications that don't go away when I am not mentioned

Branch: develop
Browser: Chrome (Windows)

**Comment by emintham** [comment]
Aha! I thought I was the only one with this problem!

**Comment by hhaidar** [comment]
@emintham ya I knew you weren't crazy all along ;)

**Comment by emintham** [comment]
#overly-attached-bug-reporter

**Comment by funkaoshi** [comment]
I see it too.

**Comment by ajuste** [comment]
I'm having the issue when I get mentioned. Going to give it a check.

**Comment by ajuste** [comment]
Or that's kind of the idea?

**Comment by geoffwhittington** [comment]
Yes when you're mentioned the notifications are meant to be sticky

**Comment by ajuste** [comment]
Got it!

**Comment by ajuste** [comment]
I cannot replicate, is there a specific workflow for this?

**Comment by emintham** [comment]
Seems to happen randomly as far as I can tell...
