### ISSUE TITLE
Where is search

### ISSUE THREAD

**Issue by Veyastar** [sdelements/lets-chat#39]
I do not see search.
Search is needed.

**Comment by geoffwhittington** [comment]
Search what, specifically?

**Comment by hhaidar** [comment]
Transcript search.

**Comment by tejasmanohar** [comment]
:+1:

**Comment by joshwand** [comment]
:+1:

**Comment by lennymora** [comment]
whats  ulp

**Comment by geoffwhittington** [comment]
Are we relying on an update to Mongo for this?

**Comment by sibartlett** [comment]
@geoffwhittington yes, we're going to try Mongo text search, before introducing another dependency.

**Comment by hhaidar** [comment]
@sibarlett how is it going to affect < 2.6?

**Comment by sibartlett** [comment]
@hhaidar we can figure that out when we try it. Maybe there's a way of retrieving the Mongo version from mongoose? Or make search something you have to enable in your config?

**Comment by sibartlett** [comment]
Transcript search has been merged into master.

**Comment by lennymora** [comment]
Hey, can you sign this petition? http://chng.it/G26S9qhk5C

Thanks! - David
