### ISSUE TITLE
Initial MUC presence uses nickname@host instead of username@host for the user who is entering

### ISSUE THREAD

**Issue by dequis** [sdelements/lets-chat#390]
When joining a channel, the client sends a presence message with its desired nickname, and gets back from the server several presence replies, the last of which should contain the JID of the client itself, confirming that the join is complete. However, instead of using a normal `username@host` JID, lets-chat takes the nickname sent by the client and turns it into a (likely to be non-existent) JID `nickname@host`.

Some clients rely on this JID to match their own to successfully join a channel. Bitlbee is one of those, so this is what causes the issue mentioned in https://github.com/sdelements/lets-chat/issues/246#issuecomment-74884954 (hi @geoffwhittington! sorry for the delay!)

-------

Example XMPP dialog, from psi logged in as user `test2@localhost`, with another user in that channel, `dequis@localhost`

Sent from psi, which joins setting itself the nick "this-is-the-nick-not-the-jid"

```xml
<presence to="beep@conference.localhost/this-is-the-nick-not-the-jid">
<priority>5</priority>
<c xmlns="http://jabber.org/protocol/caps" node="http://psi-im.org/caps" ver="caps-b75d8d2b25" ext="cs ep-notify-2 html"/>
<x xmlns="http://jabber.org/protocol/muc"/>
</presence>
```

Received from lets-chat:

```xml
<presence from="beep@conference.localhost/dequis" type="result" to="test2@localhost/bolsa">
<x xmlns="http://jabber.org/protocol/muc#user">
<item affiliation="none" role="participant" jid="dequis@localhost"/>
</x>
</presence>

<presence from="beep@conference.localhost/this-is-the-nick-not-the-jid" type="result" to="test2@localhost/bolsa">
<x xmlns="http://jabber.org/protocol/muc#user">
<item affiliation="none" role="participant" jid="this-is-the-nick-not-the-jid@localhost"/>
</x>
</presence>

<message from="beep@conference.localhost/this-is-the-nick-not-the-jid" type="groupchat" to="test2@localhost/bolsa">
<subject>beep | boop</subject>
</message>
```

In particular:

```xml
<item affiliation="none" role="participant" jid="this-is-the-nick-not-the-jid@localhost"/>
```

Should be 

```xml
<item affiliation="none" role="participant" jid="test2@localhost"/>
```

--------

The commit that broke it is https://github.com/sdelements/lets-chat/commit/4442fb53d88d876ffa23699d05ba6db8429d76c0#diff-660965fd9722eb219bd2c056c39c7a7eR40

And unfortunately it seems to be partially intended behavior for kerberos, but it's wrong. The nickname can be set arbitrarily by the client to any string (even strings that are invalid for that part of the JID) and that doesn't make the client JID any different.

**Comment by sibartlett** [comment]
@dequis can you try the latest code? thanks!

**Comment by dequis** [comment]
Hey! Thanks! It's an improvement - the bug I originally reported is certainly fixed.

However after more testing I found another related issue that was preventing the join from getting detected. You send `<presence type="result" ...>` and we explicitly check for presence stanzas with no type attribute.

(I couldn't figure out where in your code that was getting added, so instead i modified it through gdb and that's all it needed to work, so consider that confirmed)

**Comment by sibartlett** [comment]
@dequis that should also now be fixed!

**Comment by dequis** [comment]
:heart:

It works!

Feel free to close this

**Comment by sibartlett** [comment]
@dequis thanks for reporting the issue and helping debug it :smile:

**Comment by gparent** [comment]
Not sure if related but ever since the fixes for XMPP have been commited to our server, one of the XMPP clients we use is no longer able to join chat rooms (irssi-xmpp).

**Comment by sibartlett** [comment]
@gparent I will investigate when I have some time. Do you mind opening a separate ticket for it though?

**Comment by gparent** [comment]
No worries, we're gathering up info and traces from different clients. I'm the one who originally got this to dequis' attention.
