### ISSUE TITLE
Do you plan to add test to this sweet thing?

### ISSUE THREAD

**Issue by zzz6519003** [sdelements/lets-chat#394]

**Comment by geoffwhittington** [comment]
This is a duplicate of #185 

Do you experience writing tests? We'd love to have you contribute!

**Comment by zzz6519003** [comment]
i'm sorry i haven't have read that!

**Comment by geoffwhittington** [comment]
No worries. Do you want to help write tests?

**Comment by hhaidar** [comment]
![image](https://cloud.githubusercontent.com/assets/1066160/7049770/58bc85ac-ddea-11e4-9348-ba210709d11d.png)

**Comment by geoffwhittington** [comment]
I can't quite make out all the features on that picture @hhaidar  But the tears! I see them

**Comment by zzz6519003** [comment]
i love test! but i think it may be difficult for me to get startedT.T
