### ISSUE TITLE
docker image issue

### ISSUE THREAD

**Issue by chiel1980** [sdelements/lets-chat#395]
Hi,

After the issue found in https://github.com/sdelements/lets-chat/issues/393 I tried to build a new image but get strange behaviour:
I upgrade the image as follows:

- cd /usr/local/lets-chat
- git pull
- docker rm *image/container* # except mongodb
- docker build -t lets-chat .
- docker run -p 5000:5000 --link db:db lets-chat

The app starts fine and has even a socket listening:

[root@server mve]# nc -vv 127.0.0.1 5000
Connection to 127.0.0.1 5000 port [tcp/commplex-main] succeeded!

But as soon as I want to connect to it with curl I get no data back from the container/app:

[root@server mve]# curl http://127.0.0.1:5000
curl: (56) Failure when receiving data from the peer

docker logs *container id* shows that everything is working fine:

> lets-chat@0.3.9 prestart /usr/src/app
> migroose

> lets-chat@0.3.9 start /usr/src/app
> node app.js

██╗     ███████╗████████╗███████╗     ██████╗██╗  ██╗ █████╗ ████████╗
██║     ██╔════╝╚══██╔══╝██╔════╝    ██╔════╝██║  ██║██╔══██╗╚══██╔══╝
██║     █████╗     ██║   ███████╗    ██║     ███████║███████║   ██║
██║     ██╔══╝     ██║   ╚════██║    ██║     ██╔══██║██╔══██║   ██║
███████╗███████╗   ██║   ███████║    ╚██████╗██║  ██║██║  ██║   ██║
╚══════╝╚══════╝   ╚═╝   ╚══════╝     ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝

Release 0.3.9

I use CentOS 6 with or without iptables, disabled SElinux and tailed /var/log/* but see nothing going wrong.

Is there a way I can pinpoint why I am not getting data from the lets-chat container?

**Comment by vwbusguy** [comment]
I can verify that it works on CentOS7.  Does `netstat -plnt` show a listener on 5000?

**Comment by hhaidar** [comment]
@chiel1980 I'm pretty sure it's a host setting issue. Try setting it to blank or `0.0.0.0` (in settings.yml) and see if that helps.

**Comment by chiel1980** [comment]
Very late reply but yes indeed, that was the issue - you should bind lets-chat to 0.0.0.0
