### ISSUE TITLE
Unable to join group chats with irssi-xmpp (maybe recent regression) and bitlbee

### ISSUE THREAD

**Issue by gparent** [sdelements/lets-chat#396]
Hi,

Ever since the last few commits 3 days ago related to XMPP, one of our clients is unable to join the lets-chat server group chats. His client version is irssi-xmpp-0.52p2 on OpenBSD 5.6 with erratas.

The lets-chat server is using the develop branch on commit 868412a85769ff52754b6d547d3cf04179a3c414.

With bitlbee, the recent XMPP fixes stopped the crashes I was seeing on Bitlbee's side. However I am still unable to join group chats.

**Comment by gparent** [comment]
To be explicit, this was uncovered after applying fixes for #390

**Comment by gparent** [comment]
Anything I can do to assist with this? It's pretty serious breakage and I know how to operate gdb, packet captures and everything to make it advance.

**Comment by sibartlett** [comment]
@gparent this has been waiting on me to setup a test environment, so I can install irssi-xmpp.

Can you enable the debug flags in Let's Chat's XMPP settings, and provide us the console output after trying to join a room with irssi-xmpp?

**Comment by martindube** [comment]
Hi guys,

I do not see error messages when I join a room but it tells me the room is empty. Output of "/names" is the following:

13:34 [Users <ROOM_NAME>@conference.<DOMAIN_NAME>]
13:34 -!- Irssi: <ROOM_NAME>@conference.<DOMAIN_NAME>: Total 
          of 0 nicks [0 ops, 0 halfops, 0 voices, 0 normal]

When logging in, messages are as before:

13:54 [hf] -!- Irssi: Looking up <DOMAIN_NAME>
13:54 [hf] -!- Irssi: Connecting to <DOMAIN_NAME>
          [192.168.5.5] port 5222
13:54 [hf] -!- Irssi: Using STARTTLS encryption.         XMPP P
13:54 -!- Irssi: warning SSL (<DOMAIN_NAME>): no 
          certificate found
13:54 -!- Irssi: warning SSL (<DOMAIN_NAME>): certificate 
          hostname does not match expected hostname
13:54 [hf] -!- Irssi: Authenticated successfully. 
13:54 -!- Irssi: critical Source ID 1 was not found when 
          attempting to remove it
13:54 [hf] -!- Irssi: Requesting the roster. 
13:54 [hf] -!- Irssi: Connection to <DOMAIN_NAME> 
          established

**Comment by martindube** [comment]
We also tried the debug mode and no error is displayed.

**Comment by gparent** [comment]
@sibartlett Martin is having trouble with irssi-xmpp, I'm having the same trouble with bitlbee's jabber module. I will report in the same way once I can test with debug enabled, thanks a lot!

**Comment by sibartlett** [comment]
With the XMPP debug flags enabled, Let's Chat will dump all the XMPP messages (sent and received) to the console. Might be a bit noisy if lots of clients connect at the same time.

**Comment by martindube** [comment]
Hi again,

I got a workaround. Actually, I was logging in with the LDAP domain FQDN instead of the server FQDN. When logging in with user@<SERVER_FQDN>, I can join a room. 

Debug output of the erroneous attempt was:

<message type="groupchat" to="<ROOM_NAME>@conference.<SERVER_FQDN>" id="918356929521" xmlns:stream="http://etherx.jabber.org/streams" from="mart@<LDAP_DOMAIN_FQDN>/irssi-xmpp"> <body>hello</body>
</message>

Is it expected behavior to be able to login with something like mart@domain.com instead of mart@xmppsrv.domain.com?

**Comment by martindube** [comment]
Not working message in room:
```
<message type="groupchat" to="ROOM_NAME@conference.<SERVER_FQDN>" id="918356929521" xmlns:stream="http://etherx.jabber.org/streams" from="mart@<DOMAIN_FQDN>/irssi-xmpp"> <body>hello</body>
</message>
```

Working message in room:
```
<message type="groupchat" to="ROOM_NAME@conference.<SERVER_FQDN>" id="656532669049" xmlns:stream="http://etherx.jabber.org/streams" from="mart@<SERVER_FQDN>/irssi-xmpp"> <body>yo</body>
```

Note: SERVER_FQDN is not part of DOMAIN_FQDN. For example: server=xmpp.domain.com, domain=dom.com

**Comment by pathetiq** [comment]
I guess the problem is related to the deprecated function of "host" setting versus the new "domain".

Right now we have the following in the config and the setting "domain" is not set:
```
host: xmpp.domain.com
```

**Comment by sibartlett** [comment]
Ah right! Let's Chat now tolerates users putting any domain in their JID by default - it only uses the node/username part of the JID to authenticate you.

Let's Chat expects you to connect to rooms on the same domain as you've logged into.

If you connect as "mart@<DOMAIN_FQDN>", then Let's Chat expects you to join rooms like so "ROOM_NAME@conference.<DOMAIN_FQDN>".

If you connect as "mart@< SERVER_FQDN>", then it'd be "ROOM_NAME@conference.< SERVER_FQDN >".

**Comment by martindube** [comment]
Ok that explain the behavior. We'll test with bitlbee soon. Thanks!

**Comment by keesj** [comment]
I just updated to the latest version and I used to have a problem when using irssi that the text was not echoed back but for me it all is working now!

**Comment by gparent** [comment]
Okay, seems to be that with the recent fixes, the configuration change, and the patches on bitlbee's side, everything works properly. If you ever need a hand for anything systems related, hit me up, I owe you one. Considering this closed on my end.

**Comment by hhaidar** [comment]
@gparent good to hear!
