### ISSUE TITLE
Private chat

### ISSUE THREAD

**Issue by fellz** [sdelements/lets-chat#397]
What about private chat rooms ? any plans to release that feature ? 
p.s. it's not about 1:1, it's invite only chat n:n

**Comment by geoffwhittington** [comment]
We have some work done with password protected rooms - is that what you mean?

**Comment by fellz** [comment]
any solution would be acceptable i think, so the question when ?

**Comment by geoffwhittington** [comment]
Check the develop branch - we have password protected rooms in there

**Comment by fellz** [comment]
@geoffwhittington I cann't see any changes. How password can be set for the room ?

**Comment by geoffwhittington** [comment]
Try creating a new room - do you see any password fields?

**Comment by fellz** [comment]
no same old stuff - name, description, archive, save

**Comment by geoffwhittington** [comment]
Odd. And you're testing the develop branch?

What am I missing @sibartlett ?

**Comment by sibartlett** [comment]
You need to enable password-protected rooms in the configuration.

```
rooms:
  passwordProtected: true
```

**Comment by fellz** [comment]
exactly, thanks

**Comment by geoffwhittington** [comment]
Thanks @sibartlett

**Comment by fonsich** [comment]
Hi all,

this is not working for me. Im running the dev branch and added the 
rooms:
  passwordProtected: true

But there is no password field

**Comment by geoffwhittington** [comment]
@fonsich are you formatting the settings like they are set above?

**Comment by hhaidar** [comment]
@fonsich silly question, but did you restart the server?

**Comment by fonsich** [comment]
@geoffwhittington yes exactly.

@hhaidar I did

Thanks for your replys

**Comment by iamfiscus** [comment]
Not sure if this thread is still open, but if you look at the default.yml file the private room setting is:
rooms:
  private: false

That seemed to work for me.

**Comment by vwbusguy** [comment]
Yup^^ Working here on the latest release.

**Comment by marcstreeter** [comment]
Can I say that invite rooms would be different than password protected rooms? I'm not sure if I'm not the only one of the culture that "one more password" is annoying (especially when I've already been authenticated).  Is there any movement to have private "invite" rooms where I can just be invited and, upon acceptance, not have to log in again.

**Comment by sibartlett** [comment]
@marcstreeter We have implemented a way to edit the participant list for a private room. It doesn't quite work like invites - as there is no notification or accept/reject workflow. It does allow you to have private rooms that don't require a password though.

**Comment by marcstreeter** [comment]
@sibartlett nice -- I wasn't aware of the feature, that answers my use case completely as I'm not too concerned with the lack of a notification.  Is it implemented in the main branch or elsewhere?

**Comment by hhaidar** [comment]
@marcstreeter develop branch, you'll need to update your settings.yml to enable these features

**Comment by sibartlett** [comment]
@marcstreeter it's currently in the develop branch. There might still be some bugs that we need to fix, but I hope to have it merged into master soon. You create a "private" room, and then you can edit participants using the Edit Room dialog.

**Comment by sibartlett** [comment]
Private rooms have been merged into master.

**Comment by marcstreeter** [comment]
awesome thanks to all who made it possible
