### ISSUE TITLE
Usernames with less than three letters

### ISSUE THREAD

**Issue by maximilian-krauss** [sdelements/lets-chat#405]
Hey,
we use LDAP as auth-provider, our usernames are the first letter from the firstname and the first letter from the lastname (e.g. mk).
The problem is that the the username validation regex requires three or more characters (```/^[^\.][a-z0-9_\.]+[^\.]$/i```).
I changed it locally to ```/^[^\.][a-z0-9_\.]*[^\.]$/i``` and lets-chat works still fine. Is there a reason not to change it and shall I send a pull request?

**Comment by hhaidar** [comment]
Seems fine to me. Might be good to make this configurable though.

**Comment by sibartlett** [comment]
The regex has been updated to require a minimum of 2 characters.
