### ISSUE TITLE
Will it be ok if, we can reduce the number of lines while handling responses to be sent to client.

### ISSUE THREAD

**Issue by nodeofcode** [sdelements/lets-chat#409]
I took lets-chat app as base of examples to built up a npm module `rb` https://github.com/nodeofcode/response-builder#examples

with some key features:

1) Clean and manageable
2) Writing little code
3) logging all the errors automatically, whether on terminal/file
4)  setting up status code for error and success automatically
5) automatically detect 404 cases and sent 404 response in those cases.
6) attaching a unique requestId each time a response a sent. So that it can debuged easily on prod
7) Adding extra fields like, `message` or `status` code automatically while sending response
8) what if we can send the lets-chat version information with each response sent to client. That can have many advantages

many other..

Please look into the above module.
If everything is good with this module and if found at least few positive responses, asking to use `rb` module in `lets-chat` development, then I can sent pull-request(with `rb` used throughout the nodejs code) in next few days.

**Comment by sibartlett** [comment]
Hi,

I took a quick look at your library. I have a couple of reservations:

* Firstly, you may need to modify your library to work with Let's Chat. We use a library called [express.oi](https://github.com/sibartlett/express.io), which means that the express routes serve both socket.io events and HTTP requests. For instance, `util.isValidRequest` would return false for socket.io events.

* Secondly, I feel like some of the examples in the README are less readable than the original code snippets. I also would be a little concerned that this library would make it more challenging for new contributors to Let's Chat.

We are actually considering switching away from express to [hapi.js](http://hapijs.com/). That framework seems to have addressed a lot of express' short-comings, and also addresses a lot of the things you mention in your comment above.

**Comment by hhaidar** [comment]
Closing this for now. Seems like something to contribute to [express.oi] ;D
