### ISSUE TITLE
Mobile Web App for Let's Chat (android/ios)

### ISSUE THREAD

**Issue by JohnTheodore** [sdelements/lets-chat#410]
So if I could use let's chat on my phone, that would be epic. No native code, just a wrapper around webkit. Very similar to how slack does it.

**Comment by tonghuix** [comment]
Hi, it could run in your phone via any browser, please have a try for that

**Comment by geoffwhittington** [comment]
@JohnTheodore Lets Chat is responsive to a mobile interface. Check it out!

If this is a request for a type of phonegap-style app this is a duplicate of #216
