### ISSUE TITLE
Guides to starting this project on AWS?

### ISSUE THREAD

**Issue by doodirock** [sdelements/lets-chat#417]
Hey all, I'm looking for anyone who has deploy lets-chat on a public site via AWS EC2.  Loading up locally is cake.

**Comment by tonghuix** [comment]
I deployed it on a AWS EC2, it is very easy. I suggest you could start from beginning step by step. If you following the wiki, it should give you a clear and easy deployment lets-chat.

**Comment by doodirock** [comment]
I thought so as well :( 

I used an AMI with node and mongo installed on ubuntu but im not really sure how the configuring should go to get it working. Installing local with LC is easy since its all just local host, but setting up the server side of things has been giving me issues.

**Comment by tonghuix** [comment]
What issues you facing?

**Comment by doodirock** [comment]
Sup i first got rid of using the node.js AMI package and went with a clean install of ubuntu 14.  

Installed node, python, and mongo.  

Started up Mongo

In AWS I opened up ports 80, 8080, and 5000

Pulled down lets-chat from the repo

Did npm install and started the app.

copied YML config and changed the port to 8080 but left everything else the same (should I need to do something with mongo, ip, or another else here?)

Port forward 8080 to 80 in Umbutu

Started the app. Nothing....

**Comment by doodirock** [comment]
More info.  My settings file is as follows:

`
env: production # development / production

http:
  enable: true
  host: 'localhost'
  port: 8080

https:
  enable: false
  port: 5001
  key: key.pem
  cert: certificate.pem

files:
  enable: true
  provider: local
  local:
    dir: uploads

xmpp:
  enable: false
  port: 5222
  domain: example.com

database:
  uri: mongodb://localhost/letschat
`
I assume it should be local host?  I set the port to 8080 for now, but tried 5000 in the beginning and that didnt work either.  I figure the issue has something to with my IP as when i run npm start everything starts up fine.

**Comment by hhaidar** [comment]
It's probably only binding to localhost, try making it undefined:

```
http:
  enable: true
  host:
  port: 8080
```

**Comment by doodirock** [comment]
Throws this:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at net.js:1147:9
    at dns.js:72:18
    at process._tickCallback (node.js:448:13)

npm ERR! lets-chat@0.3.10 start: `node app.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the lets-chat@0.3.10 start script.
npm ERR! This is most likely a problem with the lets-chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls lets-chat
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-48-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /home/lets-chat
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! Error: EACCES, open 'npm-debug.log'
npm ERR!  { [Error: EACCES, open 'npm-debug.log'] errno: 3, code: 'EACCES', path: 'npm-debug.log' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.13.0-48-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /home/lets-chat
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! path npm-debug.log
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, open 'npm-debug.log'
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/lets-chat/npm-debug.log
npm ERR! not ok code 0
```

**Comment by doodirock** [comment]
I have no idea what changed cause I didnt touch anything else, but after the reboot it just came up....  I do think leaving it blank was what did it however.  For future reference, what does leaving it blank actually do?

**Comment by hhaidar** [comment]
@doodirock whatever you set in host is what the app will listen on.

If you did `wget http://localhost:8080/` on the server, you would have been able to pull the login page.

Leaving it blank just means bind on everything (0.0.0.0).

**Comment by doodirock** [comment]
Ah, makes sense. Not sure why I couldnt get it to work with just local.  I'll leave it as is for now, thanks!

**Comment by hhaidar** [comment]
np :D
