### ISSUE TITLE
how is the password stored?

### ISSUE THREAD

**Issue by JesusTinoco** [sdelements/lets-chat#424]
Hi, I'm wondering what processes do you apply to the password once entered by the user. I know it's a mix of the salt in the settings file and that it depends of the user's login, and then bcrypted. But I don't know what's exactly the process.

Any help much appreciated.

**Comment by hhaidar** [comment]
The salt in the settings file is to keep older passwords working (version < 0.2).

If a user  has registered or changed their password in 0.3, it's just bycrypt, see https://github.com/sdelements/lets-chat/blob/master/app/models/user.js#L121

**Comment by JesusTinoco** [comment]
Doesn't it depend on the user id or something? I've tried registering several users with same password but different user id and email and the passwords in mongo are diferent.

**Comment by hhaidar** [comment]
@JesusTinoco nope, that's how bcrypt is designed.

If you don't mind me asking, what are you trying to do?

**Comment by geoffwhittington** [comment]
@JesusTinoco We follow best practices and salt and hash the password. I'm closing this issue as we have provided you the answer. Feel free to follow-up to clarify your situation.
