### ISSUE TITLE
Let's chat does not realize when you are logged in from more than one location

### ISSUE THREAD

**Issue by antevens** [sdelements/lets-chat#427]
When logged in from more than one location Let's chat should realize that and not show your own messages to yourself, also if a message notification has been showed to you at one location it should only be shown at the other in realtime and not as a part of a "message log" of notifications from when your machine was hibernated or sleeping.

**Comment by WhiteHatTux** [comment]
I experienced this as well. Sending a message through xmpp to a channel firefox will show me a notification, that i just sent a message. :-)
