### ISSUE TITLE
How to use Authentication API

### ISSUE THREAD

**Issue by malvcr** [sdelements/lets-chat#436]
Thanks for so nice project.  I was able to install it on CentOS 7 and it works well, but I really have no idea how to use the Authentication when using the REST API.

The documentation only indicates that there are tokens and that the token must be used there, but there is no one example about how to combine the authentication and the other methods, even no one about how to authenticate with REST if this is even possible to do.

I was able to call the Login using curl, but although this authenticates me, do nothing about how to send, for example, a message to a room using that authentication is working because there is no indication in the documentation about how to connect the dots.

Thanks

**Comment by tkisme** [comment]
agree,something like curl can help me too

**Comment by geoffwhittington** [comment]
Check out #88 where there is a small example on how to use the Authorization header.

**Comment by malvcr** [comment]
Following the example and with some test and error, I arrived to the following using "curl":

    curl -d @test.txt -X POST -H "Content-Type:application/json" -H "Authorization: Bearer NTU0Z... (truncated)...5OQ==" http://myLetsChatIP:5000/messages

Inside the test.txt file I have the message as:

    {
      "text":"This is an online test",
      "room":"55450d2540c06d790ab906a8"
    }

Without the  -H "Content-Type:application/json" parameter the command doesn't work.

Thanks for the reference

**Comment by geoffwhittington** [comment]
Glad it's working for you!
