### ISSUE TITLE
Official Docker Container

### ISSUE THREAD

**Issue by DoubleMalt** [sdelements/lets-chat#442]
It would be great to have an official docker container, that is automatically built on GitHub changes. That would make it easier for other people to maintain their custom Docker containers or incorporate it in bigger docker-compose collections.

**Comment by geoffwhittington** [comment]
I'm doubtful the team here will be providing this. Feel free anyone else - if people like it we'll make a wiki entry to it

**Comment by DoubleMalt** [comment]
@geoffwhittington: I'm more than willing to create and maintain it. But only someone in the sdelements github organization can set it up, that's enforced by the Docker registry.

**Comment by m4ng0squ4sh** [comment]
Checkout my Docker and Turtle files:
- https://github.com/desertbit/turtle-lets-chat
- https://registry.hub.docker.com/u/desertbit/lets-chat/

The default docker file provided by Let's Chat runs nodejs as root inside the container! This is an improved version with a separate nodejs user and some other useful presets.

**Comment by geoffwhittington** [comment]
That's cool stuff! I'm a Docker noob so I'm not familiar with the requirements or best practices or how to evaluate one Docker file over another.

If people come to a consensus on what file they want to use with some reasoning I'm sure we could help make an official version

**Comment by DoubleMalt** [comment]
a) Running let's chat as non-root user is definitively an improvement.
b) The current possibility to configure everything by environment variables is great for tools like docker -compose. You can setup everything including LDAP configuration with this.
Also the volumes are unnecessary and the git clone can be omitted if it is built directly from the let's chat repo. I will submit a pull request to the current Dockerfile, that starts Let's Chat as non-root user.

**Comment by m4ng0squ4sh** [comment]
@DoubleMalt: The volumes are necessary for the Turtle app management tool. It has an intelligent backup system build in based on BTRFS snapshots. That's why I am using volumes...
I like the idea with the environment variables. I am using them also to setup apps with turtle. However for now I stopped working on the let's-chat app, because some useful tools as a terminal based admin tool, ... are missing.

**Comment by DoubleMalt** [comment]
Now that the docker file is amended to use a non root user and expose the xmpp port, I think it would be a good time to take this up again.

**Benefits**

- Users can easily start and use let's chat without having to clone the repository
- The docker automated build makes it possible to have separate images for each version and/or stable, testing and development branches that are automatically updated when the branch or tag is updated.

**Necessary Steps**

- Create an account on docker registry
- Create an organization
- Connect with Github account
- Create a new automated build 

I'm happy to walk one of the team through it or even set it up myself. For the latter I'd have to have contributor rights to the repository, so I guess, that's not an option.

For now what I do is syncing our fork (https://github.com/cloudfleet/lets-chat) that creates the cloudfleet/letschat docker images.

But this cannot be done automatically.

**Comment by kermit666** [comment]
+1 for an official Docker automated build.

**Comment by geoffwhittington** [comment]
Are the build steps documented somewhere? Sounds pretty straightforward. I can help set it up

**Comment by DoubleMalt** [comment]
That's the official documentation:
http://docs.docker.com/docker-hub/builds/

**Comment by sibartlett** [comment]
I looked into creating an automated Docker build of Let's Chat. The only concern I have is that the README.md in the root of the repository will be used - and our's has lots of information unrelated to Docker. Been trying to figure out if there's a way to use a readme file specific for the Docker build, any ideas?

**Comment by DoubleMalt** [comment]
It would be possible to move the Dockerfile to a subdirectory and add the
nginx files from .. . For that to work it would be necessary to not use the
node onbuild image, but the normal node image and add `RUN npm install` and
`ADD .. /usr/src/app` at the appropriate places in the Dockerfile. Then an
Docker tailored README.md can be placed next to the Dockerfile.

**Comment by sibartlett** [comment]
@DoubleMalt I tried switching away from the onbuild image and putting the Dockerfile in a nested directory yesterday - but I got this error message when trying to build: "Forbidden path outside the build context"

**Comment by sibartlett** [comment]
Ok, so I've been doing some experimentation tonight, and I think I'm getting close to a possible solution :)

**Comment by sibartlett** [comment]
We now have an automated build: https://registry.hub.docker.com/u/sdelements/lets-chat/

**Comment by kermit666** [comment]
Excellent, thanks a lot!
