### ISSUE TITLE
XMPP - Cant see / authenticate Users

### ISSUE THREAD

**Issue by miscs** [sdelements/lets-chat#450]
HI all,

first thank you all for creating lets chat! I just installed Lets Chat (develop) on Ubuntu 14.04 and the Web-GUI works perfekt.

I just have problems with XMPP (using adium client) - I can´t see other logged in users. Is there any configuration for shared roaster? If I create a room (using web gui) I can find the room using the adium discovery browser. Inside the room I see other joined users and the chat works. If I try to add a user as contact it says authorization missing. Re-requesting authorization from user doesn't have any effect.

Am I missing something?
Thank you very much vor your help!
Steve

lets-chat: latest develop (20th of may)
xmpp-configuration:
xmpp:
  enable: true
  roomCreation: true
  debug:
    handled: true
    unhandled: true
  port: 5222
  domain: mail1.sprylab.com
  username: node # node / full
  tls:
    enable: true
    key: ./my.key
    cert: ./my.crt

**Comment by sibartlett** [comment]
You need to add this to your config file:

```
private:
  enable: false
```

It'll enable rosters, but currently will only show those users logged into XMPP at the same time. It won't show web users.

**Comment by miscs** [comment]
Thank you very much! Its working now!

Have a nice weekend :)

**Comment by vwbusguy** [comment]
Is there any equivalent ENV?  I don't see it listed on the wiki, but it would help for our Docker deployment.

**Comment by sibartlett** [comment]
It's on the wiki yet, because this hasn't been merged into master.

`PRIVATE_ROOMS=true`

**Comment by vwbusguy** [comment]
Awesome and thanks!
