### ISSUE TITLE
..how do I upload stuff?

### ISSUE THREAD

**Issue by cathalgarvey** [sdelements/lets-chat#462]
This is either a technical problem (option is missing!) or a UX problem (option isn't obvious!)..I've looked around the UI and can't find any indication for how to upload a locally held file.

My YAML file contains this block:

    files:
      enable: true
      provider: local
      maxFileSize: 50000000
      allowedTypes:
        - 'image/jpeg'
        - 'image/png'
        - 'image/gif'
      local:
        dir: uploads

The UI has no cues here, and dragging files to the post-box just drops the path to the file in as text.

**Comment by hhaidar** [comment]
@cathalgarvey its in the sidebar of the chat window:

![screen shot 2015-05-27 at 10 37 59 am](https://cloud.githubusercontent.com/assets/1066160/7838742/8ccebfb6-045c-11e5-8854-cd0f03724458.png)

**Comment by franciscod** [comment]
Making the files draggable to the text message box would be nice :)

**Comment by hhaidar** [comment]
@franciscod yea, something like how github does it? They are draggable now, but it'll just open up the upload window for you.

**Comment by cathalgarvey** [comment]
Sadly, I do not appear to see any file dialog in my case.
I'm cloning the repo directly and then using `docker-compose up` to fire it up. I have the mongodb docker image running. Account creation and login work fine, creating rooms, gravatar etc., all peachy except that there's no file dialog.

![letschaterr](https://cloud.githubusercontent.com/assets/1167837/7847557/3c41e7de-04bc-11e5-9fb7-6fa2847c265c.png)

**Comment by sibartlett** [comment]
@cathalgarvey did you change the configuration after building the Docker image? It might not have updated the container with your new config.

You could try using environment variables in the docker-compose.yml file. There's a wiki page listing them.

**Comment by sumingyue** [comment]
@sibartlett  I use the latest version under Linux deployed the let - chat program, but after I create room, didn't see the room, on debugging in Firefox, I see the following error:
![qq 20150528091222](https://cloud.githubusercontent.com/assets/12492155/7850821/ae1487c4-0519-11e5-8201-722e81ef93dc.png)

**Comment by sumingyue** [comment]
Hope to receive your reply, thank you

**Comment by sibartlett** [comment]
@sumingyue that's strange! we don't block eval in the CSP configuration.

You're using the master branch? You could try commenting lines 92 -101 in app.js for the time-being.

Also, please don't open new Github issues for problems you have. It's not good to pollute other tickets.

**Comment by sumingyue** [comment]
@cathalgarvey   Thank you, this problem is solved, are still a little difficult for Chinese web developers use of foreign resources, general web site has been sealed off, want to them this class, / (ㄒ o ㄒ) / ~ ~

**Comment by hhaidar** [comment]
@sibartlett might be good to have a flag for helmet

**Comment by cathalgarvey** [comment]
@sibartlett Sorry for the delay: I initially made the mistake of changing settings after composing the docker image, but realised the error and tried again, without solving the problem.

As I write this, I'll repeat the process by `rm -rf`ing the repo and starting anew, documenting exactly the steps I take (the mongodb docker image remains unchanged, could this contribute to the problem somehow?):

    rm -rf lets-chat
    git clone https://github.com/sdelements/lets-chat
    cd lets-chat
    docker-compose up

Output: (wall of text, sorry):

Recreating letschat_db_1...
    Recreating letschat_app_1...
    Attaching to letschat_db_1, letschat_app_1
    db_1  | 2015-05-30T19:27:34.520+0000 I JOURNAL  [initandlisten] journal dir=/data/db/journal
    db_1  | 2015-05-30T19:27:34.521+0000 I JOURNAL  [initandlisten] recover : no journal files present, no recovery needed
    db_1  | 2015-05-30T19:27:34.551+0000 I JOURNAL  [durability] Durability thread started
    db_1  | 2015-05-30T19:27:34.551+0000 I JOURNAL  [journal writer] Journal writer thread started
    db_1  | 2015-05-30T19:27:34.570+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=398decbacd3d
    db_1  | 2015-05-30T19:27:34.570+0000 I CONTROL  [initandlisten] 
    db_1  | 2015-05-30T19:27:34.570+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
    db_1  | 2015-05-30T19:27:34.570+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
    db_1  | 2015-05-30T19:27:34.570+0000 I CONTROL  [initandlisten] 
    db_1  | 2015-05-30T19:27:34.570+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
    db_1  | 2015-05-30T19:27:34.570+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
    db_1  | 2015-05-30T19:27:34.570+0000 I CONTROL  [initandlisten] 
    db_1  | 2015-05-30T19:27:34.570+0000 I CONTROL  [initandlisten] db version v3.0.3
    db_1  | 2015-05-30T19:27:34.570+0000 I CONTROL  [initandlisten] git version: b40106b36eecd1b4407eb1ad1af6bc60593c6105
    db_1  | 2015-05-30T19:27:34.570+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
    db_1  | 2015-05-30T19:27:34.570+0000 I CONTROL  [initandlisten] build info: Linux ip-10-169-193-181 3.2.0-4-amd64 #1 SMP Debian 3.2.46-1 x86_64 BOOST_LIB_VERSION=1_49
    db_1  | 2015-05-30T19:27:34.570+0000 I CONTROL  [initandlisten] allocator: tcmalloc
    db_1  | 2015-05-30T19:27:34.570+0000 I CONTROL  [initandlisten] options: {}
    db_1  | 2015-05-30T19:27:34.817+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
    app_1 | 
    app_1 | > lets-chat@0.3.12 prestart /usr/src/app
    app_1 | > migroose
    app_1 | 
    db_1  | 2015-05-30T19:27:40.077+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.4:36067 #1 (1 connection now open)
    db_1  | 2015-05-30T19:27:40.079+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.4:36068 #2 (2 connections now open)
    db_1  | 2015-05-30T19:27:40.079+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.4:36069 #3 (3 connections now open)
    db_1  | 2015-05-30T19:27:40.080+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.4:36070 #4 (4 connections now open)
    db_1  | 2015-05-30T19:27:40.080+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.4:36071 #5 (5 connections now open)
    app_1 | 
    app_1 | > lets-chat@0.3.12 start /usr/src/app
    app_1 | > node app.js
    app_1 | 
    db_1  | 2015-05-30T19:27:40.124+0000 I NETWORK  [conn4] end connection 172.17.0.4:36070 (4 connections now open)
    db_1  | 2015-05-30T19:27:40.124+0000 I NETWORK  [conn5] end connection 172.17.0.4:36071 (4 connections now open)
    db_1  | 2015-05-30T19:27:40.124+0000 I NETWORK  [conn1] end connection 172.17.0.4:36067 (4 connections now open)
    db_1  | 2015-05-30T19:27:40.124+0000 I NETWORK  [conn2] end connection 172.17.0.4:36068 (4 connections now open)
    db_1  | 2015-05-30T19:27:40.124+0000 I NETWORK  [conn3] end connection 172.17.0.4:36069 (4 connections now open)
    db_1  | 2015-05-30T19:27:42.367+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.4:36072 #6 (1 connection now open)
    db_1  | 2015-05-30T19:27:42.369+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.4:36073 #7 (2 connections now open)
    db_1  | 2015-05-30T19:27:42.370+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.4:36074 #8 (3 connections now open)
    db_1  | 2015-05-30T19:27:42.378+0000 I NETWORK  [conn7] end connection 172.17.0.4:36073 (2 connections now open)
    db_1  | 2015-05-30T19:27:42.382+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.4:36075 #9 (3 connections now open)
    db_1  | 2015-05-30T19:27:42.382+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.4:36076 #10 (4 connections now open)
    db_1  | 2015-05-30T19:27:42.384+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.4:36077 #11 (5 connections now open)
    db_1  | 2015-05-30T19:27:42.385+0000 I NETWORK  [conn10] end connection 172.17.0.4:36076 (4 connections now open)
    db_1  | 2015-05-30T19:27:42.388+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.4:36078 #12 (5 connections now open)
    db_1  | 2015-05-30T19:27:42.389+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.4:36079 #13 (6 connections now open)
    db_1  | 2015-05-30T19:27:42.393+0000 I NETWORK  [conn13] end connection 172.17.0.4:36079 (5 connections now open)
    db_1  | 2015-05-30T19:27:42.410+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.4:36080 #14 (6 connections now open)
    db_1  | 2015-05-30T19:27:42.415+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.4:36081 #15 (7 connections now open)
    db_1  | 2015-05-30T19:27:42.416+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.4:36082 #16 (8 connections now open)
    db_1  | 2015-05-30T19:27:42.416+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.4:36083 #17 (9 connections now open)
    db_1  | 2015-05-30T19:27:42.416+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.4:36084 #18 (10 connections now open)
    app_1 | 
    app_1 | ██╗     ███████╗████████╗███████╗     ██████╗██╗  ██╗ █████╗ ████████╗
    app_1 | ██║     ██╔════╝╚══██╔══╝██╔════╝    ██╔════╝██║  ██║██╔══██╗╚══██╔══╝
    app_1 | ██║     █████╗     ██║   ███████╗    ██║     ███████║███████║   ██║   
    app_1 | ██║     ██╔══╝     ██║   ╚════██║    ██║     ██╔══██║██╔══██║   ██║   
    app_1 | ███████╗███████╗   ██║   ███████║    ╚██████╗██║  ██║██║  ██║   ██║   
    app_1 | ╚══════╝╚══════╝   ╚═╝   ╚══════╝     ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝
    app_1 | 
    app_1 | Release 0.3.12
    app_1 | 

I go to localhost:5000 and my session is still active as I never closed the browser, and data is presumably stored in mongodb. Still no sign of the file upload dialog.

Could this be a database bug? I'll try to delete and reinstall the mongodb container.

**Comment by cathalgarvey** [comment]
OK, just deleted *all images and containers from docker*, then following the docker install instructions for lets-chat again (after wiping and re-cloning the repo again as above). This should be a *clean slate*, so let's see if something mysterious starts working or if I get the same results!

    docker pull mongo  # I realised too late that docker-compose would do this, but meh
    git clone https://github.com/sdelements/lets-chat
    cd lets-chat
    docker-compose up

Results: Nope. Still no file dialog/pane. I'd post a screenshot but it's identical to the one I already posted.

I *just* pulled from github, so this is me with commit 6a6906e297 on Arch Linux with Firefox 38.0.1

**Comment by hhaidar** [comment]
@cathalgarvey 

```
cp settings.yml.sample settings.yml
docker-compose kill
docker-compose build
docker-compose up
```

**Comment by cathalgarvey** [comment]
I tried rebuilding exactly as you indicated, and it launches successfully but browsers and curl/wget totally fail to connect; instant `connection reset` errors.

Worse, if I rebuild without the `settings.yml` now, it *still* doesn't work. :(

I love the project, I really want to see a Slacklike without the closed-source, centralised crap, but this is proving kinda torturous!

**Comment by hhaidar** [comment]
@cathalgarvey ah, forgot to mention, set host under `http` to blank in `settings.yml` and then try rebuilding + running.

I know things have been a bit bumpy, sorry about that. I'll try to help out however I can until things work :)

**Comment by cathalgarvey** [comment]
Success! Thank you for the help.

So, the wiki needs updating to make this clear; the defaults, in the absence of the sample `settings.yml`, are *not* to support file upload. Further, to use the sample settings.yml on localhost, you have to remove the 'localhost' bit under `host`. Why is that there if it clearly is intended for localhost, but breaks localhost? Is it a docker thing, that it needs to be blank so the docker image recognises host OS connections? That needs to be in the docker instructions..

I love this project, thank you for making it.

**Comment by sibartlett** [comment]
@cathalgarvey I've updated the Dockerfile to explicitly override the `host` setting in settings.yml

**Comment by cathalgarvey** [comment]
Thank you! And thanks to your patience, I'm up and running and have written a [Python API wrapper](https://github.com/cathalgarvey/python-letschat). Fun things ahead! :)
