### ISSUE TITLE
Chinese localization package

### ISSUE THREAD

**Issue by sumingyue** [sdelements/lets-chat#466]
Did the let - chat program for Chinese localization package
Developers in China.

**Comment by tonghuix** [comment]
I am expecting too!
Same from China.

**Comment by hhaidar** [comment]
@sumingyue @tonghuix is this something you guys can look at then?

**Comment by tonghuix** [comment]
I could help for translating

**Comment by funkaoshi** [comment]
Anyone have any experience actually trying to localize a Node app? It'd be amazing to do, but probably a lot of work.

**Comment by sumingyue** [comment]
@hhaidar Thanks

**Comment by hhaidar** [comment]
@sumingyue no problem :)
