### ISSUE TITLE
Clang error unknown argument 'fno-tree-vrp'

### ISSUE THREAD

**Issue by Free16t** [sdelements/lets-chat#467]
Hi,

I'm currently facing an issue during the `npm install`
Here is the log (ubuntu 14.04, `node -v` = v.0.10.25, `npm -v` = 1.3.10):

>make: Entering directory `/opt/lets-chat/node_modules/node-xmpp-core/node_modules/ltx/node_modules/node-expat/node_modules/iconv/build'
  CC(target) Release/obj.target/libiconv/deps/libiconv/lib/iconv.o
clang: error: unknown argument: '-fno-tree-vrp'
make: *** [Release/obj.target/libiconv/deps/libiconv/lib/iconv.o] Error 1
make: Leaving directory `/opt/lets-chat/node_modules/node-xmpp-core/node_modules/ltx/node_modules/node-expat/node_modules/iconv/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.16.0-30-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /opt/lets-chat/node_modules/node-xmpp-core/node_modules/ltx/node_modules/node-expat/node_modules/iconv
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
npm ERR! weird error 1
  SOLINK_MODULE(target) Release/obj.target/bson.node
  SOLINK_MODULE(target) Release/obj.target/bson.node: Finished
  COPY Release/bson.node
make: Leaving directory `/opt/lets-chat/node_modules/mongoose/node_modules/mongodb/node_modules/bson/build'

What can I do?

**Comment by hhaidar** [comment]
@Free16t http://stackoverflow.com/questions/21168141/can-not-install-packages-using-node-package-manager-in-ubuntu

Also might be good to upgrade npm to version 2+

**Comment by Free16t** [comment]
I will see to upgrade. 
I have already nodejs-legacy install and node / nodejs in /usr/bin

**Comment by hhaidar** [comment]
@Free16t cool, let us know what happens
