### ISSUE TITLE
IE8 & IE 9 does not support Lets-Chat

### ISSUE THREAD

**Issue by yasirrose** [sdelements/lets-chat#468]
Can any one help me about this chat system. It does not work in IE8 and IE9, Actually I am going to build chat system for specific business type people, And 30% of our clients still using window XP OS, that's why I need help to make this Chat system perfect in IE8 and IE9.

Looking for solution..

Thanks in advance..

**Comment by sibartlett** [comment]
Let's Chat probably won't ever support IE8 or IE9 - we make extensive use of CSS flexbox: http://caniuse.com/#feat=flexbox

**Comment by yasirrose** [comment]
Thanks for reply !!
1-But in my case I face fallowing error during signin on IE8 Browser

![issue_ie](https://cloud.githubusercontent.com/assets/5586359/7890620/d828afa8-05fb-11e5-8787-53b9d5f0bed6.jpg) 

2-I think socket.io not support in IE 8.
3-Css issue is an other thing let me explain when i sign in on chat project it redirect me to dashboard and following screen is showing to me 

![dashboard](https://cloud.githubusercontent.com/assets/5586359/7890708/7c159e14-05fc-11e5-8054-a23b9941e708.jpg)

Please suggest me a better solution.

**Comment by franciscod** [comment]
...install a modern browser?

**Comment by funkaoshi** [comment]
@yasirrose As Simon mentioned to start, we don't support IE8 or 9. Sorry.
