### ISSUE TITLE
How to edit a less file without needing to restart app?

### ISSUE THREAD

**Issue by j-mcnally** [sdelements/lets-chat#472]
Everytime i edit a less file i have to restart the server for it compile. Is there a way to have it compile everyime?

**Comment by mpartipilo** [comment]
LESS is meant to compile to CSS.  You can't really expect to skip that step.

Using something like nodemon could help. It will restart the server automatically when it detects that a file has changed.

Installation is as simple as "npm -g install nodemon". You might need to use "sudo".

There might be another way but I'd need to look into it before recommending it. Just let me know if nodemon is not enough for you and I'll look into it

**Comment by j-mcnally** [comment]
Yea sorry maybe i didn't describe my problem correctly. I know LESS needs to compile. The issue is it isnt re-compiling when I edit a file. Was asking more if there is a setting or something I can install to have it re-compile on change.

**Comment by sibartlett** [comment]
@j-mcnally sorry, I don't think there is a setting to have it re-compile on change. We use the [connect-assets middleware](https://github.com/adunkman/connect-assets) to serve the less and js files, and i don't think that provides an options. This really bugs us too - so we'll probably be looking into switching to another middleware.

**Comment by j-mcnally** [comment]
@sibartlett  thanks, im not complaining it doesn't exist, just wanted to make sure I wasn't missing something :)

**Comment by hhaidar** [comment]
@j-mcnally yea it kinda sucks, I usually run nodemon locally and have it reset on less changes. It's not ideal, but it works okay.
