### ISSUE TITLE
Error:Cannot find module 'i18n'

### ISSUE THREAD

**Issue by sumingyue** [sdelements/lets-chat#476]
What do I need to npm install.....?

**Comment by sumingyue** [comment]
I used:npm install i18n-node,but incorrect

**Comment by sibartlett** [comment]
You only need to run `npm install` - NPM will install the correct i18n package for you.

**Comment by hhaidar** [comment]
@sumingyue the module is called just `i18n`, so `npm install i18n` should do it.

But yea, if you just run `npm install`, it'll grab all the dependencies it needs.

**Comment by sumingyue** [comment]
@sibartlett @hhaidar thanks

**Comment by shaitand** [comment]
@sibartlett I've yet to ever see running npm install grab all the dependencies. According to my command history this is what I had to run on a clean CENTOS 7.3 after running a yum -y update, adding the mogodb-org community repo/starting it, adding EPEL, then `yum -y install nodejs npm git` and cloning the project.

npm install colors
npm install lodash
npm install express.oi
npm install i18n
npm install body-parser
npm install cookie-parser
npm install compression
npm install helmet
npm install nunjucks
npm install mongoose
npm install connect-mongo
npm install require-tree
npm install js-yaml
npm install async
npm install passport
npm install passport.socketio
npm install passport-http-bearer
npm install passport-http
npm install uuid
npm install require-directory
npm install mongoose-unique-validator
npm install bcryptjs
npm install md5
npm install node_hash
npm install mongoose-validate
npm install on-finished
npm install multer
npm install passport-local
npm install connect-assets
npm install less

This was from a series of errors after successful npm install attempting to npm start except for 'less' which it complained about after indicating successful start. This is the 3rd or 4th project I've installed that uses nodejs and npm, sometimes on centos sometimes Ubuntu, I've never yet seen npm install actually install all the dependencies. Hopefully nothing else pops up in operation.

**Comment by Helen267** [comment]
Hi, I am facing an issue when I run jest tests, getting the below error.
 **Cannot find module '@/localization/i18n.js' from 'src/components/abc.js'**

When I comment on the localization lines in the .js file and then run tests. it is working fine. 
But I want to display the messages also in my tests.

Please help!
