### ISSUE TITLE
docker image broken after 0.4.0 upgrade?

### ISSUE THREAD

**Issue by chiel1980** [sdelements/lets-chat#478]
Hi,

It seems the docker build does not work anymore, or at least I only see the following:

letschat_1 |
letschat_1 | > lets-chat@0.4.0 prestart /usr/src/app
letschat_1 | > migroose
letschat_1 |

I removed all images, containers and even the git clone and cloned a new one but I get the same behaviour.
Also, I see the options in the default.yml where we can enable passworded rooms but is there some documentation of how this has to be set and should it be set in the settings.yml ?

Cheers,

Michiel

**Comment by sibartlett** [comment]
What happens if you restart the Docker container? I'll take a look into soon too.

Also, we'll update the docs with all the new settings.

**Comment by chiel1980** [comment]
A restart after git pull seem to work but I wanted to build a clean new
image and container and restore the mongo backup.
Op 4 jun. 2015 23:14 schreef "Simon Bartlett" <notifications@github.com>:

**Comment by loyalj** [comment]
I'm experiencing the same issue with lets-chat in docker

    lets-chat$ docker run -p 5000:5000 --link db:db lets-chat
    > lets-chat@0.4.0 prestart /usr/src/app
    > migroose

I've tried restarting the container as well as removing it.and rebuilding.  Nothing seems to unjam the issue.

**Comment by sibartlett** [comment]
This should now be fixed, please pull the latest code and try again.

Seems to have been caused by a bug in the migroose library.

**Comment by chiel1980** [comment]
It works!

Stupid question: how do I enable the passworded rooms feature (is it an on/off switch or is it choosable when creating a new room?).
And the same for the 1:1 chat?

I do see it available in the default.ml, should I overwrite it in the settings.yml?

Michiel

**Comment by chiel1980** [comment]
Ok, added it to the settings.yml and it works for passworded rooms nice :+1:

**Comment by chiel1980** [comment]
Will close the issue.
