### ISSUE TITLE
text entry window cut off

### ISSUE THREAD

**Issue by kermit666** [sdelements/lets-chat#481]
This is what the text entry looks like for me. The CSS seems to be messed up.

![screenshot 2015-06-06 00 50 50](https://cloud.githubusercontent.com/assets/1818628/8016653/a6f091f8-0be6-11e5-81cb-47f038947ba6.png)

This is the very bottom of the window and I can't scroll down any further. Appears in Chrome - not on all channels, but on those where there is lots of text pasted in with some code examples etc.

**Comment by hhaidar** [comment]
@kermit666 try updating to 0.4

**Comment by kermit666** [comment]
Worked, thanks!
