### ISSUE TITLE
Print chat history

### ISSUE THREAD

**Issue by mmeinert** [sdelements/lets-chat#487]
Selecting all the transcript and print will result on only the first page printed (all common browsers are impacted).

Not sure at all but this may be related to [onbeforeprint event](https://msdn.microsoft.com/en-us/library/ms536906(v=vs.85).aspx) and [onafterprint event](https://msdn.microsoft.com/en-us/library/ms536788(v=vs.85).aspx)

I hesitated to put this issue with #485. Finally I thought this was not directly related but the solution of exporting to a file workarounds the problem.

Thank you

**Comment by hhaidar** [comment]
I'm pretty sure its a CSS issue. The message list can be made to not be contained for print.

**Comment by mmeinert** [comment]
Maybe the use of [CSS Print Media Query] will help(http://www.joshuawinn.com/css-print-media-query/) ?
Even [html2canvas](https://github.com/niklasvh/html2canvas) looks promising.
I (we) can try it.
