### ISSUE TITLE
Embed chat widget on a web page

### ISSUE THREAD

**Issue by openstepmedia** [sdelements/lets-chat#495]
Is there a way to embed lets-chat into a website - take a look at : spot.im

Even just iframe it?

**Comment by Fibrewire** [comment]
I have done this successfully with an iframe by adding

app.use(function(req,res,next) {

    res.setHeader('X-Frame-Options','ALLOW-FROM <your FGDN HERE>');

    next();

});

to app.js

and then altering document.domain to remove the port number

https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy
