### ISSUE TITLE
Multiple occurrences of messages from XMPP users

### ISSUE THREAD

**Issue by mmeinert** [sdelements/lets-chat#497]
As seen on the screenshot below, I encounter a problem when sending a message from a XMPP client. No problem to receive...  

![screenshot_2015-06-11-13-31-28 1](https://cloud.githubusercontent.com/assets/2050640/8106071/a0d0afd6-103e-11e5-90c9-498977168503.png)

![chat](https://cloud.githubusercontent.com/assets/2050640/8106229/b99d497e-103f-11e5-9bae-8d5f68e4a201.png)

Where is the bug ?

Thank you

**Comment by sibartlett** [comment]
Is that the Conversations app? We've had the same problem with that client. We're planning to debug it soon.

**Comment by hhaidar** [comment]
cc @kevindelaney

**Comment by mmeinert** [comment]
Yes, I confirm it's Conversations. I'll try Xabber which is referenced in the wiki. 
Thank you in advance for debbuging Conversations :+1:

**Comment by sibartlett** [comment]
This is now fixed in the latest code! :tada:

**Comment by mmeinert** [comment]
great ! Thank you
