### ISSUE TITLE
vCard requests from XMPP clients kill node 

### ISSUE THREAD

**Issue by 8bitjeremy** [sdelements/lets-chat#501]
vCard requests from XMPP clients kill node with the following:

/home/imnotbob/lets-chat/app/xmpp/msg-processors/vcard-get.js:30
                this.sendVcard(user, cb);
                     ^
TypeError: Cannot call method 'sendVcard' of undefined
    at /home/imnotbob/lets-chat/app/xmpp/msg-processors/vcard-get.js:30:22
    at /home/imnotbob/lets-chat/node_modules/mongoose/lib/query.js:1173:16
    at /home/imnotbob/lets-chat/node_modules/mongoose/node_modules/kareem/index.js:109:16
    at process._tickCallback (node.js:448:13)
node fails when vcards are accessed

is this a node-xmpp issue?

The client is xabber on android.  You can turn off vcard requests in the android app  settings, but it is on by default.  So if a new user tries to set up chat on their device they kill the server once they login.

**Comment by sibartlett** [comment]
This bug should now be fixed. If you're using our Docker image, the next build will be available shortly.

**Comment by 8bitjeremy** [comment]
Great! Thanks!

-- 
No trees were killed to send this message, but a large number of electrons
were terribly inconvenienced.
