### ISSUE TITLE
Text Entry Layout Broken on Chromium/Chrome 43 

### ISSUE THREAD

**Issue by treeves** [sdelements/lets-chat#504]
An issue has cropped up for our users of Chrome 43 (or Opera using Chromium 43) that is not extant on Chrome 42, whereby the text entry area is pushed down to nearly below the bottom of the page.   

Chrome 43:
![screen shot 2015-06-12 at 2 05 49 pm](https://cloud.githubusercontent.com/assets/1467135/8139945/815d962c-110c-11e5-9edb-77550e1e7b2e.png)

Chrome 42:
![screen shot 2015-06-12 at 2 06 30 pm](https://cloud.githubusercontent.com/assets/1467135/8139951/8de13548-110c-11e5-8fc0-a7f55a524ae1.png)

Additionally, it seems to break the chat history CSS.   I'm using 0.3, but didn't see anything in the .4 release that would have addressed this.    Anyone else having issues with such?

**Comment by sibartlett** [comment]
This has been fixed in the latest release of Let's Chat. Could you try updating?

**Comment by sibartlett** [comment]
I just checked CHANGELOG.md - it was fixed in 0.3.13.

**Comment by hhaidar** [comment]
@treeves ya just upgrade and it should be good to go. 0.3 -> 0.4 shouldn't be pretty easy to get going

**Comment by treeves** [comment]
@hhaidar / @sibartlett Thanks a bunch guys.  I didn't see that release note (was just trawling through commit messages).  Installed 0.4 & migrated my settings back over and it appears all fixed!   And the team likes the Giphy addition too.  Oh the things it will do for our productivity.  :)

**Comment by hhaidar** [comment]
@treeves hah good to hear!
