### ISSUE TITLE
Time is not updated on each message 

### ISSUE THREAD

**Issue by mmeinert** [sdelements/lets-chat#506]
Timestamp is not updated on each message, only when another says something.
So, if I'm alone typing text from 11AM to 11PM, one message every 5 minutes, all my messages will be displayed as sent on 11AM.

Timestamp should be updated if the previous message of the user is > 59 sec if no one says anything during this interval.

Big problem to me

Thank you

**Comment by mmeinert** [comment]
![today_chat](https://cloud.githubusercontent.com/assets/2050640/8278551/b729727c-18cc-11e5-93b2-e341991321e3.png)

If you don't think it's an issue (I personally do), could you please show me where and what to change to have one new message with his timestamp everytime a post is sended even by the same user ?

Solving this will help for #513 

Thank you

PS : Yes, it's in french, I'm trying to find my way for #493

**Comment by hhaidar** [comment]
@mmeinert @sibartlett just showed me his pretty elegant solution for this (grouping messages in 5 minute intervals). Should be up in a few.

@mmeinert complete i18n is coming! I'll bug you to help update the french pack :P

**Comment by sibartlett** [comment]
@mmeinert I've pushed a change which hopefully improves things: 1d647e6fc302cdcd34f66a6444a9ffd6d231b040

Also, sorry for the delay - both myself and @hhaidar were unavailable, attending a conference.

**Comment by mmeinert** [comment]
@sibartlett That's much better, thank you

Don't be sorry, you rocks ;)
