### ISSUE TITLE
Portuguese translation of locales/en.json

### ISSUE THREAD

**Issue by marcusmonteiro** [sdelements/lets-chat#512]
Hey guys,

I'm adapting your application to use it as an internal chat at my company. I've made a portuguese translation of locales/en.json, named pt.json. Are you interested? Can I submit a pull request? It's my first time contributing to an open source project. I'm also translating the entire application as it is as a next step for my adaptation, before I go into things specific to my company. If you're interested, I can submit that pull request as well.

**Comment by marcusmonteiro** [comment]
I could possibly go a step further and translate the entire application if you're interested.

**Comment by hhaidar** [comment]
@marcusmonteiro yup, that'd be awesome, please go ahead!

If you don't mind me asking, is there a difference between Brazilian and European Portuguese?

**Comment by marcusmonteiro** [comment]
Written, not too much, except for a few words, mostly slangs. Spoken, well, I understand English speakers easier than Portuguese :D. As translation is concerned though, Brazil usually adopts foreign words as they are, whereas Portuguese tend to translate them. In my translation, words such as "tokens" and "chat" will be left in English because Brazilians use them.

**Comment by hhaidar** [comment]
@marcusmonteiro hah cool, good to know! thanks :D

I'm closing this, please open a PR when you have a chance.
