### ISSUE TITLE
not able to login

### ISSUE THREAD

**Issue by ashwin31** [sdelements/lets-chat#536]
i have installed lets-chat to heroku by the heroku deploy button in http://sdelements.github.io/lets-chat/

i am not able to login as admin with admin / admin

how can i manage the installation as admin?

**Comment by hhaidar** [comment]
@ashwin31 there is no admin user or ACL at the moment.

**Comment by ashwin31** [comment]
@hhaidar I wanted to create chat for my organization and now I see that its not for organisations where we need to control users and monitor activity.

Are you planning to integrate ACL and admin control etc.

**Comment by hhaidar** [comment]
@ashwin31 probably not for a while. If you need ACL now I suggest using the ldap/kerberos auth plugins.
