### ISSUE TITLE
Add "Conversations" Android app to xmpp wiki

### ISSUE THREAD

**Issue by bufke** [sdelements/lets-chat#542]
I would submit a pull but github doesn't let you on the [wiki](https://github.com/sdelements/lets-chat/wiki/XMPP#android).

https://github.com/siacs/Conversations

It's open source and IMO the best android XMPP app. I had to work with the developer (who kindly spent some time debugging my issue) for it to work but the stable release works out of box with let's chat.

**Comment by hhaidar** [comment]
Done!

Conversations is amazing <3
