### ISSUE TITLE
Make Giphy support optional/configurable

### ISSUE THREAD

**Issue by oerdnj** [sdelements/lets-chat#544]
Would it be possible to have a configuration option to disable Giphy? And/or an options to not animate the GIFs by default. Pretty please.

**Comment by ibiBgOR** [comment]
:+1: We are faceing the exact same problem in out team.

**Comment by frob** [comment]
Can you change the setting on a per room basis. It would be nice to have a couple of gif free rooms.
I am sure a few of my users would prefer to not load gifs in the user prefs too.

**Comment by sibartlett** [comment]
We're going to make Giphy globally configurable for the time-being. We are considering making it configurable on a per-room basis though.

**Comment by sibartlett** [comment]
Giphy is now globally configurable with the following options:

```
giphy:
  enable: true
  rating: pg-13
  limit: 24
  apiKey: dc6zaTOxFJmzC
```
