### ISSUE TITLE
Show Let's Chat version

### ISSUE THREAD

**Issue by nicolas-raoul** [sdelements/lets-chat#546]
How can a user tell what version of Let's Chat they are using?

This might be needed when troubleshooting or discussing on general help forums.

**Comment by hhaidar** [comment]
Like an end-point or in the UI?

We already print the version on startup. Also this doesn't help much if you're running on master.

**Comment by nicolas-raoul** [comment]
I meant in the UI.
Most self-hosted webapps have a fineprint or menu item stating the version.
It could be at the bottom of Account Settings for instance, or any better place.

**Comment by hhaidar** [comment]
Should show up in the bottom right now:

![screen shot 2015-07-14 at 2 03 30 pm](https://cloud.githubusercontent.com/assets/1066160/8680714/216d6cfe-2a31-11e5-8e19-5e7cef8520cc.png)
