### ISSUE TITLE
Standard install process works start fails

### ISSUE THREAD

**Issue by corn13read** [sdelements/lets-chat#560]
npm start

> lets-chat@0.4.2 prestart /usr/src/app/lets-chat
> migroose

> lets-chat@0.4.2 start /usr/src/app/lets-chat
> node app.js

██╗     ███████╗████████╗███████╗     ██████╗██╗  ██╗ █████╗ ████████╗
██║     ██╔════╝╚══██╔══╝██╔════╝    ██╔════╝██║  ██║██╔══██╗╚══██╔══╝
██║     █████╗     ██║   ███████╗    ██║     ███████║███████║   ██║   
██║     ██╔══╝     ██║   ╚════██║    ██║     ██╔══██║██╔══██║   ██║   
███████╗███████╗   ██║   ███████║    ╚██████╗██║  ██║██║  ██║   ██║   
╚══════╝╚══════╝   ╚═╝   ╚══════╝     ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝

Release 0.4.2

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EAFNOSUPPORT
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1139:19)
    at listen (net.js:1182:10)
    at net.js:1280:9
    at dns.js:85:18
    at process._tickCallback (node.js:355:11)

npm ERR! Linux 2.6.32-504.16.2.el6.x86_64
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! lets-chat@0.4.2 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lets-chat@0.4.2 start script 'node app.js'.
npm ERR! This is most likely a problem with the lets-chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls lets-chat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/lets-chat/npm-debug.log

cat  /usr/src/app/lets-chat/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart lets-chat@0.4.2
6 verbose unsafe-perm in lifecycle true
7 info start lets-chat@0.4.2
8 verbose unsafe-perm in lifecycle true
9 info lets-chat@0.4.2 Failed to exec start script
10 verbose stack Error: lets-chat@0.4.2 start: `node app.js`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid lets-chat@0.4.2
12 verbose cwd /usr/src/app/lets-chat
13 error Linux 2.6.32-504.16.2.el6.x86_64
14 error argv "node" "/usr/local/bin/npm" "start"
15 error node v0.12.7
16 error npm  v2.11.3
17 error code ELIFECYCLE
18 error lets-chat@0.4.2 start: `node app.js`
18 error Exit status 1
19 error Failed at the lets-chat@0.4.2 start script 'node app.js'.
19 error This is most likely a problem with the lets-chat package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     node app.js
19 error You can get their info via:
19 error     npm owner ls lets-chat
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

**Comment by hhaidar** [comment]
Try turning on ipv6

Probably a similar issue to:

* https://github.com/joyent/node/issues/7983
* https://github.com/Jalle19/node-ffmpeg-mpegts-proxy/issues/5
* https://github.com/tapchat/tapchat/issues/32

**Comment by hhaidar** [comment]
@corn13read did you end up getting it to work?

**Comment by EvilBMP** [comment]
I have something similar...

```
npm start

> lets-chat@0.4.2 prestart /home/portrinochat/private/lets-chat
> migroose


> lets-chat@0.4.2 start /home/portrinochat/private/lets-chat
> node app.js

fs.js:761
  return binding.readdir(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript/app/models'
    at Error (native)
    at Object.fs.readdirSync (fs.js:761:18)
    at require_tree (/home/portrinochat/private/lets-chat/node_modules/require-tree/index.js:37:24)
    at Object.<anonymous> (/home/portrinochat/private/lets-chat/app.js:33:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Linux 3.18.9-x86_64-jb1
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! lets-chat@0.4.2 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lets-chat@0.4.2 start script 'node app.js'.
npm ERR! This is most likely a problem with the lets-chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls lets-chat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/portrinochat/private/lets-chat/npm-debug.log
```

Any ideas?

**Comment by shuanzi** [comment]
I have something similar， too...

```
> lets-chat@0.4.2 prestart /home/xiquan/lets-chat
> migroose


> lets-chat@0.4.2 start /home/xiquan/lets-chat
> node app.js

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: watch ENOSPC
    at exports._errnoException (util.js:746:11)
    at FSWatcher.start (fs.js:1176:11)
    at Object.fs.watch (fs.js:1202:11)
    at createFsWatchInstance (/home/xiquan/lets-chat/node_modules/nunjucks/node_modules/chokidar/lib/nodefs-handler.js:24:15)
    at setFsWatchListener (/home/xiquan/lets-chat/node_modules/nunjucks/node_modules/chokidar/lib/nodefs-handler.js:47:19)
    at EventEmitter.NodeFsHandler._watchWithNodeFs (/home/xiquan/lets-chat/node_modules/nunjucks/node_modules/chokidar/lib/nodefs-handler.js:177:15)
    at EventEmitter.NodeFsHandler._handleDir (/home/xiquan/lets-chat/node_modules/nunjucks/node_modules/chokidar/lib/nodefs-handler.js:301:8)
    at EventEmitter.<anonymous> (/home/xiquan/lets-chat/node_modules/nunjucks/node_modules/chokidar/lib/nodefs-handler.js:342:12)
    at FSReqWrap.oncomplete (fs.js:99:15)

npm ERR! Linux 3.13.0-37-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! lets-chat@0.4.2 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lets-chat@0.4.2 start script 'node app.js'.
npm ERR! This is most likely a problem with the lets-chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls lets-chat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/xiquan/lets-chat/npm-debug.log
```

**Comment by ramanandapanda** [comment]
For solving the follwoing error:

Error: ENOENT, no such file or directory '/home/USER/local/:/home/USER/local/node_modules/app/models'


I end up with unseting the NODE_PATH by:

unset NODE_PATH

I don't know where let's chat is reassigning the NODE_PATH.

**Comment by simon8410** [comment]
I end up with unseting the NODE_PATH by:

unset NODE_PATH

**Comment by hhaidar** [comment]
@ramanandapanda turns out there's a bug with `require-tree` and NODE_PATH having just whitespace.
