### ISSUE TITLE
node.js crashes 

### ISSUE THREAD

**Issue by HeadhunterXamd** [sdelements/lets-chat#562]
let's chat crashes I use npm start.
here is the npm-debug.log...
http://pastebin.com/WkurazYZ 
```
D:\user\lets-chat>npm run-script migrate

> lets-chat@0.4.2 migrate D:\user\lets-chat
> migroose


D:\user\lets-chat>node app.js
D:\user\lets-chat\node_modules\mongoose\node_modules\mongodb\lib\server.js:228
        process.nextTick(function() { throw err; })
                                            ^
Error: Could not connect to database
    at NativeConnection.<anonymous> (D:\user\lets-chat\app.js:190:11)
    at NativeConnection.emit (events.js:104:17)
    at NativeConnection.Object.defineProperty.set (D:\user\lets-chat\node_modules\mongoose\lib\connection.js:105:14)
    at D:\user\lets-chat\node_modules\mongoose\lib\connection.js:444:23
    at D:\user\lets-chat\node_modules\mongoose\lib\drivers\node-mongodb-native\connection.js:57:21
    at D:\user\lets-chat\node_modules\mongoose\node_modules\mongodb\lib\db.js:203:14
    at null.<anonymous> (D:\user\lets-chat\node_modules\mongoose\node_modules\mongodb\lib\server.js:226:9)
    at g (events.js:199:16)
    at emit (events.js:110:17)
    at null.<anonymous> (D:\user\lets-chat\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\lib\topologies\server.js:255:68)
    at g (events.js:199:16)
    at emit (events.js:110:17)
    at null.<anonymous> (D:\user\lets-chat\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:77:12)
    at g (events.js:199:16)
    at emit (events.js:110:17)
    at Socket.<anonymous> (D:\user\lets-chat\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\lib\connection\connection.js:118:49)
```

this is the error I get when I try the run-script migrate command.

for the record I have a mongodb instance running.

this is on windows 7 64-bit, I used the npm install (github.com/sdelements/lets-chat/wiki/Installation ) option

**Comment by hhaidar** [comment]
Is mongo running?

**Comment by HeadhunterXamd** [comment]
the last thing mongo tells me in the console = [initandlisten] waiting for connections on port 27017

**Comment by hhaidar** [comment]
@HeadhunterXamd oh sorry I misread your original post

Are you able to connect using mongo shell in cmd?

**Comment by HeadhunterXamd** [comment]
it seems that the connection is working
```[initandlisten] connection accepted from 127.0.0.1:50802 #1 (1 connection now open)```

**Comment by HeadhunterXamd** [comment]
can this:
```
npm info it worked if it ends with ok
npm info using npm@2.11.2
-----> npm info using node@v0.12.5
npm info prestart lets-chat@0.4.2
```
be a problem?

**Comment by hhaidar** [comment]
@HeadhunterXamd nah your node/npm versions look fine

Also this is not a problem with migroose, the error is being thrown from app.js :/

**Comment by HeadhunterXamd** [comment]
yeah, changed it. 

When I look at the source code I see this:
```
/**
 * @fileOverview The **Server** class is a class that represents a single server topology and is
 * used to construct connections.
 *
 * **Server Should not be used, use MongoClient.connect**
 * @example
 * var Db = require('mongodb').Db,
 *   Server = require('mongodb').Server,
 *   test = require('assert');
 * // Connect using single Server
 * var db = new Db('test', new Server('localhost', 27017););
 * db.open(function(err, db) {
 *   // Get an additional db
 *   db.close();
 * });
 */
```
in the top of the source file at lets-chat\node_modules\connect-mongo\node_modules\mongodb\lib\server.js
what is this?

**Comment by HeadhunterXamd** [comment]
it seems to crash at line 228 of that server.js

**Comment by hhaidar** [comment]
Does `mongo --host localhost` work?

**Comment by HeadhunterXamd** [comment]
hmmm, yes it does...
should I make the database beforehand?

**Comment by hhaidar** [comment]
Maybe something is up with the connection string.

If you add `console.log('uri: ', settings.database.uri);`  at the bottom of app.js, what does it give you?

**Comment by HeadhunterXamd** [comment]
uri:  mongodb://localhost/letschat
it gives me this.

**Comment by hhaidar** [comment]
Yea that seems good too...

I don't know what's going on :(

**Comment by HeadhunterXamd** [comment]
which port does it use to connect to mongodb?

**Comment by hhaidar** [comment]
27017

**Comment by HeadhunterXamd** [comment]
seems to be correct... and still nothing? =/

**Comment by HeadhunterXamd** [comment]
can the problem be that my user is a domain account like computername.domain.local and user = username.domain.local?

**Comment by HeadhunterXamd** [comment]
alright seems to be fixed the problem came from a malformed hosts file...

**Comment by hhaidar** [comment]
@HeadhunterXamd haha that'll do it
