### ISSUE TITLE
Adding support for MongoDB replication set

### ISSUE THREAD

**Issue by galal-hussein** [sdelements/lets-chat#564]
It would be great if the application driver has support for MongoDB replica set to auto route the writes the master db to and autodetect when primary server goes down, my guess about implementing such thing is to have a configuration for a seed list of Mongo backends and then checking for primary server upon connection.

**Comment by hhaidar** [comment]
@galal-hussein should already be supported (we use mongoose):

http://mongoosejs.com/docs/connections.html#replicaset_connections

Just change the database uri in settings.

**Comment by galal-hussein** [comment]
That's great, thank you very much.
