### ISSUE TITLE
npm run migrate 

### ISSUE THREAD

**Issue by HeadhunterXamd** [sdelements/lets-chat#569]
in short : 
```
D:\user\let\lets-chat>npm start

> lets-chat@0.4.2 prestart D:\user\let\lets-chat
> migroose
```
here I get an error-popup: 
migroose.js
Object expected
Code: 800A138F
```

> lets-chat@0.4.2 start D:\user\let\lets-chat
> node app.js

Database migration required
Ensure you backup your database first.

Run the following command: npm run migrate

D:\user\let\lets-chat>npm run-script migrate

> lets-chat@0.4.2 migrate D:\user\let\lets-chat
> migroose
```

same here
```


D:\user\let\lets-chat>
```

**Comment by hhaidar** [comment]
Might be related to this: #352 

Have you considered using vagrant or docker?

**Comment by HeadhunterXamd** [comment]
I will try that tommorrow, also the fix that is proposed in issue #352 is something I will attempt tommorrow. I will let you know :)

**Comment by 1337sup3rh4x0r** [comment]
I tried the fix in #352 but it didn't help. Vagrant works for now, as long as you don't halt it as described in #566

**Comment by HeadhunterXamd** [comment]
it seems that the solution in issue #352 has worked \o/
but for so far no one can join :/
I have tried it with vagrant and even that wasn't working for me, one time I had a "working version" but no one could reach it...

**Comment by sibartlett** [comment]
We have removed migroose from Let's Chat.
