### ISSUE TITLE
Database encryption

### ISSUE THREAD

**Issue by Bakies** [sdelements/lets-chat#570]
Right now it looks like messages are in clear text in the database. I would like to have encryption at rest.

**Comment by hhaidar** [comment]
You could probably change the model to do this. Might be computationally expensive having to decrypt if you have a bunch.

**Comment by geoffwhittington** [comment]
You might be better served installing the database onto an encrypted volume.

**Comment by HeadhunterXamd** [comment]
Why do you want to have encryption on the messages?

**Comment by hhaidar** [comment]
No plans to do this as of yet, maybe someone can experiment in a fork.
