### ISSUE TITLE
New Docker Install - Connection Reset

### ISSUE THREAD

**Issue by SparserLogic** [sdelements/lets-chat#573]
Howdy folks,

I've tried installing lets-chat two different ways now (from source and via docker) and neither method has worked.

There's no errors logged, the log shows the fancy ASCII art, but no matter what I do I'm getting "Connection Refused" and I'm kinda stuck. Nothing is responding, its running but I cannot get any output other than the successful looking log.

Thoughts? I'm inside a corporate network running behind a proxy. I have Mongo setup as another local Mongo container named some-mongo. My docker command:

docker run  --name blst_letschat --link some-mongo:mongo -p 3000:5000 -d sdelements/lets-chat

Docker Inspect details below. Thanks!

[
{
    "Id": "fc6f9946d8f9f0e9ab453d24adf5df49e35ca3e9847730418fe92e0eff7db8d1",
    "Created": "2015-07-24T16:43:08.912867331Z",
    "Path": "npm",
    "Args": [
        "start"
    ],
    "State": {
        "Running": true,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 13203,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2015-07-24T16:43:09.327130707Z",
        "FinishedAt": "0001-01-01T00:00:00Z"
    },
    "Image": "109abf722473fddf8f2af4fc14c79ce06d1334de24f42a622c3060ffeb1ffc24",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "8effc34f702d6d1fe6991a143fb959c6cec3a55b947d90530bd13fb6dbbf3b09",
        "Gateway": "172.17.42.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "172.17.0.3",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "02:42:ac:11:00:03",
        "NetworkID": "edfe6e9afe8a637e057f58952839b978ae3c7614d13aea810d068aade6588000",
        "PortMapping": null,
        "Ports": {
            "5000/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "3000"
                }
            ],
            "5222/tcp": null,
            "8080/tcp": null
        },
        "SandboxKey": "/var/run/docker/netns/fc6f9946d8f9",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "ResolvConfPath": "/var/lib/docker/containers/fc6f9946d8f9f0e9ab453d24adf5df49e35ca3e9847730418fe92e0eff7db8d1/resolv.conf",
    "HostnamePath": "/var/lib/docker/containers/fc6f9946d8f9f0e9ab453d24adf5df49e35ca3e9847730418fe92e0eff7db8d1/hostname",
    "HostsPath": "/var/lib/docker/containers/fc6f9946d8f9f0e9ab453d24adf5df49e35ca3e9847730418fe92e0eff7db8d1/hosts",
    "LogPath": "/var/lib/docker/containers/fc6f9946d8f9f0e9ab453d24adf5df49e35ca3e9847730418fe92e0eff7db8d1/fc6f9946d8f9f0e9ab453d24adf5df49e35ca3e9847730418fe92e0eff7db8d1-json.log",
    "Name": "/blst_letschat",
    "RestartCount": 0,
    "Driver": "aufs",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "Volumes": {
        "/usr/src/app/config": "/var/lib/docker/volumes/255fc642b02f9c672e2f52b1ce6f6cd1a4c49f0e2fa79f81c773ce0bbb119a74/_data",
        "/usr/src/app/uploads": "/var/lib/docker/volumes/b713fd9fef82843da0c7396a2167b37f755cdfe27300d19ee85001552cd916bc/_data"
    },
    "VolumesRW": {
        "/usr/src/app/config": true,
        "/usr/src/app/uploads": true
    },
    "AppArmorProfile": "",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": null,
        "ContainerIDFile": "",
        "LxcConf": [],
        "Memory": 0,
        "MemorySwap": 0,
        "CpuShares": 0,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": 0,
        "BlkioWeight": 0,
        "OomKillDisable": false,
        "Privileged": false,
        "PortBindings": {
            "5000/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "3000"
                }
            ]
        },
        "Links": [
            "/some-mongo:/blst_letschat/mongo"
        ],
        "PublishAllPorts": false,
        "Dns": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "VolumesFrom": null,
        "Devices": [],
        "NetworkMode": "bridge",
        "IpcMode": "",
        "PidMode": "",
        "UTSMode": "",
        "CapAdd": null,
        "CapDrop": null,
        "RestartPolicy": {
            "Name": "no",
            "MaximumRetryCount": 0
        },
        "SecurityOpt": null,
        "ReadonlyRootfs": false,
        "Ulimits": null,
        "LogConfig": {
            "Type": "json-file",
            "Config": {}
        },
        "CgroupParent": ""
    },
    "Config": {
        "Hostname": "fc6f9946d8f9",
        "Domainname": "",
        "User": "node",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "PortSpecs": null,
        "ExposedPorts": {
            "5000/tcp": {},
            "5222/tcp": {},
            "8080/tcp": {}
        },
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "NODE_VERSION=0.12.7",
            "NPM_VERSION=2.11.3",
            "PKG_JSON_URL=https://raw.githubusercontent.com/sdelements/lets-chat/master/package.json",
            "TAR_GZ_URL=https://github.com/sdelements/lets-chat/archive/master.tar.gz",
            "BUILD_DEPS=g++ gcc git make python",
            "LCB_PLUGINS=lets-chat-ldap lets-chat-s3",
            "LCB_DATABASE_URI=mongodb://mongo/letschat",
            "LCB_HTTP_HOST=0.0.0.0",
            "LCB_HTTP_PORT=8080",
            "LCB_XMPP_ENABLE=true",
            "LCB_XMPP_PORT=5222"
        ],
        "Cmd": [
            "npm",
            "start"
        ],
        "Image": "sdelements/lets-chat",
        "Volumes": {
            "/usr/src/app/config": {},
            "/usr/src/app/uploads": {}
        },
        "VolumeDriver": "",
        "WorkingDir": "/usr/src/app",
        "Entrypoint": null,
        "NetworkDisabled": false,
        "MacAddress": "",
        "OnBuild": null,
        "Labels": {}
    }
}
]

**Comment by sibartlett** [comment]
The Docker image is expecting you to bind to port 8080, try:

```
docker run --name blst_letschat --link some-mongo:mongo -p 3000:8080 -d sdelements/lets-chat
```

**Comment by SparserLogic** [comment]
THANK YOU! Here I am assuming I've made some massive mistake...

May I suggest you/someone update the install documentation to call this port binding out? Everywhere else it lists LetsChat as using 5000, not 8080.

**Comment by sibartlett** [comment]
The Docker readme does say 8080, but I'll take another look at the docs.
