### ISSUE TITLE
Passwords are send as plaintext

### ISSUE THREAD

**Issue by ibiBgOR** [sdelements/lets-chat#578]
I think that is a serious problem when using http and not https.

**Comment by maximilian-krauss** [comment]
Why is this a problem? Thats what SSL is for and you should use https.
Even your bank would send your stuff in plaintext if they offered http ...

**Comment by hhaidar** [comment]
Yea you can run with the https option on, or better yet a reverse proxy with nginx or something.

Unfortunately we can't hold peoples hands for this kind of thing :(
