### ISSUE TITLE
add documentation on file upload

### ISSUE THREAD

**Issue by veggiemonk** [sdelements/lets-chat#581]
Hi everyone, 

this is a really awesome project and it has a lot of nice features. :+1:

Just wanted to say that it took a while to find out where the uploaded files were stored so I can mount a volume in the docker container.

Now I know that
```
files:
  local:
    dir: uploads
```
means `/usr/src/app/uploads`

Keep it up, :smile:

**Comment by mtrycz** [comment]
I didn't check for sure, but you can probably give an absolute path to the properties, so you can mount whatever location you prefer (for example to have consistent paths with other contaniner, etc.).

But yeah, it's really awesome

**Comment by veggiemonk** [comment]
I tried to set the paths to  `/uploads` and got an error...

When set to `/usr/src/app/uploads` it works wonderfully!

Probably access rights/ user rights problem. But hey, it works!!!! So happy and thanks..

**Comment by hhaidar** [comment]
@mtrycz thank you <3

@veggiemonk awesome, glad to hear it worked!
