### ISSUE TITLE
url for date-range-picker-stylesheet is hardcoded to root-url

### ISSUE THREAD

**Issue by dudleyperkins** [sdelements/lets-chat#583]
i've changed the url path for lets-chat as mentioned in https://github.com/sdelements/lets-chat/issues/411#issuecomment-128661279

Now the date-range-picker in room history looks a bit "naked". Looking at the page-source you can see that most stuff is referenced relatively, like:
```
<link rel="icon" type="image/png" href="./media/favicon.ico" />
<link rel="stylesheet" href="./media/dist/vendor-0648a638b7d7eba0ae1ae24cffb30c81.css" />
<script src="./media/dist/vendor-9af5e921ef6ce5ac7bd5cb635ba434b1.js"></script>
```
But not this one:
```
<link rel="stylesheet" type="text/css" href="/media/js/vendor/bootstrap-daterangepicker/daterangepicker-bs3.css" />
```

I've added a redirect for /media so its working here now, but i think you should know ;)

**Comment by hhaidar** [comment]
ah, let me fix that.
