### ISSUE TITLE
Chat History Search - Blank Result

### ISSUE THREAD

**Issue by hamsal** [sdelements/lets-chat#584]
When I search chat history I always get blank results even if the word has been mentioned repeatedly. Is there something else I need to configure for search to work?

UPDATE:

this shows up in the terminal when I search:

```
{ name: 'MongoError',
  message: 'invalid operator: $search',
  '$err': 'invalid operator: $search',
  code: 10068 }
```

**Comment by hhaidar** [comment]
Try upgrading mongo: http://docs.mongodb.org/manual/core/index-text/

**Comment by hamsal** [comment]
Thanks, that is the same answer I got on the google group and that fixed it completely

**Comment by hhaidar** [comment]
@hamsal no worries, good to hear its working now :)
