### ISSUE TITLE
deploy to sloppy.io instructions

### ISSUE THREAD

**Issue by MikeMichel** [sdelements/lets-chat#585]
hi,

there is howto to deploy let's chat to http://sloppy.io (docker container platform) at https://github.com/sloppyio/quickstarters/tree/master/letschat 

if needed i can create a wiki page for that though i don't know how to do a PR for wiki pages.

mike

**Comment by hhaidar** [comment]
thank you, I've linked it in the wiki: https://github.com/sdelements/lets-chat/wiki
