### ISSUE TITLE
The height of the text area gradually lowers on Internet Explorer.

### ISSUE THREAD

**Issue by taguchimasahiro** [sdelements/lets-chat#589]
The height of the text area gradually lowers on Internet Explorer.
I put a 'a' enough to scroll, and the text area gradually lowers when I input messages.
I tried a demonstration site and the latest master.
This capture was token at a demonstration site.

Browser: Internet Explorer 11 (11.0.9600.17914)
OS: Windows 7

![ie11](https://cloud.githubusercontent.com/assets/4678370/9322524/692be950-45af-11e5-87e8-944e05d5a30d.JPG)

**Comment by taguchimasahiro** [comment]
I still confirm that I can fix it by setting 'min-height' in 'room.less'.

**Comment by taguchimasahiro** [comment]
Sorry.
I already confirm this problem is fixed that to set 'min-height' in 'room-less'.

**Comment by hhaidar** [comment]
Do you mind opening up a PR?
