### ISSUE TITLE
Fresh Install Dependency Issue

### ISSUE THREAD

**Issue by emperorcow** [sdelements/lets-chat#605]
I was just completing a fresh install and had a few issues when using LDAP for authentication.  In short, there is a problem in the lets-chat-ldap module where it calls passport-ldapauth.  There was a recent change in passport (noted here: https://github.com/jaredhanson/passport/issues/400) that changed some of the way authentication is handled in passport. 

This is beyond the scope of Let's Chat, but I did want to let you know that when you do a `npm install` after cloning the repository,  you will get a newer version of passport.socketio, which will request a newer version of passport.  

The temporary fix for me was to simply install version 3.5.1 or passport.socketio using `npm install passport.socketio@3.5.1 --save`, but I still wanted to let you know and so if others came along they would know as well.

**Comment by mootpt** [comment]
Seems like what I saw with: https://github.com/sdelements/lets-chat/issues/603

**Comment by peasead** [comment]
This fixed me as well.

**Comment by sibartlett** [comment]
Thanks for reporting the issue, I've updated package.json - and fixed the passport library versions.
