### ISSUE TITLE
connect to existing jabber server?

### ISSUE THREAD

**Issue by jonbayer** [sdelements/lets-chat#609]
Hi Guys,

I quite like your application, but we already have an in-house jabber server that I'd rather not migrate away from (openfire) due to some handy features like shared rostering. It's looking like it's not possible, but I just thought I'd check and verify if it is possible for let's chat to simple connect to an existing jabber server/conf. room and be more of a web UI for this. 

Apologies if this is a dumb question, I've just been looking everywhere for an app that will do this.

**Comment by sploadie** [comment]
Let's Chat allows XMPP clients to connect to it, but Let's Chat is not itself a client. If you are just looking for a Jabber web-client, maybe [Converse.js](https://conversejs.org/)?

**Comment by jonbayer** [comment]
Thanks for the response. I ended up going with kaiwa, as it's got the same UI concepts but connects to my existing jabber server. I still think highly of this project though and wish you guys the best of luck.
