### ISSUE TITLE
Adding tags to Docker image

### ISSUE THREAD

**Issue by alininja** [sdelements/lets-chat#611]
Hi,

Would it be possible to add tags to your automated build image on Docker Hub?

I'm not sure how easy or difficult it is:
http://stackoverflow.com/questions/25328166/docker-hub-automated-build-tagging

But I'm stuck trying to workaround this issue:
https://github.com/sdelements/lets-chat/issues/607

If there were tags, I can just use an earlier working image.  But right now, everything is tagged as latest and overwrites the previous build.

Thank you for such an awesome product!

**Comment by hhaidar** [comment]
Hey @alininja,

Sorry for the delay, I've tagged 0.4.3 in docker. Let me know if it works for you.

**Comment by alininja** [comment]
Hi @hhaidar , thanks for adding the tag.  I'll try the container out the next time I'm pulling images.  Keep up the awesomeness! :smile:
