### ISSUE TITLE
Bug in the custom range picker in transcript

### ISSUE THREAD

**Issue by mmeinert** [sdelements/lets-chat#614]
Custom range date picker in transcript doesn't allow me to choose a range greater than a month but writing the from/to date in the form works.

Surely a small bug but I can't find out :(

**Comment by bascht** [comment]
The selectable range was set on purpose by @sibartlett in d5d1bc01:
https://github.com/sdelements/lets-chat/blob/master/media/js/views/transcript.js#L63-L65
Could be because of performance issues. :)

**Comment by mmeinert** [comment]
@bascht That makes sense
