### ISSUE TITLE
lets-chat & nodejs 4.x = broken?

### ISSUE THREAD

**Issue by WBTMagnum** [sdelements/lets-chat#619]
## Description ##

On our application server (openSUSE 13.1) Node.js packages have been updated to V4.0.0 today. Afterwards lets-chat (installation from source) didn't run / start anymore.

### Reported errors ###

```
$ npm run-script migrate --verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node',
npm verb cli   '/usr/bin/npm',
npm verb cli   'run-script',
npm verb cli   'migrate',
npm verb cli   '--verbose' ]
npm info using npm@2.14.2
npm info using node@v4.0.0
npm verb run-script [ 'premigrate', 'migrate', 'postmigrate' ]
npm info premigrate lets-chat@0.4.2
npm info migrate lets-chat@0.4.2

> lets-chat@0.4.2 migrate /usr/local/src/lets-chat
> migroose

Segmentation fault
```

```
$ npm install

> node-stringprep@0.7.2 install /usr/local/src/lets-chat/node_modules/node-xmpp-core/node_modules/node-stringprep
> node-gyp rebuild

gyp: /usr/lib64/node_modules/npm/node_modules/node-gyp/addon-rpm.gypi not found (cwd: /usr/local/src/lets-chat/node_modules/node-xmpp-core/node_modules/node-stringprep) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib64/node_modules/npm/node_modules/node-gyp/lib/configure.js:358:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.11.10-29-desktop
gyp ERR! command "/usr/bin/node" "/usr/lib64/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/src/lets-chat/node_modules/node-xmpp-core/node_modules/node-stringprep
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
npm ERR! Linux 3.11.10-29-desktop
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! node-stringprep@0.7.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-stringprep@0.7.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-stringprep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-stringprep
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/src/lets-chat/npm-debug.log
```

## Questions ##
* Has anybody experienced similar issues?
* Is there a known incompatibility between lets-chat and Node.js V4.x (node-gyp)?
* Could this be a Node.js packaging error (I rarely work with node)?

## Current system status ##
For the time being I rolled back Node.js to the previous version (V0.12.7). lets-chat works like a charm again.

**Comment by knadendla** [comment]
i am facing similar issues..

**Comment by knadendla** [comment]
but i am using hipchat
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nadendk\\AppData
\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-stringprep@l
atest"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! node-stringprep@0.7.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-stringprep@0.7.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-stringprep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-stringprep
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\ProjectDevOpsBot\mydevopshipchat\npm-debug.log

**Comment by sonnyp** [comment]
https://github.com/sdelements/lets-chat/pull/628

**Comment by hhaidar** [comment]
Thanks again @sonnyp 

@WBTMagnum @knadendla we can close this once you try it out.

**Comment by WBTMagnum** [comment]
@sonnyp Thank you!
@hhaider lets-chat v0.4.4 is smoothly running with node v4.2.1 now.
