### ISSUE TITLE
HTML/XHTML formatting?

### ISSUE THREAD

**Issue by hany** [sdelements/lets-chat#625]
Is HTML/XHTML formatting supported? For example, our bot regularly pastes links like:

```
<a href="somewebsite">somewebsite</a>
```

But it seems to render as the raw text. XHTML is defined in [XEP-0071](http://www.xmpp.org/extensions/xep-0071.html). Is it supported?

**Comment by hhaidar** [comment]
Nope, is there anyway to change the output on your bot?

**Comment by hany** [comment]
Is there any way to support formatted text in any way?

**Comment by hhaidar** [comment]
Not at the moment unfortunately :(

**Comment by hany** [comment]
@hhaidar thanks for the quick replies. Any plans for something like this in the future?

**Comment by hhaidar** [comment]
@hany probably for markdown, not sure for HTML just yet

**Comment by hany** [comment]
@hhaidar markdown would be fantastic, as you can do pretty much everything. What is needed to implement this?

**Comment by hhaidar** [comment]
@hany more testing and perhaps some speed improvements. You can look at #365 

Both @sibartlett and I have been kind of busy the last few months with work stuff. Hopefully end of year we can get some of these things in master.

**Comment by hany** [comment]
OK, thanks @hhaidar. I'll close this issue out.

**Comment by WBTMagnum** [comment]
@hany If you need this for very specific patterns only, you could try to define custom replacement rules for the time being. See folder extras/replacements/.

**Comment by nmstoker** [comment]
Any word on this?  Looks like the PR #365 still needs to be merged...
