### ISSUE TITLE
MD5? No.

### ISSUE THREAD

**Issue by taoeffect** [sdelements/lets-chat#630]
Noticed: https://github.com/sdelements/lets-chat/blob/master/package.json#L65

Is this project actually using MD5? MD5 is [deprecated](https://duckduckgo.com/?q=md5+deprecated) because of multiple attacks on it. It is considered a weak hash function by modern standards and it shouldn't be used for anything.

Its presence is especially curious as the next line down in `package.json` lists bcrypt:

https://github.com/sdelements/lets-chat/blob/master/package.json#L67

**Comment by nomeaning777** [comment]
This project uses MD5 to get avatar from Gravatar( see https://en.gravatar.com/site/implement/hash/ ).
So I think using MD5 is not problem.

**Comment by taoeffect** [comment]
Ah, I see. Yeah, not much you can do about that except complain to Gravatar. Thanks for the explanation!

**Comment by hhaidar** [comment]
Yes passwords use bcrypt :)

**Comment by funkaoshi** [comment]
@hhaidar aaaaah yeah.
