### ISSUE TITLE
How to restart letschat in vagrant?

### ISSUE THREAD

**Issue by rabbits123456** [sdelements/lets-chat#631]
Hi, 

I was download lets-chat form vagrant page (https://github.com/sdelements/lets-chat/wiki/Vagrant), but it only works once. 

1. When I did 'vagrant reload' then it will crash to start lets-chat, the message in below.
<pre>
[chouy@pc lets-chat]$ vagrant up
Bringing machine 'lcb' up with 'virtualbox' provider...
==> lcb: Clearing any previously set forwarded ports...
==> lcb: Fixed port collision for 22 => 2222. Now on port 2200.
==> lcb: Clearing any previously set network interfaces...
==> lcb: Preparing network interfaces based on configuration...
    lcb: Adapter 1: nat
==> lcb: Forwarding ports...
    lcb: 5000 => 5000 (adapter 1)
    lcb: 5222 => 5222 (adapter 1)
    lcb: 22 => 2200 (adapter 1)
==> lcb: Running 'pre-boot' VM customizations...
==> lcb: Booting VM...
==> lcb: Waiting for machine to boot. This may take a few minutes...
    lcb: SSH address: 127.0.0.1:2200
    lcb: SSH username: vagrant
    lcb: SSH auth method: private key
    lcb: Warning: Connection timeout. Retrying...
    lcb: Warning: Connection timeout. Retrying...
    lcb: Warning: Remote connection disconnect. Retrying...
==> lcb: Machine booted and ready!
==> lcb: Checking for guest additions in VM...
    lcb: The guest additions on this VM do not match the installed version of
    lcb: VirtualBox! In most cases this is fine, but in rare cases it can
    lcb: prevent things such as shared folders from working properly. If you see
    lcb: shared folder errors, please make sure the guest additions within the
    lcb: virtual machine match the version of VirtualBox you have installed on
    lcb: your host and reload your VM.
    lcb: 
    lcb: Guest Additions Version: 4.2.0
    lcb: VirtualBox Version: 5.0
==> lcb: Mounting shared folders...
    lcb: /vagrant => /home/chouy/test/talk/lets-chat
==> lcb: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> lcb: flag to force provisioning. Provisioners marked to run always will still run.
</pre>

2. I can did 'vagrant ssh' to vagrant area, then it failed to start.

<pre>
 [chouy@pc  lets-chat]$ vagrant ssh
vagrant@precise32:~$ cd lets-chat/
vagrant@precise32:~/lets-chat$ npm start

> lets-chat@0.4.4 prestart /home/vagrant/lets-chat
> migroose

> lets-chat@0.4.4 start /home/vagrant/lets-chat
> node app.js

fs.js:666
  return binding.readdir(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '/usr/lib/nodejs/app/models'
    at Object.fs.readdirSync (fs.js:666:18)
    at require_tree (/home/vagrant/lets-chat/node_modules/require-tree/index.js:56:8)
    at Object.<anonymous> (/home/vagrant/lets-chat/app.js:33:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

npm ERR! lets-chat@0.4.4 start: `node app.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the lets-chat@0.4.4 start script.
npm ERR! This is most likely a problem with the lets-chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls lets-chat
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.2.0-23-generic-pae
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /home/vagrant/lets-chat
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/vagrant/lets-chat/npm-debug.log
npm ERR! not ok code 0
</pre>

Is someone have this problem, how are you fix it?

Thank you.

**Comment by mmaedler** [comment]
This fixed it for me:
```
~# vagrant ssh
~# cd lets-chat
~# unset NODE_PATH
~# npm start
```

**Comment by rabbits123456** [comment]
@mmaedler  cool~  it works to display "Let's Chat"  on terminal, but it can't connect with browser, did you have this problem?


<pre>
vagrant@precise32:~/lets-chat$ npm start

> lets-chat@0.4.4 prestart /home/vagrant/lets-chat
> migroose


> lets-chat@0.4.4 start /home/vagrant/lets-chat
> node app.js


██╗     ███████╗████████╗███████╗     ██████╗██╗  ██╗ █████╗ ████████╗
██║     ██╔════╝╚══██╔══╝██╔════╝    ██╔════╝██║  ██║██╔══██╗╚══██╔══╝
██║     █████╗     ██║   ███████╗    ██║     ███████║███████║   ██║   
██║     ██╔══╝     ██║   ╚════██║    ██║     ██╔══██║██╔══██║   ██║   
███████╗███████╗   ██║   ███████║    ╚██████╗██║  ██║██║  ██║   ██║   
╚══════╝╚══════╝   ╚═╝   ╚══════╝     ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝

Release 0.4.4
</pre>


<pre>
http://localhost:5000/
錯誤代碼：ERR_CONNECTION_RESET
</pre>



And this was I checked the result for port 5000.
<pre>
vagrant@precise32:~$ ss -an4
State      Recv-Q Send-Q                  Local Address:Port                    Peer Address:Port 
LISTEN     0      128                         127.0.0.1:27017                              *:*     
LISTEN     0      128                                 *:111                                *:*     
LISTEN     0      128                         127.0.0.1:28017                              *:*     
LISTEN     0      128                                 *:49330                              *:*     
LISTEN     0      128                                 *:22                                 *:*     
LISTEN     0      128                         127.0.0.1:5000                               *:*     
</pre>

**Comment by mmaedler** [comment]
@rabbits123456 Good to hear that this helped you! 
The problem you are now facing might be because you set ```host``` in the ```http``` section to either ```127.0.0.1``` or ```localhost``` in your settings.yml. This might be correct from the vms point of view, but you are trying to access the vm from "outside" aka from the host. Therefore, lets chat is running, but not bound to the correct vm network interface. 
If you replace ```127.0.0.1``` (or localhost) with ```0.0.0.0``` it should work.

**Comment by rabbits123456** [comment]
@mmaedler I followed your steps and it worked. Thanks a lot.
