### ISSUE TITLE
How to invite user?

### ISSUE THREAD

**Issue by rabbits123456** [sdelements/lets-chat#640]
Hi,

How can I invite user to join a password chatroom ??
Because in that private chatroom, I only see my login in the list.

Thanks.

**Comment by rabbits123456** [comment]
Hi,

I found a way to join user to a password room.

a. Add Room / click 'Private' and set 'Password' and 'Confirm Password' / save
b. going to just create room / click 'Edit Room'
c. typing 'Password' 'Confirm Password' and add user login to 'Participants' / save

If user in participants list, when they login let's chat they won't typing password then can talk in that room.

Thanks.

**Comment by hhaidar** [comment]
@rabbits123456 cool, closing this for now.
