### ISSUE TITLE
If I forgot my let's chat password??

### ISSUE THREAD

**Issue by rabbits123456** [sdelements/lets-chat#642]
Hi,

I was build the let's chat in vagrant and test, and I can't find a place to reset my password. 
Because maybe user was forgot their password, but in the UI it no options can let user do resent their password from system, or sent a default password from system to my email?

Is this function needs install another plugin? or should I need add in settings.yml? 

Thanks.

**Comment by mmeinert** [comment]
Hi,
Personnaly I use LDAP to handle credentials and it works well, except that the user can't change his informations from the app so I had to create a side form to allow it.
Issue #616 is open related this "problem".

**Comment by hhaidar** [comment]
@rabbits123456 yea unfortunately you need to go into the database to reset passwords. Most people who run Let's Chat (including us) use an external auth provider such as LDAP or Kerberos.

**Comment by hhaidar** [comment]
@rabbits123456 if you need to reset a specific user, I can help you with that as well. Please let me know.

**Comment by rabbits123456** [comment]
@mmeinert @hhaidar 

Sorry I have a lot of questions want to ask... 

1. Because we think we don't want to use LDAP to do Let's Chat authentication, so if user really forgot their password, how can we do? 
2. I was run it on vagrant, but I don't know how to going to database? 
3. where can I looking for registration accounts? 
4. Can I enable all of rooms by default?
5. I was found a way to invite user to a private room (#640), but if we forgot the room creator, how can we add new user to that room? 


 Thank you.

**Comment by iamatulsingh** [comment]
@hhaidar can you please help me to make forgot password page?
