### ISSUE TITLE
`npm start` doesn't work

### ISSUE THREAD

**Issue by webinfinite** [sdelements/lets-chat#645]
I am running this binary on my mac. I followed the instruction for installation. The error I am having copied from lets-chat/npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/5.1.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.3.12
3 info using node@v5.1.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle lets-chat@0.4.4~prestart: lets-chat@0.4.4
6 verbose lifecycle lets-chat@0.4.4~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle lets-chat@0.4.4~prestart: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/GelinZHU/lets-chat/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
8 verbose lifecycle lets-chat@0.4.4~prestart: CWD: /Users/GelinZHU/lets-chat
9 silly lifecycle lets-chat@0.4.4~prestart: Args: [ '-c', 'migroose' ]
10 silly lifecycle lets-chat@0.4.4~prestart: Returned: code: 1  signal: null
11 info lifecycle lets-chat@0.4.4~prestart: Failed to exec prestart script
12 verbose stack Error: lets-chat@0.4.4 prestart: `migroose`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
12 verbose stack     at emitTwo (events.js:87:13)
12 verbose stack     at EventEmitter.emit (events.js:172:7)
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
12 verbose stack     at emitTwo (events.js:87:13)
12 verbose stack     at ChildProcess.emit (events.js:172:7)
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
12 verbose stack     at emitTwo (events.js:87:13)
12 verbose stack     at ChildProcess.emit (events.js:172:7)
12 verbose stack     at maybeClose (internal/child_process.js:818:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
13 verbose pkgid lets-chat@0.4.4
14 verbose cwd /Users/GelinZHU/lets-chat
15 error Darwin 14.5.0
16 error argv "/usr/local/Cellar/node/5.1.1/bin/node" "/usr/local/bin/npm" "start"
17 error node v5.1.1
18 error npm  v3.3.12
19 error code ELIFECYCLE
20 error lets-chat@0.4.4 prestart: `migroose`
20 error Exit status 1
21 error Failed at the lets-chat@0.4.4 prestart script 'migroose'.
21 error Make sure you have the latest version of node.js and npm installed.
21 error If you do, this is most likely a problem with the lets-chat package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     migroose
21 error You can get their info via:
21 error     npm owner ls lets-chat
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]

**Comment by mmeinert** [comment]
Don't think node 5.1.1 is supported, the [changelog](https://github.com/sdelements/lets-chat/blob/186dba1af2b1e80b189375c19ab7638bc3804d26/CHANGELOG.md#044-2015-10-26) of the current latest version (0.4.4) indicates support of node v4.

**Comment by webinfinite** [comment]
My OSX is yosemite. While I tried to download node v4, it says it cannot be done since it wont' work on any OSX version newer than mountain lion. 

Is there anyway else to resolve this issue? 

thanks.

**Comment by mpartipilo** [comment]
That doesn't make sense, there's no reason node 4 wouldn't work perfectly
on Yosemite.

You could also try to get it going with Docker.

**Comment by hhaidar** [comment]
@webinfinite I run 5.1.1 locally and it works just fine. Is mongodb running on your box and are the settings correct in settings.yml/env?

**Comment by webinfinite** [comment]
No, I haven't set up mangodb yet. This might be the problem. Will update
this thread while I find out.

Thanks.

**Comment by webinfinite** [comment]
OK, set up mongodb on my machine. The error still is the same: 

zhugelindeMacBook-Pro:lets-chat GelinZHU$ npm start

> lets-chat@0.4.4 prestart /Users/GelinZHU/lets-chat
> migroose


/Users/GelinZHU/lets-chat/node_modules/mongoose/node_modules/mongodb/lib/server.js:235
        process.nextTick(function() { throw err; })
                                      ^
Error: connect ECONNREFUSED 127.0.0.1:27017
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/5.1.1/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.1.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! lets-chat@0.4.4 prestart: `migroose`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lets-chat@0.4.4 prestart script 'migroose'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lets-chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     migroose
npm ERR! You can get their info via:
npm ERR!     npm owner ls lets-chat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/GelinZHU/lets-chat/npm-debug.log

**Comment by hhaidar** [comment]
> Error: connect ECONNREFUSED 127.0.0.1:27017
> at Object.exports._errnoException (util.js:856:11)

@webinfinite mongo is definitely not running (or perhaps the app can't reach it for some reason). Try using the mongo shell client and see if that will connect: https://docs.mongodb.org/getting-started/shell/client/

**Comment by webinfinite** [comment]
After start my mongod, it works. Thanks for all your guys help.

**Comment by hhaidar** [comment]
@webinfinite awesome, good to hear :D
