### ISSUE TITLE
LCB_XMPP_DOMAIN instead of LCB_XMPP_HOST

### ISSUE THREAD

**Issue by wasapi** [sdelements/lets-chat#646]
I noticed that since xmpp.host is deprecated, the env variable LCB_XMPP_HOST don't work anymore for docker, I had to use LCB_XMPP_DOMAIN.
This wiki page need an update : https://github.com/sdelements/lets-chat/wiki/Environment-variables

**Comment by sibartlett** [comment]
Thanks for letting us know that the docs were out of date.

We switched away from HOST to DOMAIN - as it wasn't consistent with the HTTP and HTTPS HOST settings.
