### ISSUE TITLE
Docker vs. Vagrant vs. Heroku

### ISSUE THREAD

**Issue by warent** [sdelements/lets-chat#649]
Howdy,

I proposed before that we only use Vagrant for lets-chat, while leaving out Heroku and Docker.

Previous response from @sibartlett:
> Regarding Docker and Heroku: We'll still want to keep them. There's a large number of people using Docker, and Heroku is really useful for setting up a quick demo installation.

There's also a large number of people using Vagrant, and Vagrant is also useful for setting up quick demo installations.
```bash
$ vagrant up
$ vagrant share
```
It's that simple. Are we really suggesting bloating the project to cater to every individual? I can't see any justification for this. Please explain.

**Comment by mpartipilo** [comment]
+1 on keeping Docker support. It takes less effort to write a Dockerfile than writing this here.

**Comment by funkaoshi** [comment]
Simon already explained this to you, but I don't mind repeating him here: "There's a large number of people using Docker, and Heroku is really useful for setting up a quick demo installation." What other justification do you need exactly?

**Comment by geoffwhittington** [comment]
Maybe the issue might have been better rephrased to propose splitting out the vagrant, heroku, docker support to a different repo?

**Comment by funkaoshi** [comment]
I think it'd be worth pulling them out if maintaining the files / support was in itself a large amount of code, or a distracting amount of work. In this case it strikes me as neither.

I'd add that a lot of the initial popularity of the project came from being easily deployable on Heroku.
