### ISSUE TITLE
LESS vs. SASS

### ISSUE THREAD

**Issue by warent** [sdelements/lets-chat#650]
Hi,

I would like to propose that we move from the archaic LESS to the industry standard SASS.
http://www.zingdesign.com/less-vs-sass-its-time-to-switch-to-sass/

If there is disagreement here, can someone please provide reasons against this?

Thanks!

**Comment by AustinPaquette** [comment]
:+1: +1

**Comment by hhaidar** [comment]
We're 100% on-board as well, this is happening in #653
