### ISSUE TITLE
Moving away from Nunjucks Templates

### ISSUE THREAD

**Issue by warent** [sdelements/lets-chat#652]
Greets,
I love nunjucks templating as much as the next person, but I think there are reasons lets-chat would work better without them.

If we use Angular ui-routing with ngTemplating *partials* then all HTML be statically cached within the Angular app. This means every single request will be serving from the client cache to save enormous server data strain. The best way to do this is to create the application in a tree structure, and then use some kind of builder (i.e. Gulp) to minify, uglify, and concatenate all of the client **application** JS files into one, and all of the **vendor** JS files into another. So every HTML page request will only have two script files: vendor.js, application.js.

Using ui-router will also allow us to ensure that lets-chat remains a *single-page web application*
Remember that we're building a web app, not a website.

Does that make sense? Please debate.

**Comment by WBTMagnum** [comment]
While following your recent comments, the following catched my eye:
> ... and concatenate all of the client application JS files into one, and all of the vendor JS files into another. So every HTML page request will only have two script files: vendor.js, application.js.

With the advent of http2 this might not be the best approch anymore, see http://rmurphey.com/blog/2015/11/25/building-for-http2

**Comment by warent** [comment]
@WBTMagnum 
Very good point! I'm also very excited about http2.
Conversely, however, the support is still [rather limited.](http://caniuse.com/#feat=http2)

It seems that maybe about one in three people wouldn't be able to use http2.

Thoughts?

**Comment by WBTMagnum** [comment]
Yes, http2 is still a bit "limited", but it for sure is the future. Also the proposed changes will probably take some time to land in lets-chat's master branch. Until then http2 support will be higher ;-)

**Comment by warent** [comment]
Well I for one sincerely hope that bureaucracy doesn't stunt the growth or development of lets-chat

**Comment by funkaoshi** [comment]
We are planning on moving away from the current approach to the front end code. So don't worry, nunjucks templates will disappear as part of that re-write.

There are zero plans to switch to Angular, though. Sorry.
