### ISSUE TITLE
is lets-chat work for heroku production deployment?

### ISSUE THREAD

**Issue by thomasjoyce** [sdelements/lets-chat#660]
hi,
    just wanted to use this awesome  open source chat system on my site and was wondering if all the features will work well with heroku production deployment? 

anyone has issue with heroku prod deployment ?

any suggestion what platform besides heroku is ideal for lets-chat to work out of the box and easy to add on to a website? Thanks for any pointers helps ;- )

**Comment by hhaidar** [comment]
Heroku should work fine, but we highly recommend using docker. I would also suggest tying authentication to something like ldap/kerberos/or one of the other plugins available.

**Comment by thomasjoyce** [comment]
Hi :- ) thanks for responding. i'm not familiar with docker but will read more about it online. any idea why u like docker specifically for lets-chat to be run on it? thanks for your guidance Houssam :-)

**Comment by hhaidar** [comment]
@thomasjoyce it runs on any platform and we pay the most attention to it (aside from local deployment on OSX haha).

Just to reiterate, Heroku is fine too!
