### ISSUE TITLE
Users/files sidebar empty in Chrome

### ISSUE THREAD

**Issue by RobThree** [sdelements/lets-chat#668]
The right sidebar in Chrome doesn't show anything; works fine in Firefox.

Firefox 43.0.4 | Chrome 48.0.2564.82 (64 bit)
------------- | -------------
![sc1](https://cloud.githubusercontent.com/assets/607888/12505284/b69ed8bc-c0e5-11e5-8672-184bb4f45d5b.png) | ![sc2](https://cloud.githubusercontent.com/assets/607888/12505285/b6a0467a-c0e5-11e5-914f-eefca062a08e.png)

There are no js messages or errors in the console log. Also Opera 34.0, IE 11.63 and Edge 25.10586 are fine as well.

**Comment by RobThree** [comment]
Actually, had another computer with Chrome 47.0.2526.111 on it: displays fine. Updated it to 48.0.2564.82 -> same problem. So it broke somewhere after 47.0.2526.111

**Comment by hhaidar** [comment]
Should be fixed now, thanks @RobThree
