### ISSUE TITLE
Connecting to external XMPP server

### ISSUE THREAD

**Issue by GodLesZ** [sdelements/lets-chat#669]
Hi folks,

is it possible to connect to an existing/running xmpp server using Lets Chat?
Just saw the xmpp usage (https://github.com/sdelements/lets-chat/blob/master/app/xmpp/index.js) and it seems to be only working with an internal self-hosted instance.

Any chance for bringing this up?
I want to use Lets Chat only as an xmpp client and later on bridge it on |https://github.com/atom/electron

**Comment by hhaidar** [comment]
Do you mean a server to server connection or something? That is not possible. Neither is using the client as an XMPP client.

If you throw the client into an electron container, it would definitely be possible with a lot of glue. I'm not sure it would be worth it though, as there are some very decent XMPP clients out there (something like https://github.com/jcbrand/converse.js)
