### ISSUE TITLE
Has anybody built a SAAS solution with lets-chat?

### ISSUE THREAD

**Issue by dalareo** [sdelements/lets-chat#675]
I would like to build a SaaS solution based on lets-chat, similar to Slack, Noysi and others. I am looking for a Node.js project that could serve as home-page, user registration and subscription management and make deployment of different lets-chat projects. Has anyone tried something similar? Any clue?

Thanks.

**Comment by funkaoshi** [comment]
I don't think anyone has yet. It's certainly do-able, though Let's Chat (currently!) lags behind Slack in terms of features. I think it's big feature/win is that it's hosted.

If there was a SaaS offering i'm not sure why someone wouldn't just choose Slack. (Sorry @hhaidar! Ha.)

**Comment by funkaoshi** [comment]
I think to start you'd need to add support for multi-tenancy. Otherwise you'd have to deploy an instance of Let's Chat for each client.

**Comment by funkaoshi** [comment]
I'm going to close this: it's not really an issue.
