### ISSUE TITLE
Define 'small' in small teams, please ;)

### ISSUE THREAD

**Issue by JoeMurray** [sdelements/lets-chat#677]
Just wondering how appropriate this would be for an open source community that tends to have several dozen lurkers in our irc? What's a reasonable volume of messages / users for a server instance with given specs (RAM, vCPUs, disk, I suppose are most relevant parameters). Eg to support 500 messages a day, perhaps 50 users typically logged in, with messages coming from our jenkins and github integrations to irc right now. We also have an old forum that still gets a dozen or two posts per day, and a stackexchange community it would be nice to integrate at some point that gets 12 questions a day and 18 answers a day on average, with, oh, maybe 30 comments a day. 2k users over there, many more accounts on the old forums.

**Comment by hhaidar** [comment]
The company I work at has about ~50 online user at any given moment with about 620k messages over two years. We also have multiple hubots (gitlab, jenkins, ci, etc) in multiple channels.

Hope that gives you an idea. Let me know if I can help with anything.

**Comment by JoeMurray** [comment]
That's quite useful, @hhaidar. What sort of system are you using for this, and are there any performance issues?

**Comment by hhaidar** [comment]
@JoeMurray a vm on a shared Xeon E5-2620 box with 1.5gb of ram allocated. Let's Chat itself usually sits at around ~200mb usage and mongodb around ~130. It's not particularly intensive on resources, you could probably run it just fine on less (not that you should haha).

**Comment by JoeMurray** [comment]
Thanks! Sounds like our load should be easy to handle. I should review what happens in UI with higher volume and frequency of content to make sure it doesn't degrade badly like some tools.
