### ISSUE TITLE
Lets-Chat behind nginx reverse Proxy

### ISSUE THREAD

**Issue by menzbua** [sdelements/lets-chat#680]
Hi @all,

did someone installed Lets-Chat behind an nginx reverse Proxy and can share the configuration with me. My problem at the moment is that the official URL is for example https://server.com/letschat/ and then the client tries to connect to https://server.com/login and this connect fails.

Thanks a lot

Regards
Manuel

**Comment by nomeaning777** [comment]
In my environment, this configuration works correctly.
```
 location /letschat/ {
   proxy_pass http://192.168.1.100:5000/;
   proxy_redirect /  /letschat/;
   proxy_redirect default;
   proxy_http_version 1.1;
   proxy_set_header Upgrade $http_upgrade;
   proxy_set_header Connection "upgrade";
   proxy_set_header Host $host;
 }
```

**Comment by menzbua** [comment]
That works.
Thanks a lot.

**Comment by hhaidar** [comment]
thank you @nomeaning777
