### ISSUE TITLE
Unable to access Lets-Chat

### ISSUE THREAD

**Issue by spantula** [sdelements/lets-chat#686]
Hello,
I have installed Lets-Chat on localhost and can access it via http://localhost:5000. 
How do I access this url from other systems 
for example if the IP of my local system is 192.168.234.59 can I access it like this

http://192.168.234.59:5000

At the moment when I try this I get web page not found.

Any ideas?

**Comment by hhaidar** [comment]
You'll need to change the `host` in your settings file:

https://github.com/sdelements/lets-chat/blob/master/settings.yml.sample#L11

Setting it to `192.168.234.59` should bind to that address.

**Comment by spantula** [comment]
Thanks, silly me, i have given the ip in quotes.

**Comment by hhaidar** [comment]
@spantula hah no worries :D
