### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by yeltsin** [sdelements/lets-chat#69]
Create a folder (and edit the code) to be able to translate the script to others languages.

**Comment by hhaidar** [comment]
Closing this for now. If enough people want it we then maybe it can be viable.

**Comment by Finkregh** [comment]
how do you determine is there are enough ppl?

:+1:

**Comment by avraf** [comment]
I am also interested in RTL and would want to contribute.

**Comment by hhaidar** [comment]
Everyone smiles in the same language! (#473)

**Comment by hhaidar** [comment]
So we have basic support in the develop branch now (soon to be release 0.4.0).

Some things we still gotta do:

* Translate client-side stuff
* Translate server responses
* Enable locale header detection
