### ISSUE TITLE
Locale language not changed

### ISSUE THREAD

**Issue by k0fi** [sdelements/lets-chat#696]
I have added 
```
i18n:
  locale: fr
```
to the end of settings.yml and restarted the server but the locale languge is still English. 
I also tried for other languages and saw no changes. Am I missing something? or it is a bug?
BTW,[ the wiki page](https://github.com/sdelements/lets-chat/wiki/i18n) about locales change missing a ':' after 'i18n'.

**Comment by hhaidar** [comment]
@k0fi thank you, it's been fixed

You can also now pass in an additional `locales` array in the yaml to allow visitors browser settings to determine the locale of their choosing.
