### ISSUE TITLE
Cloudron as installation option

### ISSUE THREAD

**Issue by nebulade** [sdelements/lets-chat#707]
The wiki mentions some installation options already and since we have packaged lets chat as a Cloudron app since some time now, it would be great if we could be added as another installation option.

One option would be to link our app package repository at https://github.com/cloudron-io/letschat-app
or directly put the link to install on a Cloudron https://cloudron.io/button.html?app=io.github.sdelements.lets_chat.cloudronapp

Usually the latter link is used with a Cloudron button, similar to other "deploy to" buttons, however a direct link in the bullet point list fits the layout of the wiki page maybe better.

Thanks in advance!

**Comment by nebulade** [comment]
Just saw that we are already mentioned in the Readme.md however with a link to the wiki page of a forked repo of lets chat. That might not be the best option, unless that wiki page could be put into the upstream wiki. What would be the process to get it in the main wiki?

**Comment by hhaidar** [comment]
@nebulade thank you, I've linked our README to the app package's README
