### ISSUE TITLE
How to make it work ?

### ISSUE THREAD

**Issue by barak-haviv** [sdelements/lets-chat#708]
I followed installation instruction on lubuntu 16.04 system
run npm start.
see the big LETS CHAT on my terminal.
not seeing any error message.
see nothing in my browser at
http://localhost:5000/
any idea ?
also change the node version to v0.12

**Comment by hhaidar** [comment]
Are you running it on a VM?

What do you have for `host` under http settings?

**Comment by barak-haviv** [comment]
No I am not using VM?
I started again from scratch and it work eventually.
The problem I think is that I started the installation with my current node/npm which is 6.3 and only after I had problems I saw the remark that it works only with old node I change my node version which not help in that stage.
So I guess it be useful to put a remark in the installation page to use node version v0.12
Thanks for your response

**Comment by hhaidar** [comment]
Np, glad it worked!
