### ISSUE TITLE
Documentation Installation Prerequisites update needed

### ISSUE THREAD

**Issue by SyZn** [sdelements/lets-chat#709]
The latest version seems not to work anymore on nodejs **v0.10.x.**
Got an error on using TLS with nodejs v0.10.43 stating that "createSecureContext" function is not available. NodeJS Documentation (https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options) told me that this function was added in v0.11.13.
Please change the requirement to at least nodejs **v0.11+**

**Comment by hhaidar** [comment]
Updated, thank you!
