### ISSUE TITLE
Wrong redirect after log out -> /login/ and not /lets-chat/login/

### ISSUE THREAD

**Issue by janstieler** [sdelements/lets-chat#718]
Hi,
I don't know what i'm doing wrong.
I installed lets-chat in a subfolder `lets-chat`, if I log me out I will redirected to xxx.de/login and not to xxx.de/lets-chat/login

Have I a mistake in my .htaccess
```
RewriteEngine On

RewriteCond %{SERVER_PORT} 80
RewriteRule ^lets-chat/(.*) http://localhost:myportnumber/$1 [P]
``` 

I don't have the most experience with node applications.

Cheers

**Comment by mmeinert** [comment]
Give a look at #411 , I think you'll find your answer

**Comment by janstieler** [comment]
@mmeinert Thanks, why I don't have found it last night?
Problem solved, thanks again!
