### ISSUE TITLE
Requesting an invalid file identifier crashes the server

### ISSUE THREAD

**Issue by dmbrown** [sdelements/lets-chat#759]
## Description
If the server (0.4.8 was confirmed) receives a request for a file path which references an invalid file identifier, an unhandled exception is encountered and the server crashes.

A valid file path is produced by the server once an upload is complete:
* `https://74c4b82a45a9f87a3c6b4d640de8e030.oasis.sandstorm.io/files/59839f4962c9d82300052d4a/rainbow_pony.jpg`

Replacing a single character in the file identifier, as shown below, reliably triggers the crash:
* `https://74c4b82a45a9f87a3c6b4d640de8e030.oasis.sandstorm.io/files/59839f4962c9d82300052d4b/rainbow_pony.jpg`

## letschat.log
`events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'type' of null
    at [LETSCHAT_ROOT]/app/controllers/files.js:72:31
    at Query.<anonymous([LETSCHAT_ROOT]/node_modules/mongoose/lib/model.js:3699:16)
    at [LETSCHAT_ROOT]/node_modules/mongoose/node_modules/kareem/index.js:273:21
    at [LETSCHAT_ROOT]/node_modules/mongoose/node_modules/kareem/index.js:127:16
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)

npm ERR! Linux 3.13.0-73-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! lets-chat@0.4.8 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lets-chat@0.4.8 start script 'node app.js'.
npm ERR! This is most likely a problem with the lets-chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls lets-chat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!    [LETSCHAT_ROOT]/npm-debug.log`

**Comment by hhaidar** [comment]
Thanks!

**Comment by bellune** [comment]
bonsoir quelqu'un peut m'aider stp?
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at net.js:1147:9
    at asyncCallback (dns.js:68:16)
    at Object.onanswer [as oncomplete] (dns.js:123:9)
