### ISSUE TITLE
Make it possible to mount lets-chat under a subpath on server

### ISSUE THREAD

**Issue by klugjohannes** [sdelements/lets-chat#78]
We want to deploy this in our intranet under a subdirecty (e.g. internal.acme.com/chat) behind nginx. Unfortunately the code seems to be littered with hard-coded url paths. Maybe I'm missing some important setting flag here, but this is rather inconvenient ;).

If this is wanted we can take some time to integrate and provide a patch for this feature. Some pointers on central places in the code might be useful, though.

**Comment by sibartlett** [comment]
This should be fixed in the next release (0.3) - which is coming very very soon!

**Comment by sibartlett** [comment]
0.3 has been merged into master

**Comment by sibartlett** [comment]
We did address this, but then in release 0.3.1 we introduced an asset pipeline - which outputs absolute paths in the HTML response.

However, if you use nginx or apache to proxy Let's Chat - you can configure them to rewrite the links in the HTML source.
