### ISSUE TITLE
User moderation, commands and permissions

### ISSUE THREAD

**Issue by bendicion** [sdelements/lets-chat#80]
We would really like if you can please help us with these features or questions.

Implement user moderation by using commands like these by the chat admin or the chat moderator: 
/mute (user) (#minutes)
/ban (user) (#days)
private message like /pm (user) (message)
/alert (message) and this alert would show in all rooms.
/close room (room name)
They don't necessarily have to be commands; they can also be options listed in a drop-down menu when right-clicking on the username.

Allow an admin to make or create a moderator user and assign /mute or /ban or any other available permissions.
List the admin name with a different color from the rest of the users and be listed at the top. List the moderator with a different color and be listed just below the admin.
List all regular users under admin and moderator.

Allow a regular user to type a command like /clear or click on an icon to clean the chat window.
Also, can a user, when entering any chat room, be presented with a blank screen and not see any previous lines of text?

We'd really appreciate your help.
Thank you in advance for your great work!

**Comment by funkaoshi** [comment]
Can track in #33.
