### ISSUE TITLE
Web Hooks/POSTS/Notifcations/Emails from external services.

### ISSUE THREAD

**Issue by william20111** [sdelements/lets-chat#88]
Sorry its a broad coverage there in title, but it would be great for any of these features in the future to be implemented. Allowing Nagios notifications to post something into the chat, or say failed builds from CI.

Thanks
William

**Comment by geoffwhittington** [comment]
@sibartlett proved me wrong. We have API tokens in 0.3 for the endpoints.

**Comment by hhaidar** [comment]
@sibartlett are we able to pass the token as a get/put/post parameter?

**Comment by geoffwhittington** [comment]
Looks like its a query parameter for any method ...

https://github.com/sdelements/lets-chat/blob/release/0.3.0/app/auth/index.js#L91

**Comment by sibartlett** [comment]
@geoffwhittington that's only for websockets - we'd still have to make a change for other endpoints

**Comment by geoffwhittington** [comment]
### Working sample

To send the message `hello there, this is a message` to a room called "test", given by the browser URL `http://localhost:5000/#!/room/54b86d184ff602080ef6d6d1` and having token `NTRiYzYz[... truncated ...]xYmE2MmJhYQ==`:

### Request

```
POST http://localhost:5000/messages
Authorization: Bearer NTRiYzYz[... truncated ...]xYmE2MmJhYQ==

{"text":"hello there, this is a message", "room": "54b86d184ff602080ef6d6d1"}
```

### Response

```
{
  "id": "54bdd4888ae374ac06e2bd1f",
  "room": {
    "id": "54b86d184ff602080ef6d6d1",
    "slug": "test",
    "name": "test",
    "description": "description",
    "lastActive": "2015-01-20T04:07:36.842Z",
    "created": "2015-01-16T01:44:56.539Z",
    "owner": "54b78f39ab48031b077e1f80"
  },
  "owner": {
    "id": "54bc639d2a453ff1046a6499",
    "firstName": "bob",
    "lastName": "bob",
    "username": "bobby",
    "displayName": "Bobby Smith",
    "avatar": "b325d79c4b6739c52d7c5c8f1ef2a817",
    "email": "bobby@aol.com",
    "local": true
  },
  "text": "hello there, this is a message",
  "posted": "2015-01-20T04:07:36.842Z"
}
```

**Comment by geoffwhittington** [comment]
We started to update the wiki https://github.com/sdelements/lets-chat/wiki with some API details

**Comment by funkaoshi** [comment]
0.3.0 is now in master.
