### ISSUE TITLE
XMPP bot / bridge

### ISSUE THREAD

**Issue by almereyda** [sdelements/lets-chat#99]
Maybe it would make sense to add an XMPP bot, so one could federate chatrooms between different interfaces (i.e. web on HD screen and XMPP via native mobile app)?

**Comment by geoffwhittington** [comment]
@almereyda Check out our wiki we've been adding to recently about XMPP:

https://github.com/sdelements/lets-chat/wiki

**Comment by almereyda** [comment]
@geoffwhittington Thanks to your recent comment, I've revisited my use case and can specify it now by delivering the following links.

#### Foundational Readings

* [XEP-0114: Jabber Component Protocol](http://xmpp.org/extensions/xep-0114.html)
* [Comparison of IRC, XMPP and PSYC](http://about.psyc.eu/Comparison)
* some [Existing Chat Servers & Clients](https://github.com/AgileVentures/EduChat/wiki/Existing-Chat-Servers-&-Clients)
* An essay about [Interconnecting XMPP and IRC](http://www.isode.com/whitepapers/interconnecting-xmpp-and-irc.html) from a commercial provider.

Prosody has a simple documentation about plugging in those components, but you find similiar Infos for `ejabberd`, too.

* [Prosody Components](http://prosody.im/doc/components)
* [Prosody Transports and Gateways](http://prosody.im/doc/transports_and_gateways)

#### Implementations

* https://github.com/hanzz/libtransport , a.k.a. spectrum.im, but the site is currently offline
* https://github.com/OchenZloy/ircgw , found via a weird russian blog article
* https://github.com/PaulFreund/I2X , consider it the dark web
* [`mod_irc` for `ejabberd`](https://www.ejabberd.im/mod_irc)
* [biboumi](http://biboumi.louiz.org/)
* [BitlBee](http://www.bitlbee.org/main.php/news.r.html)

---

We can therefore close this issue, as most questions have been solved somewhere else already (i.e. Hubot and Gateways).

I'll keep subscribed and update it nevertheless once I'm implementing such an infrastructure.

Currently I'm aiming for offering Let's Chat, Scrollback and Convos to the same conversations. More JS XMPP clients like Converse.js and Jappix, whose use cases are also covered by Scrollback somehow, remain in close consideration.
